### ISSUE TITLE
Fix delayed_job

### ISSUE THREAD

**Issue by enricostano** [openfoodfoundation/ofn-install#100]
### WAT
Some times it just stops working.

### TODO
 - clean up and document how to start/stop/restart the `delayed_job` process
 - add monitoring (we have monit but it's not enough)
 - investigate the issue and solve it

**Comment by myriamboure** [comment]
Pau has done a big spike on this, so I think we can close this now.

**Comment by sauloperez** [comment]
Yep, we haven't had any new problem with it
