### ISSUE TITLE
install python using ansible raw module

### ISSUE THREAD

**Issue by elf-pavlik** [openfoodfoundation/ofn-install#112]
https://github.com/openfoodfoundation/ofn-install/wiki/Setup#setup-a-server-instance

> You will need to ensure Python2.7 is installed on your server, and that /usr/bin/python points to Python2.7.

Ansible can ensure that and this way leave less to worry about for person using it.

Probably we could just add snippet from this gist
https://gist.github.com/gwillem/4ba393dceb55e5ae276a87300f6b8e6f

I could make PR, which playbook file do you think I should add it to?

**Comment by enricostano** [comment]
We use this [script](https://github.com/openfoodfoundation/ofn-install/blob/master/scripts/provisioning-dev.sh#L14) for now. I'm sure this can be better, I'm not sure an Ansible playbbok would be a good solution.

**Comment by elf-pavlik** [comment]
Why do you think using ansible raw module as in [this gist](https://gist.github.com/gwillem/4ba393dceb55e5ae276a87300f6b8e6f) doesn't make sense?

**Comment by enricostano** [comment]
I just think that adding an Python/YAML (Ansible) playbook to just do what one line in Bash would do maybe is too much. But maybe that's just me 😂

**Comment by Matt-Yorkley** [comment]
I'll look at making a new task for this now. It holds up fresh provisioning currently, and Aus and others might be provisioning new 16.04 servers soon with ofn-install. Also had someone on Slack setting up a new staging server, so lets iron out these creases...
