### ISSUE TITLE
ansible_user needed in inventory/hosts

### ISSUE THREAD

**Issue by elf-pavlik** [openfoodfoundation/ofn-install#113]
I might no fully understand as which user ansible should ssh into the machine. In my case, where I create LXD container with Ubuntu 16.04 i import my ssh key from github to root user following https://insights.ubuntu.com/2017/02/25/howto-automatically-import-your-public-ssh-keys-into-lxd-instances/
1. I run default_user playbook as root
2. after running `geerlingguy.security` role it blocks ssh access for root user and i need to use ofn-admin user to run playbooks

Currently for reasons above I have `ansible_user=ofn-admin` in `inventory/hosts`:
```
cornucopia.hackers4peace.net ansible_host=5.9.161.176 ansible_user=ofn-admin ansible_port=2222
```

And when I run `default_user` for the first time, as suggested on https://github.com/openfoodfoundation/ofn-install/wiki/Provisioning#default-user
I add to the command `-e 'ansible_user=root'` following tip in https://github.com/ansible/ansible/issues/4622#issuecomment-74083728

I think it could use little more documentation but firs I wanted to do little sanity check with you all.

**Comment by enricostano** [comment]
We always run `default_user` playbook with `root`, look [here](https://github.com/openfoodfoundation/ofn-install/blob/master/playbooks/default_user.yml#L6). That playbook will create the user `ofn-admin`, our system administrator.

All the other playbooks will run with [that user](https://github.com/openfoodfoundation/ofn-install/blob/master/playbooks/provision.yml#L4).

Also give maybe you want to give a look at our [script](https://github.com/openfoodfoundation/ofn-install/blob/master/scripts/create-container.sh) to build an LXC container for development environments. We're working on proposing a [wiki entry](https://github.com/coopdevs/ofn-install/wiki/OFN-DevEnv-Quick-Start), but still need some work.

We also need to backport a [more up to date script](https://github.com/coopdevs/timeoverflow-provisioning/blob/master/scripts/create-container.sh) to create LXC containers for a similar app that we also maintain.

**Comment by elf-pavlik** [comment]
> Also give maybe you want to give a look at our script to build an LXC container for development environments. We're working on proposing a wiki entry, but still need some work.

I just run `lxc launch ubuntu:x ofn` and rely on this config to add my ssh key from github to root user https://insights.ubuntu.com/2017/02/25/howto-automatically-import-your-public-ssh-keys-into-lxd-instances/

**Comment by enricostano** [comment]
Yeah, we're not using LXD. Just plain LXC as you can see from the scripts.
