### ISSUE TITLE
Remove SUPERUSER from pg user in development

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/ofn-install#118]
As https://github.com/openfoodfoundation/wishlist/issues/338 has been merged, there's no need for `SUPERUSER` privileges for the postgres user in development.

**Comment by enricostano** [comment]
https://github.com/openfoodfoundation/ofn-install/blob/bd9fbf9057de4754ab69911dcf050cb0d8c49b5d/playbooks/development.yml#L34

**Comment by sigmundpetersen** [comment]
development.yml was removed in https://github.com/openfoodfoundation/ofn-install/commit/fe83ee45b398ada0731ad630d78cd0cf806910a8 so closing this
