### ISSUE TITLE
OFN Germany: Map not working

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/ofn-install#129]
![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/46c8128c-347f-4ee4-b0b4-a0be3e1941bf)

![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/f473d785-8178-43ba-b197-55552c887bc6)

**Comment by enricostano** [comment]
@kirstenalarsen we need a Google Maps API for the DE instance, probably related to the Google account you're already creating for them to solve the email issue.

**Comment by enricostano** [comment]
It works now, I created a new API key associated to hallo @ openfoodnetwork.de and enabled Places and Javascript librearies.

**Comment by kirstenalarsen** [comment]
Is there a note somewhere in documentation/wiki about this? If not, could you add one? Thanks!

**Comment by kirstenalarsen** [comment]
still doesn't seem to be working for me 
![image](https://user-images.githubusercontent.com/2911176/37371928-3809a5ac-2765-11e8-95c6-5c1b19f670a6.png)

**Comment by enricostano** [comment]
Ok, probably the restrictions on domain are not working. Also probably would not work embedding the map in another web at other domain. We need to understand how we can manage that case.

**Comment by enricostano** [comment]
I removed the restriction :grimacing: , now it should work.

I also added soem documentation https://github.com/openfoodfoundation/ofn-install/wiki/Google-Maps
