### ISSUE TITLE
Bring in German language translations, keep English as option as well

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/ofn-install#130]
![image.png](https://images.zenhubusercontent.com/54b83fb37c6ccc6277a6ea46/b314ca0e-9fc7-4699-9a87-8d176fa4f7b8)

**Comment by enricostano** [comment]
This is done, we're just waiting for https://github.com/openfoodfoundation/openfoodnetwork/pull/2094 to get merged.

Also, you need to translate the `language_name` key in Transifex to "Deutch" (? :sweat_smile: )

**Comment by kirstenalarsen** [comment]
I have no idea how to do that @enricostano - I followed sigmund's instructions to use the google translate thing, i do not really know my way around transifex at all! can you explain? or i can see if i can add you to german to do it?

**Comment by kirstenalarsen** [comment]
is it to do with this?
![image](https://user-images.githubusercontent.com/2911176/37335244-181902d2-2702-11e8-9487-21d265fc2b4d.png)

**Comment by kirstenalarsen** [comment]
@mkllnk I see you are the coordinator of german - are you able to do the thing Enrico is saying above?

**Comment by sigmundpetersen** [comment]
Like this?

![deutsch](https://user-images.githubusercontent.com/1451633/37339552-54006eda-26bb-11e8-9c62-9626c202b557.png)

Done

**Comment by mkllnk** [comment]
Exactly Sigmund, done. Now we just need to merge the updated de_DE.yml into the ofn code.

**Comment by enricostano** [comment]
We were also waiting https://github.com/openfoodfoundation/ofn-install/pull/123 to get merged.

**Comment by sauloperez** [comment]
that one got merged yesterday

**Comment by enricostano** [comment]
Done here: https://github.com/openfoodfoundation/ofn-install/pull/133/commits/368d033516e46b29a6d2456801695c1f70ef2288

We're good to go now, only waiting for the next release :muscle:

**Comment by kirstenalarsen** [comment]
come on next release :)

**Comment by sauloperez** [comment]
Just wait for our night sleep and we'll have it tomorrow morning @kirstenalarsen 😜

**Comment by kirstenalarsen** [comment]
yay!

**Comment by enricostano** [comment]
Deployed latest OFN release that included DE translations. We're done here I guess, feel free to open again if you catchany other issue related to this.
