### ISSUE TITLE
OFN Germany: set up email

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/ofn-install#131]
have now set up
hallo@openfoodnetwork.de
password as per email @enricostano 

Thanks!

**Comment by enricostano** [comment]
@kirstenalarsen I cannot access the Gmail account. Is the password correct?

**Comment by kirstenalarsen** [comment]
@enricostano done, see slack

**Comment by enricostano** [comment]
@kirstenalarsen did you verified the domain in Google Suite? I cannot receive emails, can send though.

**Comment by enricostano** [comment]
Solved, there were some `MX` DNS records missing.

**Comment by enricostano** [comment]
I just discovered that Mailchimp / Mandrill removed the free trial.... I'll try Sendgrid free trial then :(

**Comment by enricostano** [comment]
Done with Sendgrid... we can send 100 emails per day.

**Comment by enricostano** [comment]
This is done.
