### ISSUE TITLE
Wrong url from email confirmation link in OFN.de

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/ofn-install#135]
takes me to . . 
http://demo.spreecommerce.com/user/spree_user/confirmation?confirmation_token=ftvoPPXSFx30Wn_hH6Zs

When I change it manually to openfoodnetwork.de it works

I had already updated the config previously (see img below) so it must be pulling this from somewhere else @enricostano ?

![image](https://user-images.githubusercontent.com/2911176/37584981-8a514ba4-2bab-11e8-9c12-81541d18bd6a.png)

**Comment by enricostano** [comment]
Mhh... we're having the same issue on https://staging.katuma.org @sauloperez

**Comment by sauloperez** [comment]
there's no automatic configuration for those settings whatsoever. I also experienced that from staging but that's normal if we do a `db:reset`. Not so sure about DE production :thinking:

**Comment by enricostano** [comment]
OK got it... when we manually change the Spree conficuration from `/admin` (General Settings) we also need to restart OFN unicorn and delayed_job... I just did it and it works now.

As a side note we also need to configure this kind of informations while setting up the server automatically.

**Comment by sauloperez** [comment]
> we also need to restart OFN unicorn and delayed_job... I just did it and it works now.

Any idea about how to document this? I did https://github.com/openfoodfoundation/ofn-install/wiki/Sending-emails-from-OFN#configuring-a-mail-method-automatically for the email settings.

> As a side note we also need to configure this kind of informations while setting up the server automatically.

It should be easy to do something similar to https://github.com/openfoodfoundation/openfoodnetwork/pull/2148. Also, https://github.com/openfoodfoundation/ofn-install/pull/141 is meant to address this when doing changes to configuration through `db:seed`.

**Comment by enricostano** [comment]
> It should be easy to do something similar to openfoodfoundation/openfoodnetwork#2148

Yes please :pray: :sob:
