### ISSUE TITLE
500 Server Error Blank Page Creating Enterprise on Vagrant Box

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/ofn-install#138]
@MikeiLL commented on [Thu Sep 03 2015](https://github.com/openfoodfoundation/openfoodnetwork/issues/663)

New install on Vagrant Box.:

```
vagrant@vagrant-ubuntu-precise-64:~/apps/pcolacoop/current/log$ tail -10 test.log 
  CACHE (0.0ms)  SELECT COUNT(*) FROM "spree_roles" INNER JOIN "spree_roles_users" ON "spree_roles"."id" = "spree_roles_users"."role_id" WHERE "spree_roles_users"."user_id" = 1 AND "spree_roles"."name" = 'admin'
  OrderCycle Load (0.3ms)  SELECT "order_cycles".* FROM "order_cycles" WHERE (order_cycles.orders_open_at <= '2015-09-03 06:35:34.314121' AND order_cycles.orders_close_at >= '2015-09-03 06:35:34.314124')
   (0.8ms)  SELECT COUNT(*) FROM "enterprises" INNER JOIN "distributors_shipping_methods" ON "distributors_shipping_methods"."distributor_id" = "enterprises"."id" INNER JOIN "spree_shipping_methods" ON "spree_shipping_methods"."id" = "distributors_shipping_methods"."shipping_method_id" INNER JOIN "distributors_payment_methods" ON "distributors_payment_methods"."distributor_id" = "enterprises"."id" INNER JOIN "spree_payment_methods" ON "spree_payment_methods"."id" = "distributors_payment_methods"."payment_method_id" WHERE "spree_payment_methods"."deleted_at" IS NULL AND "spree_payment_methods"."active" = 't' AND (spree_payment_methods.display_on='both' OR spree_payment_methods.display_on='' OR spree_payment_methods.display_on IS NULL) AND (spree_payment_methods.environment='test' OR spree_payment_methods.environment='' OR spree_payment_methods.environment IS NULL)
  CACHE (0.0ms)  SELECT COUNT(*) FROM "enterprises" INNER JOIN "distributors_shipping_methods" ON "distributors_shipping_methods"."distributor_id" = "enterprises"."id" INNER JOIN "spree_shipping_methods" ON "spree_shipping_methods"."id" = "distributors_shipping_methods"."shipping_method_id" INNER JOIN "distributors_payment_methods" ON "distributors_payment_methods"."distributor_id" = "enterprises"."id" INNER JOIN "spree_payment_methods" ON "spree_payment_methods"."id" = "distributors_payment_methods"."payment_method_id" WHERE "spree_payment_methods"."deleted_at" IS NULL AND "spree_payment_methods"."active" = 't' AND (spree_payment_methods.display_on='both' OR spree_payment_methods.display_on='' OR spree_payment_methods.display_on IS NULL) AND (spree_payment_methods.environment='test' OR spree_payment_methods.environment='' OR spree_payment_methods.environment IS NULL)
   (0.3ms)  SELECT COUNT(*) FROM "enterprises" WHERE (id IN (NULL)) AND (id NOT IN (NULL) OR 0=0)
  CACHE (0.0ms)  SELECT COUNT(*) FROM "spree_roles" INNER JOIN "spree_roles_users" ON "spree_roles"."id" = "spree_roles_users"."role_id" WHERE "spree_roles_users"."user_id" = 1 AND "spree_roles"."name" = 'admin'
  CACHE (0.0ms)  SELECT COUNT(*) FROM "spree_roles" INNER JOIN "spree_roles_users" ON "spree_roles"."id" = "spree_roles_users"."role_id" WHERE "spree_roles_users"."user_id" = 1 AND "spree_roles"."name" = 'admin'
  CACHE (0.0ms)  SELECT COUNT(*) FROM "spree_roles" INNER JOIN "spree_roles_users" ON "spree_roles"."id" = "spree_roles_users"."role_id" WHERE "spree_roles_users"."user_id" = 1 AND "spree_roles"."name" = 'admin'
Completed 500 Internal Server Error in 43.0ms
** [Bugsnag] No API key configured, couldn't notify
```

I though maybe a permission issue, but am new to Nginx and Ruby. Recursively 
- files seem to be set to `664`
- directories to `775`.

I'm used to php and apache and typically `644` and `755`.

Pointers? Insights?

---

@kirstenalarsen commented on [Thu Sep 03 2015](https://github.com/openfoodfoundation/openfoodnetwork/issues/663#issuecomment-137359461)

check discussion on forum (http://community.openfoodnetwork.org/t/need-help-to-fix-err-500/321) - I think this is the same thing (?) and am hoping that @pmackay might have some ideas . .

---

@MikeiLL commented on [Thu Sep 03 2015](https://github.com/openfoodfoundation/openfoodnetwork/issues/663#issuecomment-137457180)

Ah yes. Looks like the same thing. Thanks, @kirstenalarsen 

---

@myriamboure commented on [Tue Mar 20 2018](https://github.com/openfoodfoundation/openfoodnetwork/issues/663#issuecomment-374563037)

Has all lessons learned been documented ? To check.

---

@sigmundpetersen commented on [Tue Mar 20 2018](https://github.com/openfoodfoundation/openfoodnetwork/issues/663#issuecomment-374564574)

Is this more `ofn-install` than main code base? @sauloperez 

---

@sauloperez commented on [Tue Mar 20 2018](https://github.com/openfoodfoundation/openfoodnetwork/issues/663#issuecomment-374565681)

Definitely. If someone wants to setup a machine like production or staging, including Nginx etc, that's the thing to use. I'd close this one @myriamboure.

**Comment by myriamboure** [comment]
Done @sauloperez @sigmund

**Comment by sauloperez** [comment]
Do you mind if I close this one too? it's a very old issue and no one has complained about it since then.

**Comment by myriamboure** [comment]
We still need to decide what we do with it: is it fixed? Have all the lessons learned been documented?

**Comment by myriamboure** [comment]
No I don't @sauloperez but just would be great to quickly check if lessons learned have been documented. This has been fixed as both Mike and Gilles managed to set all that up finally... I don't have the tech skills to check documentation I'm afraid :-(

**Comment by sauloperez** [comment]
I'm afraid there isn't much we can do here. We don't have the whole picture of what that person actually did to end up with that error. We don't even know whether he ran the database migrations. So there's nothing we can document here.

We know `ofn-install` doesn't have that any problem like this because we provision our staging machines many times a day.

**Comment by myriamboure** [comment]
I meant http://community.openfoodnetwork.org/t/need-help-to-fix-err-500/321 that was referenced here and reading the discussion it seems that https://community.openfoodnetwork.org/t/need-help-to-fix-err-500/321/58 (Maikel comment) solved the issue "The delayed_job.sh script is setup with wrong paths, as you mention, the ansible paths are not used in this script. I change the paths on delayed_job.sh script ans start it manually, I receive the emails I’m waiting."
So @sauloperez if you think all that is not valid anymore and all documented properly on that end please just close.

**Comment by sauloperez** [comment]
Yep, things have changed since then and that file doesn't exist anymore.
