### ISSUE TITLE
Map on USA (openfoodnetwork.net) isn't searchable

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/ofn-install#159]
Search doesn't do anything

![image](https://user-images.githubusercontent.com/2911176/43740192-e1f55352-9a0d-11e8-9684-9cd66160e832.png)

May be related to #129 and #102

**Comment by kirstenalarsen** [comment]
info for usa
![image](https://user-images.githubusercontent.com/2911176/43740128-b561def0-9a0d-11e8-8fe1-bc60632012bf.png)
but i am not sure that this is the problem

**Comment by sigmundpetersen** [comment]
So I guess this is working now @mkllnk as commented in Slack
