### ISSUE TITLE
France - change main header to match wordpress header

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/ofn-install#164]
### Description

**- As a:** regular web surfer
**- On page:** https://www.openfoodfrance.org/
**- I want to be able to do:** see the same header menu as the wordpress : http://nicolasf.synology.me/wordpress/
=> In more details, it means that we need to add the following pages :
- A propos
- Blog
- Support

All three redirecting to the wordpress site.  No need to change anything else.

Of course, this can only be done once the wordpress is live on a "real" URL.

### Acceptance Criteria
When a user reads the wordpress and from there goes to the main site, he/she has to be able to go back to pages like "a propos" whose content are on the wordpress

**Comment by RachL** [comment]
@myriamboure it seams that I can't assign nor add labels etc to this issue. I do not have enough rights on this repo. Do you ?

**Comment by myriamboure** [comment]
I think it's fixed @RachL you should have rights now, added the ofn-instal repo to the PO and train drivers team. I'm not sure if @pacodelaluna knows how to handle that but other instances (like UK) did it so I guess we can do it... ask others on dev channel on Slack if you don't know!

**Comment by myriamboure** [comment]
This can be closed now :-)
