### ISSUE TITLE
Sys admin standardization and bug fixes (Barcelona gathering)

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/ofn-install#172]
## What is the need

- all instances are reassured that if anything bad happens on their servers different developers can help so the probability to fix it quickly is much higher
- all instances know instantly when something is wrong on their server
- etc. (to complete)

## Problems we need to solve to achieve that

- ~~Delayed job issues~~
- ~~Alarm~~
- Provisioning extra vers env
- ~~Unify process for every instance.~~ Tracked in https://github.com/openfoodfoundation/ofn-install/issues/269
- Remove outage probability (SSL & deploy issues in France)
- ~~"whenever" issue~~
- ~~SSL renewal issue~~
- Default user creation (France)
- Document ansible vault
- ~~Monit~~
- Asset precompile issue (takes lots of time)

## Features candidates
We listed various solutions on each specific problem:

1. Document how to set up env vars
2. ~~Check SSL plugin (that ensures SSL renewal) if Katuma committed it to OFN install, and if not fix, if yes make sure it's documented~~
3. ~~Fix the "whenever" issue~~
4. ~~Wormly: document how to set it up~~
5. Wormly: every instance install it (blocked by 4)
6. Install agent through OFN install for server monitoring (wormly, or prometheus, or...) (blocked by 4). Replaced with https://github.com/openfoodfoundation/ofn-install/issues/273
7. ~~Get rid of monit (blocked by 6)~~
8. ~~Make sure all sys admin SSH keys are shared on all servers~~
9. Spike on asset precompile: how to improve it?
10. Spike on how to share secret files between instances? Ansible vault with multiple users storing encrypted files vs Jenkins type of server where secret files are centralized (need: also remove bottleneck and time gap for staging and testing...). Discussion in https://community.openfoodnetwork.org/t/sharing-secrets-yml-for-ofn-install/1404
11. ~~France redeploy on new production server and we organize data migration and DNS change during the night with Australia~~
12. Improve documentation to make sure we can all use ofn-install without friction

**Comment by pacodelaluna** [comment]
About the "SSL renewal issue" problem, `provisions.yml` playbook is now executing without any issue on my side, everything is ok when I am testing the cerbot conf with `sudo certbot renew --dry-run`.

About the "Default user creation (France)" problem, I am still having an error while trying to execute the `site.yml` playbooks. Here is the error:
> fatal: [www.openfoodfrance.org]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: root@www.openfoodfrance.org: Permission denied (publickey).\r\n", "unreachable": true}
Don't know why, the root user has been deleted for security reason, so I guess the related playbook should know about this, no? Please tell me what is wrong about this config.

About the "Remove outage probability (SSL & deploy issues in France)" problem, as mentioned on the previous problems:
- SSL renewal issue is ok now
- Default user creation is still giving an error.

**Comment by Matt-Yorkley** [comment]
You shouldn't execute `site.yml` against an existing OFN instance. It's only meant to be run once when the server is set up for the first time. After that we just use `deploy` and `provision`.

**Comment by sauloperez** [comment]
Could there be a way to prevent that programmatically with Ansible @Matt-Yorkley?

**Comment by Matt-Yorkley** [comment]
The first parts of `site.yml` are run as root, and root login is disabled by a later playbook, so it basically disables itself...

**Comment by sauloperez** [comment]
Would you mind creating an issue to document in the playbook what you explained here? I hope next time people understand what is meant for.

**Comment by sauloperez** [comment]
This needs to be reviewed and update it

**Comment by sauloperez** [comment]
This was completed ages ago.
