### ISSUE TITLE
Wormly: document how to set it up

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/ofn-install#173]
## Need

We need instance managers to receive alarm if anything goes wrong on the server
Australia is using Wormly and works good so the idea is first to document how to set up Wormly so that ALL instance can just do the same.

## Acceptance criteria

Wormly set up  is well documented.

**Comment by mkllnk** [comment]
Let me know if something is missing: https://github.com/openfoodfoundation/ofn-install/wiki/Server-monitoring#wormly

**Comment by Matt-Yorkley** [comment]
I think we need a discussion on this and a bit of a spike. Is there an option to share one account for all instances, given we all have this same need? Is Wormly the best option for meeting this need, or are there similar tools that we should look at?

**Comment by mkllnk** [comment]
You found some nice and free alternatives, Matt. You could pick your favourite, set it up for the UK and document it on the same wiki page. I can then set up some checks for Australian servers and give my feedback, point out what's better and what's worse compared to Wormly. If it's the best solution, we go with it.

I have only one concern with new services: if they are quite new on the market, we don't know if they have a sustainable business model. They may just be burning the investors' money and suddenly decide to stop the free offer or do other weird things.

**Comment by sauloperez** [comment]
> They may just be burning the investors' money and suddenly decide to stop the free offer or do other weird things.

Isn't that the 99.9% of the 3rd party services we use? :trollface:
