### ISSUE TITLE
Uptime monitoring and alerts

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/ofn-install#174]
## Need

We need instance managers to receive alerts for critical server issues. 

The two basic checks we identified are: an alert if a production server goes down (basic uptime monitoring) and an alert if delayed_job processes stop running (email monitoring).

In the mid term we talked about having more complex resource and process monitoring with a system like Promethues. This would require n additional server, and may be a second iteration for the future.

We have all agreed that each instance needs this basic level monitoring and alerts, but there are still a few questions: 

Should we have a single solution for all instances? Which one do we use? Etc...

## Acceptance criteria

Instance managers receive notifications for critical issues.

**Comment by Matt-Yorkley** [comment]
I looked at almost a dozen services for server monitoring based on what I saw as our basic requirements, which are actually quite simple. For now we just need to check uptime and query that one endpoint for delayed job. These 2 checks are actually very tiny in terms of server monitoring needs. 

I think in the UK we would like a quick solution we can implement immediately, preferably before we switch off monit. 

I looked at services that are easy to set up and have useful features like slack integration for alerts. Given that our requirements are actually tiny I also looked at services that offer a free option for servers that only need a couple of checks.

I ended up thinking hapyapps.io would be the best for our current need, they offer paid accounts for larger systems but the free account can have up to 3 checks and we only need 2.

So do we need a single solution for each instance? And is a richer agent-based resource monitoring system something we'll start thinking about in 6-12 months?

**Comment by Matt-Yorkley** [comment]
Maybe we can test this solution for the UK and just compare note in 3 months time. The fact that it's simple to use and free means we can ditch it at any time if our requirements change or we move to a bigger solution like Prometheus.

**Comment by elf-pavlik** [comment]
For another application I use https://uptimerobot.com/ without any fees together with Slack integration for notifications. I think documentation may just explain what different instances use and everyone can choose what fits them best.

**Comment by Matt-Yorkley** [comment]
I tested uptimerobot, but the UI was not as good as happyapps and there was much less flexibility in customising the checks, e.g checking different responses from endpoints.

**Comment by enricostano** [comment]
> Maybe we can test this solution for the UK and just compare notes in 3 months time. The fact that it's simple to use and free means we can ditch it at any time if our requirements change or we move to a bigger solution like Prometheus.

:+1: 

We're looking into Prometheus actually, we started to test it in Katuma staging but never had the time to finish up :cry: . I vote for your proposal.

**Comment by myriamboure** [comment]
@pacodelaluna if you know some other solutions or want to test one as well feel free :-) I guess you also want that!

**Comment by sauloperez** [comment]
Agree with you as well @Matt-Yorkley . Shall we also try happyapps.io on Katuma? or you prefer us to try something else? we can also use Wormly as Aus while we wait for your feedback.

**Comment by Matt-Yorkley** [comment]
This is well documented now in the Wiki and is being implemented by sysadmins for their instances.
