### ISSUE TITLE
Document how to set up env vars

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/ofn-install#175]
## Need

??

## Acceptance criteria

??

**Comment by Matt-Yorkley** [comment]
This should include updating the example `secrets.yml` file.

**Comment by Matt-Yorkley** [comment]
Closing this as the original issue was actually just a very small question during discussions that was clarified in a dev chat, and the updates to the example `secrets.yml` file are covered in PR #187.

**Comment by sauloperez** [comment]
I think is still worth briefly explaining how to add new ENV vars. Don't you think?

I took the following notes while we talked about this in the gathering:

```
## Add env vars

Make it available for unicorn by adding the env var to
roles/webserver/templates/unicorn.service.j2 so that next time it will pick it
up.

Then, you might need to make the env var available for all processes in the
server. To do that, add it in roles/unicorn_user/templates/defaults.j2.
```
