### ISSUE TITLE
Check if SSL renewal plug in is in OFN-install and document it

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/ofn-install#176]
## Need

Instance managers need to be reassured that SSL renewal will happend automatically as planned and there will be no outage.
Katuma thinks they have committed an SSL plugin to OFN install, but we need to check if they did, if not do it, and if yes make sure it's documented.

## Acceptance criteria

- SSL renewal plugin is into OFN install and works well
- it is documented in the wiki

**Comment by Matt-Yorkley** [comment]
UK has it's renewal set up ok, and certbot is definitely in ofn-install. I think we concluded the issue that was discussed was related to the domain setup of OFN France.

**Comment by elf-pavlik** [comment]
this playbook uses https://github.com/coopdevs/certbot_nginx which relies on ubuntu package which includes auto renewal job: https://certbot.eff.org/lets-encrypt/ubuntuxenial-nginx

> **Automating renewal**
The Certbot packages on your system come with a cron job that will renew your certificates automatically before they expire.

**Comment by myriamboure** [comment]
Ping @pacodelaluna :point_up: @sauloperez said he would check if he did add the thing he did for Katuma in OFN install, from what I remember, but it seems that you confirm it is. Is it documented properly as well? So if yes @pacodelaluna if it doesn't work for us maybe we can ask Matt and Pau ;-)

**Comment by sauloperez** [comment]
Yep, it's about Open Food France setup now @pacodelaluna

**Comment by Matt-Yorkley** [comment]
Closing, as I think this is covered and the issue with France will be covered in #183. Feel free to reopen if that's not the case.
