### ISSUE TITLE
Install agent through OFN install for server monitoring 

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/ofn-install#178]
## Need

Instance server managers need to know if there is any issue on the server.
?? (to complete)
we need to to expore which agent is best to use ((wormly, or prometheus, or...) and choose, and then add it to OFN-install

## Acceptance criteria

Server monitoring agent has been chosen and is installed through OFN-install process.

**Comment by Matt-Yorkley** [comment]
Closing as I think implementing an agent-based server monitoring system is something we'll review again in 6 months, so isn't really part of this epic or current workload.
