### ISSUE TITLE
Get rid of monit

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/ofn-install#179]
## Need

Now that server monitoring agent has been installed and is monitored by Wormly, we can get rid of monit

## Acceptance criteria

Monit has been removed and moniroting service still work as expected

**Comment by Matt-Yorkley** [comment]
Note: before closing this issue, make sure to update the ofn-install Wiki.

https://github.com/openfoodfoundation/ofn-install/wiki/Server-monitoring
https://github.com/openfoodfoundation/openfoodnetwork/wiki/Delayed-job

**Comment by Matt-Yorkley** [comment]
Closed by #192
