### ISSUE TITLE
Make sure all sys admin SSH keys are shared on all servers

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/ofn-install#180]
## Need

Instance manager want to be reassure that if issue and their sys admin is not available someone else from global pool can intervene.
For that we need all sys admin SSH on all instances production servers.

## Acceptance criteria

All global sys admin (Rob, Maikel, Matt, François, Pau, Enrico) have access to all OFN instance servers.

**Comment by elf-pavlik** [comment]
Currently any group can add any admin in their `group_vars`, it seems sufficient to me. What exactly you would like to change about it? Maybe `_examlple.yml` could include people you mention and anyone creating a new group could decide to leave them in or out of the list of sysadmins.

**Comment by Matt-Yorkley** [comment]
If plan on adding lots of people to have permissions on every server, is there a way we can get ansible to only run if the --limit flag is present? Otherwise if anyone ever forgets to add the --limit it will overwrite all servers... D:

**Comment by elf-pavlik** [comment]
possible approach here: https://stackoverflow.com/a/18195217
