### ISSUE TITLE
Spike on asset precompile: how to improve it

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/ofn-install#181]
## Need

For some instances it takes a long time to precompile asset, which reduce velocity and efficiency.
Let's do a spike to understand how we could improve that.

## Acceptance criteria

We know what options we have and can choose from.

**Comment by Matt-Yorkley** [comment]
Just as a note, this issue in the main repo might have some relevance here: #2100.

**Comment by mkllnk** [comment]
I think that this has been worked on and will change with the asset pipeline changing again.
