### ISSUE TITLE
Spike on how to share secret files between instances

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/ofn-install#182]
## Need

To be able to have other sys admin doing deployment on all instance servers, instance servers managers need to be able to share secret.yml files.
There are various options, and we especially identified two:
- put encrypted secret files in a shared Ansible vault with multiple users being able to access it
- witch to Jenkins type depoyment server that would centralize all secret files and also make it easier for testers to stage and test, improving also testing velocity and alleviating a delivery pipe bottleneck (so that we would solve both issues at once)

## Acceptance criteria

We understand clearly pros and cons, difficulties of implementation for both options,  impacts, and have all the elements to choose which option we want to implement

**Comment by Matt-Yorkley** [comment]
We did some investigation and thinking on this, and have a new solution that will solve a lot of the issues raised in the discussions. We can give an update soon with the details.

**Comment by sauloperez** [comment]
The discussion moved to https://community.openfoodnetwork.org/t/sharing-secrets-yml-for-ofn-install/1404

**Comment by sauloperez** [comment]
We came up with a plan in https://community.openfoodnetwork.org/t/sharing-secrets-yml-for-ofn-install/1404/10?u=sauloperez so closing this.
