### ISSUE TITLE
Improve transifex documentation

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/ofn-install#185]
## Need

Instance managers don't understand clearly what is done for transifex, especially on code base, they can't see the code, doesn't seem to be shared (or don't know where).
So there are stil internationalisation issues linked to transifex.
Two things to do to fix that are:
- explain in detail how it works
- publish the code

## Acceptance criteria

Instance servers managers clearly understand what Transifex does and the process

**Comment by mkllnk** [comment]
I documented the Transifex process before: https://github.com/openfoodfoundation/openfoodnetwork/wiki/i18n

Now I added a bit more information about requesting new languages and becoming a language maintainer. Transifex itself is a third-party service and not open source. But their Github integration called txgh is open source. I updated the link the document to our customisation that we are using: https://github.com/openfoodfoundation/txgh/blob/ofn/README.ofn.md

Is there still something missing in that document? Did everybody find that document or is it confusing that it is called "i18n"?

**Comment by sauloperez** [comment]
I updated the wiki page's title to `Internationalisation (i18n)` for consistency

**Comment by mkllnk** [comment]
@sauloperez You just broke all links to the page! The title is also the name of the file and part of the URL. I created a new page under the old URL to point to the new one. That should help.

**Comment by sauloperez** [comment]
Oops, sorry. We can close this one then.
