### ISSUE TITLE
Look at use of application.yml

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/ofn-install#189]
As part of the goal of getting everyone to start using ofn-install, we should look at our use of `application.yml`. We have a mixture of approaches across ofn-install and the main repo for adding things to `application.yml` and it needs to be standardised and tidied up.

We also need to assess the requirements of instances currently not using ofn-install and see if there are things we need to add to get them using it.

**Comment by sauloperez** [comment]
@Matt-Yorkley if I understand correctly, this is more about the investigation to merge the app's `application.yml` and the one that gets deployed with `ofn-install`. Am I right?

**Comment by Matt-Yorkley** [comment]
Yes, it's about the fact that we have entries in both the main repo and in ofn-install for `application.yml`. I guess the simple solution is to move everything to ofn-install and just leave a comment in the main repo's `application.yml`? But I suppose this would be blocked by the "full ofn-install adoption" epic.

**Comment by sauloperez** [comment]
This is done.
