### ISSUE TITLE
Provisioning error from Certbot

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/ofn-install#190]
Ooops. Certbot asks for some user interaction here, which breaks the provisioning process. 

```
You have an existing certificate that has exactly the same domains or certificate name you requested and isn't close to expiry. 
What would you like to do?
1: Keep the existing certificate for now
2: Renew & replace the cert (limit ~5 per 7 days)
```

![screenshot from 2018-07-10 19-19-17](https://user-images.githubusercontent.com/9029026/42529416-54226210-8476-11e8-821c-00052b3a94ab.png)

**Comment by Matt-Yorkley** [comment]
Hmmm... I've just been investigating this more and now the same task is passing on UK staging without the original error. 

![shrug](https://media.giphy.com/media/K6VhXtbgCXqQU/giphy-downsized.gif)

I guess I'll close this issue for now, but it makes me a bit uneasy that I saw this error twice this morning and provisioning was blocked. 

We could consider using the `--non-interactive` flag when running certbot commands.

**Comment by sauloperez** [comment]
we can add that flag as soon as it happens again.
