### ISSUE TITLE
Refactor organisation of ENV vars

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/ofn-install#191]
At some point we should assess and refactor the way we initialize variables that are optional or not needed by all instances, and how we use them n conditionals.

There are some old uses in the format `custom_variable: none`, which then check the variable contains the string `none`. Alternatively if we define the variable but don't pass it anything it will be an empty string. Another option is removing variables completely from defaults.yml files and checking if they are undefined.

At some point we should look at these cases and maybe do some refactoring.

**Comment by sauloperez** [comment]
I guess listing all variables in yml is something worth doing, so in that caseI'd leave them empty.
