### ISSUE TITLE
Remove messy bash scripts

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/ofn-install#225]
What's the purpose of this file? https://github.com/openfoodfoundation/ofn-install/blob/master/roles/app/templates/post-receive.j2

It's been hiding out in a template file for a long while and it's quite outdated. We copy it into `/.git/hooks/post-receive/` but I don't think it's actually being triggered by our deployment process.

:fire: :fire: :fire:

**Comment by sauloperez** [comment]
isn't that what Aus uses to deploy?

**Comment by Matt-Yorkley** [comment]
Ah, that's what that is! I thought they had a separate process...

**Comment by Matt-Yorkley** [comment]
Well I'll leave this issue open for when we reach the glorious utopia of sysadmin standardisation.

:trollface:
