### ISSUE TITLE
Refactor postgresql tasks

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/ofn-install#227]
We have lots of hacky postgresql tasks, including one that runs an old bash script from 4 years ago to "fix pg encoding": https://github.com/openfoodfoundation/ofn-install/blob/98d35374ab99620ef95cc9cec15e470a65156219/roles/dbserver/files/fix_pg_encoding.sh

There are **6** ansible postgresql modules for doing just about anything with postgresql, and we currently don't use any of them. They are listed here: https://docs.ansible.com/ansible/latest/modules/list_of_database_modules.html#postgresql

#techdebt

**Comment by sauloperez** [comment]
I have no experience with it but, at Coopdevs we use https://github.com/geerlingguy/ansible-role-postgresql in all our projects.

**Comment by Matt-Yorkley** [comment]
Closed by #400
