### ISSUE TITLE
Enable DB integrations such as Zapier

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/ofn-install#230]
In the UK we've started using Zapier, which is a service that integrates with the database and allows for a wide range of extra functionality, like creating custom reports for enterprises, exporting order data to accounting software, or sending email alerts when something gets added.

It involves creating a postgresql user with restricted permissions, and enabling the service to connect directly to the DB (read-only).

It looks like this could be useful for multiple instances, and since it involves server configuration we should probably add an optional role for it to ofn-install and decide on the best way to do it. There are some security issues to discuss as well.

**Comment by Matt-Yorkley** [comment]
The manual process looks like this. I'll look at making a role for it.

```
MAKE A SECURE PASSWORD:
----------------------

openssl rand -hex 128


CREATE THE USER:
----------------

sudo -u postgres psql openfoodnetwork

CREATE ROLE zapier WITH LOGIN PASSWORD 'secure_password' 
NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;

GRANT USAGE ON SCHEMA public TO zapier;

GRANT CONNECT ON DATABASE openfoodnetwork TO zapier;

GRANT SELECT ON ALL TABLES IN SCHEMA public TO zapier;

GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO zapier;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO zapier;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON SEQUENCES TO zapier;



ALLOW ACCESS:
-------------

sudo su postgres

echo "hostssl openfoodnetwork zapier 54.86.9.50/24 md5" >> /etc/postgresql/9.5/main/pg_hba.conf

echo "listen_addresses = '*'" >> /etc/postgresql/9.5/main/postgresql.conf

sudo systemctl reload postgresql

```

**Comment by pacodelaluna** [comment]
Thanks for this clear doc! Helped a lot! A small thing on my side, ´reload´ didn't work out, I had to restart the PosgreSQL server with ´sudo systemctl restart postgresql´.

**Comment by Matt-Yorkley** [comment]
Once we have #400 merged, we should be able to make a playbook for this quite easily to make sure it's standardised (even though it's optional). I think currently UK and France use Zapier, and the setups on both required manually editing config files. I had a quick look though, and it's really easy to sort out once we have the new postgresql role managing things.
