### ISSUE TITLE
SSL expiry on USA?

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/ofn-install#231]
![image](https://user-images.githubusercontent.com/2911176/43871691-2b33d354-9bc1-11e8-95ef-f7547db60b26.png)

**Comment by mkllnk** [comment]
I can confirm that the certificate has expired. Working on it.

**Comment by mkllnk** [comment]
The certbot config was set to standalone instead of nginx. Since the webserver is running already, this failed. I think it was an old ofn-install problem. I just fixed it in that file. All works now.
