### ISSUE TITLE
Configure Stripe for OFN USA

### ISSUE THREAD

**Issue by lauriewayne** [openfoodfoundation/ofn-install#233]
USA needs to have Stripe configured so that credit cards can be used for transactions. @lauriewayne can help with most steps besides 5 and 6 here:
https://github.com/openfoodfoundation/openfoodnetwork/wiki/Setting-up-Stripe-on-an-OFN-instance

(blush, also how do I apply the USA label to this issue?)

**Comment by mkllnk** [comment]
Solved with Brandy.
