### ISSUE TITLE
Emails point to the wrong domain

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/ofn-install#243]
The site URL is not set by ofn-install. So a newly provisioned instance sends emails with broken links. The workaround is to go to `/admin/general_settings/edit` and enter the right site URL.

**Comment by Matt-Yorkley** [comment]
So this is just an extra config option that needs to be provisionable? Seems like an easy one. :+1: #goodfirstissuesinofninstall

**Comment by Matt-Yorkley** [comment]
I'm 99% sure we fixed this in the big mail configs tidyup.
