### ISSUE TITLE
Fix google maps in German instance

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/ofn-install#250]

**Comment by mkllnk** [comment]
Since I don't have access to the German Google account, I created a new API key with our account. I updated the secrets file in the repository and deployed. Maps seems to work now.

**Comment by sauloperez** [comment]
You mean in https://github.com/coopdevs/ofn-de-secrets ?

**Comment by mkllnk** [comment]
Yes, https://github.com/coopdevs/ofn-de-secrets/commit/7df4a0011f290122958d59e2b647f525e530098f. You can't really review it on Github, it's encrypted. :-)
