### ISSUE TITLE
Apply quick fix to allow OC to be created on German instance

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/ofn-install#254]
see https://github.com/openfoodfoundation/openfoodnetwork/issues/2676

This issue is now happening on german instance. ARGHHHH

Need fixed asap

But @mkllnk is away and no one else except @enricostano has access to german instance :(

**Comment by mkllnk** [comment]
I can confirm that I can't create an OC at https://openfoodnetwork.de/admin/order_cycles/new.

**Comment by mkllnk** [comment]
The problem with the US version was a broken delayed job. The German instance has one. I deleted it and now OC creation works.

```
Delayed::Job.count
=> 1

Delayed::Job.first
#<Delayed::Backend::ActiveRecord::Job id: 1, priority: 0, attempts: 0, handler: "--- !ruby/object:Delayed::PerformableMethod\nobject:...", last_error: "Job failed to load: undefined class/module HighLine...", run_at: "2018-03-08 14:46:13", locked_at: nil, failed_at: "2018-03-08 14:56:37", locked_by: nil, queue: nil, created_at: "2018-03-08 14:46:13", updated_at: "2018-03-08 14:56:37">

Delayed::Job.first.destroy
```

**Comment by mkllnk** [comment]
The OFN version should be updated as we have a permanent fix for this now. Keeping the issue open for that.

**Comment by kirstenalarsen** [comment]
We have an issue open to upgrade the instance (#249) so can close this. Thanks @mkllnk
