### ISSUE TITLE
Extract `core_dev_team` var an use it as value for `users_sysadmin`

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/ofn-install#263]
## Description

As suggested in https://github.com/openfoodfoundation/ofn-install/pull/261#discussion_r225496935, adding a `core_dev_team` var would DRY things quite a lot and would make enabling new instances easier as well as no more `X dev has no access to this instace, he can't hekp fix whatever problem now :(`.

More importantly, this better conveys the strategy of having a single dev team sharing the sysadmin responsibility across all OFN instances 💪 .

**Comment by Matt-Yorkley** [comment]
Closed by #425
