### ISSUE TITLE
Full ofn-install adoption

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/ofn-install#269]
This is an old one. This is a big part of the ongoing effort to standardize the way we deploy and provision servers to avoid wasting efforts on tools that do the same, but more importantly, that makes it possible for all sysadmins to go fix in issues any instance my experience.

Now, only the sysadmins that set up Australia's production, Canada's staging and production, German production and ~~France's staging~~ can manage them. The task is, therefore to make these adopt `ofn-install`.

**Comment by mkllnk** [comment]
The only non-ofn-install instance is now the inactive Scandinavian instance. I'm closing this.
