### ISSUE TITLE
Investigate a quick solution for system monitoring

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/ofn-install#273]
We can't delay this any further. We need a way to know how OFN's instances are behaving in terms of Memory, CPU Load, Network and disk usage. Without these, we can't troubleshoot any performance problems or perform any [operations](https://stackify.com/web-operations/) task. This should allow us to start dealing with the latter which will eventually enable us to work on the former.

There are two options here: a hosted or a saas solution. While the first one gives us full control it also brings an extra maintenance and configuration overhead alhtough the software might be free.

On the other hand, a Saas solution will have a monthly cost and might not give us full control but it will have very little maintenance overhead compared to a hosted solution.

**Comment by sauloperez** [comment]
I did a bit of investigation and the options seem to be

## Hosted
[Prometheus](https://prometheus.io/) with https://github.com/prometheus/node_exporter 

## Saas
[Datadog](https://www.datadoghq.com/) or [New Relic Infrastructure](https://newrelic.com/products/infrastructure) seem to be the biggest ones in this space.

**Comment by Matt-Yorkley** [comment]
I would vote for a simple saas solution for all instances. Maybe Datadog.

**Comment by sauloperez** [comment]
I'd go straight with datadog. There's a free option we could start using. Check it out in https://www.datadoghq.com/pricing/

**Comment by deanmarc25** [comment]
I can confirm the datadog installation script will install all of the dependencies for you; assuming we are linux based. The latest datadog agent is golang based, I think (version 6). I believe this is the script here: https://github.com/DataDog/dd-agent/blob/master/packaging/datadog-agent/source/install_agent.sh. You simply pass it your datadog api key and it does the rest in most cases.

I'd be happy to answer any questions on datadog. I used newrelic very briefly in the past but it became expensive and we discontinued it in favor of datadog and more recently, prometheus. It does have more integrations that when setup properly, you can really hone in on specific areas of the application cause problems.

I'm wondering if our infrastructure provider gives us the info we are looking for?

**Comment by mkllnk** [comment]
We are using Wormly: https://www.wormly.com/help/metrics-collectd/metrics-overview

The good thing about them is that they use collectd, free software for monitoring and you can monitor anything using their API. If you have an account with them already, you get the basic metrics for free. A basic plan is $25. That is for monitoring (like Happy Apps) and metrics. It's pricey, but an excellent tool.


They are a nice small business in Melbourne.

**Comment by sauloperez** [comment]
> I'm wondering if our infrastructure provider gives us the info we are looking for?

Now every instance has its own provider and we can't rely on them. For instance, our provider who has very low pricing doesn't show any metrics.

@mkllnk do you already have system metrics with your wormly account for free? it'd be nice if we could stick to fewer 3rd party services but for 15$ host per month, I think datadog is clear winner.

**Comment by Matt-Yorkley** [comment]
Do we need more than 1-day data retention with our current requirements? If it's free and an easy setup for Datadog, I'd say lets just start trialling it with a couple of our servers.

**Comment by sauloperez** [comment]
Yes, that's what I have in mind. Although we might need more data retention soon, this could already save our asses :trollface: .

**Comment by Matt-Yorkley** [comment]
Lets do it!

**Comment by mkllnk** [comment]
We get 200 metric per minute for free. So it depends how many things you monitor and at which interval. One host with all the default metrics at 1 minute interval generates 145 metrics per minute. It looks like this:
![screenshot from 2018-11-23 08-28-35](https://user-images.githubusercontent.com/3524483/48922529-6eec9300-eefb-11e8-92b2-94afbacb1d03.png)
As far as I know, the retention is indefinite. I used it in the past, but forgot to set it up for our new server till yesterday. So the picture above is only one day, but in a month I will see a lot more in that graph.

Different topic, but same interface for us: This is the server response time of fetching the homepage over the last year:
![screenshot from 2018-11-23 08-46-48](https://user-images.githubusercontent.com/3524483/48922647-5a5cca80-eefc-11e8-995f-ade8879023a7.png)
Unfortunately, I don't know which pull requests or software updates caused the big differences.

**Comment by sauloperez** [comment]
What is it that you propose then @mkllnk ?

If that is to use Wormly for our monitoring we still need to answer the following questions

> If you have an account with them already, you get the basic metrics for free.

Does this mean instances not using Wormly yet will have to pay the 25$ per month?

> As far as I know, the retention is indefinite.

I'd be good to know what is it exactly, but that's clearly an advantage over Datadog's freemium.

> We get 200 metric per minute for free. So it depends how many things you monitor and at which interval. One host with all the default metrics at 1 minute interval generates 145 metrics per minute.

that doesn't give us too much room. What would be the price if exceed that? the 25$ per month per host?

Also, take into account that with Datadog we have a single account for all OFN with each host sending data there, which enables us to have aggregated metrics, for instance. IMO this is a move in the right direction of sharing even more costs and removing frictions.

Let's try to reach a consensus in the next few days. I feel like we have way too many open fronts that never get closed.

**Comment by sauloperez** [comment]
> Does this mean instances not using Wormly yet will have to pay the 25$ per month?

I guess so. I can't see any mention to freemium. Just the startup plan, the 25$ per month for an unknown trial period.

**Comment by mkllnk** [comment]
> What is it that you propose then @mkllnk ?

I propose to support both Wormly and Datadog as long as you are happy with Datadog and I'm happy with Wormly. :-)

> Does this mean instances not using Wormly yet will have to pay the 25$ per month?

It depends. If every instance had their own account, they would pay $25 per month. We can all share one account though. If we reduce the amount of metrics per minute per host (fewer metrics, longer intervals) we can cover more hosts with the 200 metrics per minute included in $25. If we used all standard metrics (175 per minute) we would need to pay $10.50 for each additional host. But just sending the metrics only every two minutes would half these costs. I'm experimenting with the amount of metrics at the moment.

The data retention is indefinite. And we can use the alerting system there as well.

But if we pay for an additional account, Datadog seems to be cheaper. We get 15 months data retention for $15. I don't think we need more retention. Does that cover unlimited hosts? How many resources does their agent need? Is their tool open source?

Collectd seems to use 80 MB of memory on our production server at the moment.

I understand that it is more efficient if we all use exactly the same tools and everything is standardised. But I also think that we need space for testing several solutions and should consider the context of each instance.

The Datadog freemium account is of no use for us. I think it's a good idea if you start using Datadog and gain some experience with it over a couple of months. If you like it and we collectively get on the $15 plan for data retention, I'm happy to switch our server to Datadog as well. Hm, not entirely happy, I don't like running closed source software, but it seems to be the best solution.

**Comment by mkllnk** [comment]
Ah, the Wormly free trial period is over one month and after that the support offers to extend it another month.

**Comment by sauloperez** [comment]
> Does that cover unlimited hosts? How many resources does their agent need? Is their tool open source?

That's what it looks like. I don't know yet, but I don't expect much. The agent, at least, uses an Apache license https://github.com/DataDog/datadog-agent/blob/master/LICENSE

**Comment by sauloperez** [comment]
don't take Katuma's prod too seriously... we have way better staging than production server :see_no_evil:
