### ISSUE TITLE
Move config/initializers/db2fog.rb to the app

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/ofn-install#280]
## Description

Something as simple as having a `config/initializer/` to configure `db2fog` is overly complex and confusing, which seriously affects our confidence when changing these settings (at least mine). Also, what should be straightforward takes too much time.

## How it works now

Currently our servers end up with a symlink pointing to the config stored in `shared/` as you can see below:

```
$ ll config/initializers/db2fog.rb 
lrwxrwxrwx 1 openfoodnetwork openfoodnetwork 66 nov 16 09:56 config/initializers/db2fog.rb -> /home/openfoodnetwork/apps/openfoodnetwork/shared/config/db2fog.rb*
```

This is done in 2 steps.

### Copy file to shared folder

First, the file is copied to the shared folder

https://github.com/openfoodfoundation/ofn-install/blob/48476c4f012325350f55211820c83b8a362e0f28/roles/app/tasks/main.yml#L51-L60

### Symlink the db2fog file into app config

Then, the config needs to be made available to the app by means of a symlink.

https://github.com/openfoodfoundation/ofn-install/blob/48476c4f012325350f55211820c83b8a362e0f28/roles/deploy/tasks/main.yml#L70-L79

All this was done this way to be able to get `{{ s3_backups_bucket }}`'s value (note it's an ansible var) and print it into the Db2fog config object.

https://github.com/openfoodfoundation/ofn-install/blob/48476c4f012325350f55211820c83b8a362e0f28/roles/app/templates/db2fog.rb.j2#L2-L7

## Expected behavior

We should only have a `config/initializers/db2fog.rb` file in the app that gets the `{{ s3_backups_bucket }}`'s value from an ENV var.

To do that, we need to decide which way we populate said ENV var. Either from [roles/unicorn_user/templates/defaults.j2](https://github.com/openfoodfoundation/ofn-install/blob/master/roles/unicorn_user/templates/defaults.j2) or [roles/app/templates/application.yml.j2](https://github.com/openfoodfoundation/ofn-install/blob/master/roles/app/templates/application.yml.j2)

We also need to check what happens then with [/config/initializers/0_depricated_db2fog.rb](https://github.com/openfoodfoundation/openfoodnetwork/blob/master/config/initializers/0_depricated_db2fog.rb). Can we remove it? Because as far as I understand, it will clash with the new file.

**Comment by Matt-Yorkley** [comment]
Proposal:
- delete the two tasks and the template from `ofn-install`
- we already provision the necessary variables here: https://github.com/openfoodfoundation/ofn-install/blob/master/roles/app/templates/application.yml.j2, so that doesn't need changing
- rename `/config/initializers/0_depricated_db2fog.rb` to `/config/initializers/db2fog.rb` in the main repo, and change it to this:
```
DB2Fog.config = { 
   :aws_access_key_id     => Spree::Config[:s3_access_key], 
   :aws_secret_access_key => Spree::Config[:s3_secret], 
   :directory             => Spree::Config[:s3_backups_bucket], 
   :provider              => 'AWS' 
} 
```
