### ISSUE TITLE
Set up PayPal in staging other than AUS

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/ofn-install#282]
## Description

We need staging environments other than AUS to have PayPal set up. This will avoid us having to depend on AUS when testing the release or when PRs require using PayPal.

AFAIK this involves creating a sandbox account and enabling the integration from OFN.

**Comment by sauloperez** [comment]
According to @Matt-Yorkley UK doesn't

**Comment by sauloperez** [comment]
@RachL do we test PayPal in releases? how urgent would this be?

**Comment by RachL** [comment]
@sauloperez I've created a dev account for myself, so I think I can replicate Paypal in different staging. The only thing that I didn't quite succeed at yet, is to pay with my dev account. But Maikel has sent me a process that I need to retry. I've documented how to set up a test account here: https://docs.google.com/document/d/15EdXKb4B3BS8gekD6_9PDdPTZsjUCAVS2011zRf55lM/edit#

**Comment by sauloperez** [comment]
Cool! Let's keep this issue up to date. I hope we can close it soon!

**Comment by RachL** [comment]
@sauloperez with the recent release I have been able to pay through my Paypal test account, so i think we are good to close this :) Feel free to re-open if I'm missing something.
