### ISSUE TITLE
Set up Stripe in staging other than AU

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/ofn-install#283]
## Description

We need staging environments other than AUS to have Stripe set up. This will avoid us having to depend on AUS when testing the release or when PRs require using Stripe.

AFAIK this involves creating a sandbox account and enabling the integration from OFN.

https://github.com/openfoodfoundation/openfoodnetwork/wiki/Setting-up-Stripe-on-an-OFN-instance is the relevant documentation.

## Instances to setup

- [x] Katuma staging
- [ ] UK staging
- [x] French staging

**Comment by sauloperez** [comment]
According to @Matt-Yorkley UK doesn't

**Comment by sauloperez** [comment]
I did set it up in Katuma staging. Is it enough for now @RachL ? we should eventually have all stagings using a Stripe test account though.

**Comment by RachL** [comment]
@sauloperez if we continue to test release, I think it should be good to set up Stripe in the Uk too :)

**Comment by sauloperez** [comment]
We had the need to have Stripe in UK again in https://openfoodnetwork.slack.com/archives/C0DNLAZC7/p1549637031098200?thread_ts=1549566274.092800&cid=C0DNLAZC7

**Comment by RachL** [comment]
Yes I wanted to ask you : how did you set up the katuma account? When I'm trying to subscribe to stripe, it asks me for my IBAN and so on to activate my account. I can't switch to a testing mode (like you showed me) until my account is activated. And fake data are not working :trollface: Did you put real data for Katuma or is there another way I'm missing?
Otherwise I will have to create an account with OFN France info and UK with OFN UK info. @sauloperez

**Comment by sauloperez** [comment]
I just followed the wiki page and used katuma's real data to set up the account. The test mode was just there in the Stripe dashboard.

I wanted to give this Katuma Stripe account a try and link it to UK's staging as well, is that what you tried?

**Comment by sauloperez** [comment]
We need to check if it is set up in FR @pacodelaluna

**Comment by sauloperez** [comment]
We just set it up in FR (Check https://github.com/openfoodfoundation/openfoodnetwork/issues/3553) so to set it up in UK should be pretty straight forward.

**Comment by sigmundpetersen** [comment]
Hey @filipefurtad0 do you know the status of Stripe on staging servers?
Is this now setup for uk-staging? Then I think we can close this issue.
If not, this is still relevant.

**Comment by sigmundpetersen** [comment]
Also related -> #433

**Comment by filipefurtad0** [comment]
Hey @sigmundpetersen ,

Stripe is fully setup in staging-UK, we can use it for testing :+1: 
Closing.
