### ISSUE TITLE
Integrate Australia's staging scripts into ofn-install

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/ofn-install#284]
I wrote a few new scripts to integrate git push deployments with ofn-install. They need to be provisioned by ofn-install as well so that everybody can easily deploy via git push or Semaphore. Some of these scripts are:

* `~/apps/openfoodnetwork/current/.git/hooks/post-receive`
```sh
#!/bin/sh

set -e

# GIT_DIR is usually set to `.` and we need to change into the work tree.
cd "$GIT_DIR/.." || exit 1
unset GIT_DIR

# The just uploaded commit to deploy:
NEWREF="$(cat /dev/stdin | cut -d ' ' -f 2)"

DEPLOY_SCRIPT="$HOME/bin/ofn-deploy"

if [ -f "$DEPLOY_SCRIPT" ]; then
	echo "Deploying $NEWREF"
	"$DEPLOY_SCRIPT" "$NEWREF"
fi
```

* `~/bin/ofn-deploy`
```sh
#!/bin/sh

set -e

APP_PATH="$(dirname `pwd`)"
SHARED_PATH="$APP_PATH/shared"
CONFIG_PATH="$APP_PATH/shared/config"
PID_PATH="$APP_PATH/shared/pids"
GEM_PATH="/home/openfoodnetwork/.gem"
APP="openfoodnetwork"
RAILS_ENV="staging"

NEWREF="$1"

# We need ruby to call script/delayed_job
export PATH="$HOME/.rbenv/shims:$PATH"

# Free up memory by stopping unicorn and DJ early
echo "Stopping unicorn..."
sudo /bin/systemctl stop unicorn_openfoodnetwork.service
echo "Stopping delayed_job..."
RAILS_ENV=$RAILS_ENV bundle exec ./script/delayed_job stop --pid-dir="$PID_PATH"

"$HOME/bin/ofn-save-and-reset-staging-database"

sudo -i -u ofn-admin /home/ofn-admin/deploy
cp ~/new-post-receive-hook .git/hooks/post-receive

echo "
        Successfully deployed $NEWREF.
"
```

* `~/bin/ofn-save-and-reset-staging-database`:
```sh
#!/bin/sh

set -e

DB_HOST=localhost
DB_USER=ofn_user
DB=openfoodnetwork
BACKUP_PATH="../backups"

master_merged() {
  git fetch https://github.com/openfoodfoundation/openfoodnetwork -p
  git merge-base --is-ancestor HEAD FETCH_HEAD
}

save_staging_baseline() {
  echo "Saving baseline data"
  pg_dump -h "$DB_HOST" -U "$DB_USER" "$DB" | gzip > "$BACKUP_PATH/staging-baseline.sql.gz"
}

backup_and_restore_baseline() {
  echo "Backup database"
  pg_dump -h localhost -U ofn_user openfoodnetwork | gzip > "$BACKUP_PATH/staging-`date +%Y%m%d%H%M%S`.sql.gz"
  echo "Load baseline data"
  dropdb -h localhost -U ofn_user "$DB"
  createdb -h localhost -U ofn_user "$DB"
  zcat "$BACKUP_PATH/staging-baseline.sql.gz" | psql -h localhost -U ofn_user openfoodnetwork
}

mkdir -p "$BACKUP_PATH"


if master_merged; then
  save_staging_baseline
else
  backup_and_restore_baseline
fi
```

* `/home/ofn-admin/deploy`:
```sh
#!/bin/sh

cd ofn-install
ansible-playbook playbooks/deploy.yml -l staging.openfoodnetwork.org.au --connection=local --extra-vars "git_repo=file:///home/openfoodnetwork/apps/openfoodnetwork/current"
```

* `/etc/sudoers.d/openfoodnetwork-deploy`:
```
/etc/sudoers.d/openfoodnetwork-deploy
```

**Comment by Matt-Yorkley** [comment]
@mkllnk staging data doesn't get reset on deployment with ofn-install. I don't understand the need for the DB restore part.

**Comment by Matt-Yorkley** [comment]
Stopping delayed_job briefly during deploy is a great idea, we can add that to ofn-install quite easily. I'm not sure about stopping unicorn during deploy though. Unless that's just for staging?

**Comment by sauloperez** [comment]
I think that is for staging only, yes. We do already restart DJ though @Matt-Yorkley

**Comment by Matt-Yorkley** [comment]
Yes, but we could stop it just before the precompile for instance, then start it again. Might help with your resource issues, no?

**Comment by mkllnk** [comment]
@sauloperez 
> you suggest we copy post-receive and ofn-deploy to the remote server at provision time and then we trigger the regular ansible deploy through openfoodnetwork-deploy?

That's the best I've come up with so far. I'm not happy with the complexity of calling a chain of for scripts to actually do something. In the past we did the whole deploy in the `post-receive` script without ofn-install. That was much simpler. We could do everything with user permissions as well.

One question that is independent, but affects the development of this: How often do we run the provisioning? Ideally for every deploy, but that's very slow and often not needed. If we call it only from time to time manually, we can ignore it for deploys. In that case we can move more deploy steps into a deploy script on the server that is provisioned by ofn-install. That would simplify this setup.

@Matt-Yorkley 
> staging data doesn't get reset on deployment with ofn-install. I don't understand the need for the DB restore part.

When you deploy one pull request with database migrations and it is not accepted, you need to restore the previous state of the database before you can deploy another pull request. You can also solve this by completely deleting and resetting the database, but that also wipes data useful for testing like payment gateway setups and additional user accounts. How are you dealing with that at the moment?

The `ofn-deploy` script with stopping unicorn and resetting the database is staging specific. It would look very different for production.

**Comment by sauloperez** [comment]
> I'm not happy with the complexity of calling a chain of for scripts to actually do something

is it possible that we're not talking about the same? to deploy we execute a long but single command.

> We could do everything with user permissions as well.

Also for me to understand, what do you mean but that?

> How often do we run the provisioning?

When there are changes in `ofn-install`. I don't see a reason to do it more often but sysadmin is not my area of expertise. Apart from that, I do never change servers manually. AFAIK this must be avoided at all costs.

> When you deploy one pull request with database migrations and it is not accepted

what do you mean but `not accepted`?

**Comment by sauloperez** [comment]
In any case, is there anyone against having these scripts merged? As far as it's for staging there's not much we change here.

**Comment by sauloperez** [comment]
> But I'm also thinking of another script that can be used on production servers to trigger ofn-install deploy on Git push. It's so convenient and would be easy to integrate with Semaphore if we wanted to.

Let's not forget we have priorities agreed with the team in all backlogs: tech debt, sys admin plus the regular dev stuff. I would focus on those and discuss about this topic once we're done with them.

**Comment by sauloperez** [comment]
@Matt-Yorkley we've used part of this script for the new semaphore deployments, didn't we? I'd be good to know how much did we share and what we need to do with this particular script.

**Comment by Matt-Yorkley** [comment]
@sauloperez No, I made a new role for Semaphore deployment. It doesn't use any of these scripts or hooks.

**Comment by Matt-Yorkley** [comment]
This hook was removed in #406, right? 

See #299 for alternate semaphore staging setup
