### ISSUE TITLE
Provision Datadog agent

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/ofn-install#292]
## Description

The Datadog agent set up in https://github.com/openfoodfoundation/ofn-install/pull/288 needs to be provisioned in the following instances:

- [x] Katuma
- [x] UK
- [x] France
- [x] USA

**Comment by daniellemoorhead** [comment]
Hey @sauloperez how do we get the final 2 instances up and running with this? Does Brandy need to get involved from the US side, and maybe @Matt-Yorkley for Belgium?

#toomanythingsinthepipe

**Comment by sauloperez** [comment]
Dealing myself with Belgiuem and working with Brandy on US. The real challenge is to match our timezones and working hours 🙈

**Comment by sauloperez** [comment]
Brandy already did it!

As for Belgium. Talking to @Matt-Yorkley we thought it's better to do it next year so we don't run out of available hosts while he's testing bulk invoice.

**Comment by sauloperez** [comment]
I created https://github.com/openfoodfoundation/ofn-install/issues/298 for Belgium so we can close this :tada:
