### ISSUE TITLE
System monitoring

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/ofn-install#293]
We can't delay this any further. We need a way to know how OFN's instances are behaving in terms of Memory, CPU Load, Network and disk usage. Without these, we can't troubleshoot any performance problems or perform any [operations](https://stackify.com/web-operations/) task. This should allow us to start dealing with the latter which will eventually enable us to work on the former.

**Comment by sigmundpetersen** [comment]
We are trying to reduce to number of epics before transitioning to Github Projects.

We can close this and keep the one remaining issue.
