### ISSUE TITLE
Provision and deploy Norway's production with ofn-install

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/ofn-install#295]
We need to reprovision and then deploy Norway's production server with `ofn-install`. This will require adding its configuration settings to this repo and prevent people from using it while we provision and deploy.  

We need to provision a new production server for Norway so that we provision and deploy to it with `ofn-install`. This will require:

- [ ] Add configuration settings to this repo
- [ ] Provision the new machine
- [ ] Deploy to new machine
- [ ] Stop old server (at night when no one uses it)
- [ ] Import database dump to the new server
- [ ] Change DNS record to point to the new server
- [ ] Ditch the old server

**Comment by sauloperez** [comment]
@sigmundpetersen is there any chance you could do it? We're struggling to find the right priority for this issue although we know this server has the oldest Ubuntu version.

**Comment by sigmundpetersen** [comment]
Okay I join in this effort now but I will require some close support from you guys. I don't know how to do all those steps described and I'm sure we will hit bumps in the road. But let's give it a go 🚀

**Comment by sauloperez** [comment]
I think is best if we wait for Katuma to migrate to a new production server using Ubuntu 18.04 so that we make any needed changes to ofn-install ourselves. This will your migration easier.
