### ISSUE TITLE
Deploy v1.24.0 to European instances

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/ofn-install#301]
The release https://github.com/openfoodfoundation/openfoodnetwork/releases/tag/v1.24.0 needs to be deployed to the following instances

- [x] France
- [x] UK
- [x] Belgium
- [x] Katuma

**Comment by sauloperez** [comment]
Due to https://github.com/openfoodfoundation/ofn-install/issues/295 the Scandinavian instance needs to be dealt with separately. @sigmundpetersen how have been you doing this? Do you perform the deploys yourself?

**Comment by sauloperez** [comment]
Done! :tada:

**Comment by sigmundpetersen** [comment]
@sauloperez yes I am still using git push with post-receive script to deploy. Will let you know on any updates towards using ofn-install on the linked #295

**Comment by sauloperez** [comment]
@luisramos0 reported in https://openfoodnetwork.slack.com/archives/CDLKH9MM0/p1545906405003100 that UK and FR were running on last Friday's `master`. I just deployed v1.24.0 again there.
