### ISSUE TITLE
Apply for github.com/nonprofit

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/ofn-install#308]
AFAIK we meet all requirements to apply for https://github.com/nonprofit. This will enable us to have private repos while keeping our account free.

For this, we need to understand what's the OFN instance which is the most not-for-profit. Any ideas? @Matt-Yorkley @myriamboure @kirstenalarsen ? Katuma is legally defined as not-for-profit but that's as per a Catalan law so no idea whether it'll be ok for Github.

**Comment by sauloperez** [comment]
Relevant for this. AUS and Katuma is non-for-profit but AUS is a charity and they registered the account. Let's go with AUS first.

**Comment by luisramos0** [comment]
All we need is to create a support request [here](https://github.com/contact?form[subject]=Nonprofit%20account%20request) with:

- [X] Your nonprofit’s GitHub organization account name
    -- openfoodfoundation
- [X] Your nonprofit’s GitHub organization URL
    -- http://github.com/openfoodfoundation
- [ ] Proof of your nonprofit status with your local government (501(c)(3) status in the US)
- [ ] The registered name of your nonprofit
- [ ] A summary of what your nonprofit organization does
- [ ] Confirmation that your organization is nongovernment, nonacademic, noncommercial, nonpolitical and has no religious affiliation.

**Comment by luisramos0** [comment]
I guess @kirstenalarsen will be the closest to the documents about the openfoodfoundation charity in AUS, right?

**Comment by kirstenalarsen** [comment]
[] [Certificate as registration as a charity.pdf](https://github.com/openfoodfoundation/ofn-install/files/2879452/Certificate.as.registration.as.a.charity.pdf)
[] Open Food Web Foundation Limited
[] Summary as in Constitution
![image](https://user-images.githubusercontent.com/2911176/53006986-784db300-348a-11e9-9a9e-9532fb601afa.png)
[] confirmed

**Comment by luisramos0** [comment]
ah, awesome, thank you Kirsten!
I'll submit the form now.

**Comment by luisramos0** [comment]
form sent.

**Comment by luisramos0** [comment]
ah, done ❤️ 
![screenshot 2019-02-22 at 21 46 06](https://user-images.githubusercontent.com/1640378/53273239-6159cb80-36eb-11e9-845a-7fefcd6e241d.png)
