### ISSUE TITLE
Create per-instance private repos to hold their secrets.yml

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/ofn-install#309]
We need each OFN instance to have its own private repo to store its secrets.yml. Similar to what we did with https://github.com/coopdevs/katuma_secrets but private so we avoid people with bad intention knowing too many details.

Update: the repo has now been created and half of the secrets have been added. The remaining ones are:

- [x] `de-prod`
- [x] `ca-prod`
- [x] `us-prod`
- [x] `au-prod`
- [x] `au-staging`
- [ ] ~~`no-prod`~~

**Comment by mkllnk** [comment]
You mentioned on Discourse that we can apply for https://github.com/nonprofit to get free private repos. Is it enough to apply once for our Github organisation `openfoodfoundation` or do we all need to do that independently?
If we can do it for the organisation, we can structure the repos similar to the l10n repos.

**Comment by sauloperez** [comment]
I have no idea. That is what we need to find out.

**Comment by luisramos0** [comment]
openfoodfoundation has now unlimited users and unlimited private repos 🤣 
GO!

**Comment by sauloperez** [comment]
Did you do it @luisramos0??

**Comment by sauloperez** [comment]
I see! It went smoothly! Thanks a ton for taking the intiative! ❤❤❤

**Comment by mkllnk** [comment]
Great job @luisramos0!

**Comment by Matt-Yorkley** [comment]
I'd like to take this on, and I have some proposals on implementation so that we can later automate pulling the secrets files from the repo when we do Semaphore deployments. 

- Make a single private repo for secrets. Restrict access to core devs.
- Create a very strong password and add it to Bitwarden
- Encrypt all secrets files using ansible-vault and the strong password (same one for all secrets files)
- Add a folder for each server in the secrets repo, using the same naming system as entries in ofn-install hosts files, like this:

```
/uk-staging
    secrets.yml
/fr-prod
    secrets.yml
```

**Comment by mkllnk** [comment]
Great! I'm happy to have only one repo.

**Comment by Matt-Yorkley** [comment]
I'm thinking this could increase the chances of sysadmins accidentally deploying with the secrets file not included? Maybe we can add in a task that stops deployment if no secrets are present when it runs..?

**Comment by sauloperez** [comment]
Looks good @Matt-Yorkley . This makes their management undoubtedly easier. I also see a not less important political dimension to it; per-instance secrets become a common we protect and care for.

**Comment by Matt-Yorkley** [comment]
Ok, I've added most servers' secrets files to the new private repo. I don't have access to Germany's server and I'm not sure about some of the other instances. Here's the list of which ones are left:

- [ ] `de-prod`
- [ ] `ca-prod`
- [ ] `us-prod`
- [ ] `au-prod`
- [ ] `au-staging`

**Comment by sauloperez** [comment]
DE's secrets are under Coopdevs at https://github.com/coopdevs/ofn-de-secrets so I can do it myself.

**Comment by sauloperez** [comment]
Done in https://github.com/openfoodfoundation/ofn-secrets/pull/1
