### ISSUE TITLE
Enable deployment of mulitple instances at once

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/ofn-install#313]
## Description

Today it's been the first we deploy the latest release to a bunch of instances together (European ones) instead of having to wait for everyone to update their instances, which results in inefficiencies.

A problem I saw is that I wasn't entirely sure how Ansible would pick up and distinguish between each instance's secrets. To avoid problems I chose to deploy them one by one although what I really wanted was to do deploy them at the same time. In my mind, there shouldn't be any difference between our setup and an app that has multiple app and DB servers. 

In any case, I found the process tremendously error-prone. It was too easy to get French secrets and use them to deploy to UK, for instance.

## Proposed solution

First, we'll need to have a group defined so that we can do something like `--limit=europe`.

Then, we need to check https://docs.ansible.com/ansible/latest/user_guide/playbooks_best_practices.html#group-and-host-variables and see what's the best for Ansible to differentiate the secrets.

However, https://github.com/openfoodfoundation/ofn-install/issues/307 needs to be taken into account. Any solution we implement needs to work with that approach as well or should be easy to refactor to adapt to it.

**Comment by sauloperez** [comment]
It was bound to happen. See https://openfoodnetwork.slack.com/archives/CDLKH9MM0/p1545906405003100 for an example that explains why we need this.

**Comment by Matt-Yorkley** [comment]
OK, so I've come up with a proposal for this "enable deploying multiple servers at once" issue which involves using the Semaphore deployment system on production servers and includes automatically pulling the up-to-date secrets files from the new private repo during deployment.

It would mean we could deploy the next release to all European servers at the click of a button (if we wanted to).

The (potentially controversial) secrets-fetching part is here: #369 
Setting up Semaphore deployments on any server takes ~5 minutes.

We would then have a beautiful display of all our servers, their current states and their deployment histories (including detailed deployment logs), and deploying multiple servers at once would be effortless.

![Screenshot-2019-04-02-18-04:17](https://user-images.githubusercontent.com/9029026/55494685-26747d00-5633-11e9-991c-b715eccb03f4.png)
![Screenshot from 2019-04-02 17-41-19](https://user-images.githubusercontent.com/9029026/55494710-32603f00-5633-11e9-8def-1d46919da716.png)

**Comment by sauloperez** [comment]
This would be huge ❤
