### ISSUE TITLE
DB monitoring

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/ofn-install#317]
## Description

Similar to what we started doing with #293 and #274, we need to get insights into the operation of our database which can likely be tuned to better suit our needs. I'm also sure we might discover things we're not aware of that might need fixing.

## Proposed solution

Datadog seems to have a decent [PostgreSQL integration](https://docs.datadoghq.com/integrations/postgres/) that looks pretty straightforward to install.

**Comment by sigmundpetersen** [comment]
Is this complete @sauloperez or are there any issues you would like to add to it?

**Comment by sauloperez** [comment]
Thanks for the heads-up! I'll write a summary of the current status for the recor before closing. We had to disable some logging because it wasn't useful with the current settings.
