### ISSUE TITLE
Background jobs monitoring

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/ofn-install#318]
## Description

As part of #274, we need to know when and how long our background jobs perform plus what resources they use.

This will likely help us explain why we have this recurrent CPU spikes every few hours. See below for an example of UK's server

![screenshot from 2019-01-02 11-28-02](https://user-images.githubusercontent.com/762088/50588284-a6971500-0e81-11e9-89fd-26d9e93c1053.png)

Although they might not require any action and they might be just fine, we should be able to explain them. It shouldn't be unknown.

## Proposed solution

Skylight recently started an invitation-only alpha version of background jobs monitoring we can apply to.

Also, Datadog seems to have support for Delayed Job. Check https://github.com/DataDog/dd-trace-rb/pull/444 for reference.

Finally, there is also [Delayed Job Web](https://github.com/ejschmitt/delayed_job_web) and old project that adds a web interface for delayed job, inspired on Resque web.

**Comment by sigmundpetersen** [comment]
Is this good to go @sauloperez or any more actions you have in mind here?

**Comment by sauloperez** [comment]
It'd be good to have a look while working on https://github.com/openfoodfoundation/ofn-install/issues/496 because I think it's as simple as enabling DJ integration in Datadog.
