### ISSUE TITLE
Delete old releases after deploy

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/ofn-install#321]
Each deploy creates a backup in `releases_old`. That fills up the disk over time. I propose a new playbook that deletes some old releases. For example, we could delete every release that is older than three days.

**Comment by sauloperez** [comment]
I believe the pattern is to keep N releases, regardless of their deploy date, where N can be something like 5. That is what you get with Capistrano for instance.

**Comment by sauloperez** [comment]
We need to investigate if ofn-install deletes the oldest. It should keep N only.
