### ISSUE TITLE
Remove old file absence check

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/ofn-install#332]
## Description

As soon as https://github.com/openfoodfoundation/ofn-install/pull/329 gets provisioned to all servers, we can remove `remove bugsnag's initializer from the shared folder` task. It won't be longer needed as the file will be removed already.

**Comment by Matt-Yorkley** [comment]
That reminds me, we can now remove the task `clean up monit` and the two handlers that it calls.

**Comment by sauloperez** [comment]
At this point all ofn-install-based servers should have this absence check in place, so we can remove it whenever we want.

**Comment by sauloperez** [comment]
I just checked and UK, FR, Katuma, BE and DE do not have any `shared/config/bugsnag.rb`. AU however does.
