### ISSUE TITLE
What is the optimum number of Unicorn workers?

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/ofn-install#338]
Recently we have been seeing a number of servers timeout often and it is causing instance managers stress about OFN performance issues.

On personal reflection I think the issue is that we have a lot of data heavy pages and too few Unicorn processes. This means that we might end up with a case that x big pages are loading and an x+1 user comes in and wants to load any page and gets a slug and we all scream out "OFN is down" and panic ensues for a few minutes. (Where x=number of unicorn workers)

Within unicorn settings we can choose the number of workers.

My question is 'What is the optimum number of unicorn workers?'

I found[ this medium post](https://medium.com/@fuigaro/introduction-32a87fe8ae2b) that suggests that it is potentially the number of CPUs +1 (well it is a bit more specific than that. A little out of my depth).

It would be great to clarify a little:
- How does NGINX or Unicorn or whatever manage CPU load?
- If a worker is stuck waiting for a response does it block a CPU from other processes or can it continue on other tasks. The post above suggests it does but obviously we don't want a race condition in which CPUs are all blocked waiting for a response and there is no processing power to do DB requests, other server processes etc.

Hopefully devs have a little insight into this and we can get some good clarification that means that we can always have the optimum number of workers in relation to CPUs/mem such that we optimally increase actual server specs in relation to unicorn settings.

This will be very helpful as instances juggle keeping users happy while we work on performance issues.

**Comment by mkllnk** [comment]
The main limitation of workers is memory. We adjusted the number over time and ended up with two. But any number is okay, it doesn't have to be even. It may also be that updates within the last years mean that we can run more workers again or we just buy more memory.

Our Australian server has two workers and 7 GB of memory. Only 1 GB is free at the moment. A lot of memory (3.5 GB) is used by buff/cache though. `top` says that 3.7 GB are available.

Each worker process uses around 0.8 GB but that doesn't mean that we can start 4 more workers. There are spikes in memory consumption when converting uploaded images and maybe other tasks like compiling PDFs. We always need some free memory for that. It would be good to find out how much.

**Comment by lin-d-hop** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Site Down Intermittent Error](https://trello.com/c/IUkIofZm/415-site-down-intermittent-error)

**Comment by sigmundpetersen** [comment]
Can we close this with the merge of #356 @lin-d-hop @Matt-Yorkley ?

**Comment by mkllnk** [comment]
The question is not answered yet. We may know that 3 workers is better in the UK than 2. What do you think about this formula?

```
n = (total_memory - service_usage) / worker_usage

# UK example now:
(8GB - 1GB) / 1GB = 7

# Aus example:
(7GB - 1GB) / 1GB = 6
```

That is generous because the UK workers use only around 0.8 GB and the rest of the systems is using only 0.8 GB as well. But an Australian worker uses 0.84 GB at the moment and it could increase over time.

**Comment by mkllnk** [comment]
We don't use ofn-install to provision the Aus server yet but I just increased our worker count to `4`.

```
# edit /home/openfoodnetwork/apps/openfoodnetwork/shared/config/unicorn.rb
/etc/init.d/unicorn_openfoodnetwork restart
```

**Comment by mkllnk** [comment]
Looking good, no outage in the last two days:
![Screenshot from 2019-04-05 11-01-33](https://user-images.githubusercontent.com/3524483/55595993-3ce51a80-5792-11e9-8a38-dcf99609b861.png)

Memory consumption is looking good as well:
![Screenshot from 2019-04-05 11-02-20](https://user-images.githubusercontent.com/3524483/55596023-5b4b1600-5792-11e9-9465-1b2128823717.png)

**Comment by sauloperez** [comment]
Finally! getting more out of our resources! :clap: Let us know the status in a week or so.

**Comment by mkllnk** [comment]
The situation improved but we still got some failures. I increased the worker number to 5 since we seem to have enough memory.

![Screenshot from 2019-04-16 10-37-50](https://user-images.githubusercontent.com/3524483/56174022-d5518980-6033-11e9-8c55-5f86b9a2d944.png)
![Screenshot from 2019-04-16 10-38-28](https://user-images.githubusercontent.com/3524483/56174028-d97da700-6033-11e9-8729-ef8abd4ecf21.png)

**Comment by daniellemoorhead** [comment]
Where to next with this task @mkllnk @lin-d-hop? Can we consider it done given Maikel's results above? Or still more to do?

**Comment by sauloperez** [comment]
It'd be great to move it to a discourse thread of we want to share the experiences of these instances

**Comment by RachL** [comment]
Yes, I also would like to know what would be the optimum number for France.

**Comment by mkllnk** [comment]
I created a wiki page to document the outcome of this issue: https://github.com/openfoodfoundation/ofn-install/wiki/Performance
It's also a good place for @Matt-Yorkley's other performance experiments. We can share temporary experiments and results on Slack or Discourse. So I'm closing this issue now.

Australia is now using 6 workers and our availability increased from 99.583% last month to 99.836% in the last two weeks. That is more than halving our downtime to ~2.5 minutes per day.

@RachL The French production server has 8 GB memory and uses only 2 GB at the moment. I think it can safely go up to 6 workers. Adding a swap file would be a good idea as well. Depending on the results I would predict we can easily go to 8 workers on that server.
