### ISSUE TITLE
Provision and deploy Canada's production with ofn-install

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/ofn-install#339]
We need to reprovision and then deploy Canada's production server with `ofn-install`. This will require adding its configuration settings to this repo and prevent people from using it while we provision and deploy.  

We need a new server for Canada that is fully set up with `ofn-install`. This will require:

- [x] Add configuration settings to this repo
- [x] Provision the new machine
- [x] Deploy to the new machine
- [x] Stop old server (at night when no one uses it)
- [x] Import database dump to the new server
- [x] Change DNS record to point to the new server
- [x] Ditch the old server

#### Community forum discussion
https://community.openfoodnetwork.org/t/upgrades-rollouts-and-potential-blockers/1620

**Comment by sauloperez** [comment]
@mkllnk shared the CAN Digital ocean credentials in Bitwarden.

**Comment by Matt-Yorkley** [comment]
It's done! :tada:

I'll let the dust settle a bit before deleting the old server.

**Comment by kirstenalarsen** [comment]
ya hoo! happy @tschumilas :)
