### ISSUE TITLE
Where is the Ruby Update playbook used

### ISSUE THREAD

**Issue by danypr92** [openfoodfoundation/ofn-install#341]
I am starting a task to cover the #157 in the Katuma servers and we are looking the playbooks that we are using.

I found the playbook `ruby_update.yml` and I don't understand where this playbook is used. 

https://github.com/openfoodfoundation/ofn-install/blob/master/playbooks/ruby_update.yml

The tasks that are done in this playbook also are done in the `provision.yml` playbook.

https://github.com/openfoodfoundation/ofn-install/blob/master/playbooks/provision.yml#L32

Is this playbook needed?

Thanks!

**Comment by mkllnk** [comment]
A few years ago we used the provision playbook only for the initial server install. After that we only deployed. When we switched from Ruby 1.9 to Ruby 2.1 Rohan wrote a playbook to do that on all servers. Now we would do that through the provision playbook. We don't need ruby_update any more.
