### ISSUE TITLE
Ubuntu 18 compatibility

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/ofn-install#342]
We need to update our ofn-install scripts to get OFN compatible with Ubuntu 18 (Bionic Beaver). 

We can use this epic to track issues and co-ordinate with coopdevs. :wave:

**Comment by Matt-Yorkley** [comment]
@danypr92 have you started looking at Bionic Beaver compatibility? I'm running our playbooks against a bionic64 Vagrant box now, to see what comes up.

**Comment by enricostano** [comment]
We've been talking about this with @sauloperez today during the morning :joy: 

We need a plan for it, thanks for bringing this out @Matt-Yorkley :muscle:

**Comment by Matt-Yorkley** [comment]
We might want to do some more testing and investigation, but I'm pretty sure I've successfully fixed the compatibility issues: #348

**Comment by sigmundpetersen** [comment]
Can we close this then @Matt-Yorkley @mkllnk ?

**Comment by Matt-Yorkley** [comment]
Lets leave it open for now. The plan is to provision a fresh staging server with these changes as a test.

**Comment by Matt-Yorkley** [comment]
Closing; `ofn-install` is compatible with Ubuntu 18 and Aus production is using it live.
