### ISSUE TITLE
Package "python-software-properties" has been obsoleted

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/ofn-install#343]
The `python-software-properties` package (listed in our packages in ofn-install) has been obsoleted in 18 and it looks like it's been replaced/superceded by package: `software-properties-common`.

```
Package python-software-properties is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  software-properties-common

E: Package 'python-software-properties' has no installation candidate

```

It looks like `software-properties-common` is also available in 16, so maybe we can just switch it out...

**Comment by Matt-Yorkley** [comment]
I've tested replacing `python-software-properties` with `software-properties-common` on both 16 and 18, and it seems to be working.

**Comment by sauloperez** [comment]
Let's do it then
