### ISSUE TITLE
Remove old playbooks

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/ofn-install#347]
We've got some old playbooks lying around that can probably be removed.

- update_ruby.yml
- verify.yml

This was mentioned as part of the coopdevs team looking at the upgrade to Ubuntu 18. I've had a look and I think we can scrap them.

**Comment by enricostano** [comment]
https://github.com/openfoodfoundation/ofn-install/issues/341

**Comment by Matt-Yorkley** [comment]
Ah, sorry! I missed that. I was just working off of a screenshot from Pau of a Trello board in Catalan. :see_no_evil:

**Comment by Matt-Yorkley** [comment]
On further inspection, there's a few outdated playbooks here I think we should definitely :fire:, and a few I'm not sure about as I've never used them.

**debug.yml**
Summary: some commented out lines, and a command that checks the database, but as the `ubuntu` user? 
:fire: :fire: :fire: 

**development.yml**
Apparently for provisioning dev environments, but looks a bit outdated. Does anyone use this? 
:fire:

**import.yml**
From 2016. Used for importing database dumps. Has anyone used this in the last 3 years?
:fire:

**ruby_update.yml**
An old file for updating the Ruby version on a server. I'm pretty sure if we were ever updating the Ruby version this is absolutely not how we would do it...
:fire: :fire: :fire: 

**verify.yml (and verify role)**
Another ancient playbook (and corresponding role). It's purpose seems to be to check if an instance is online, but it also has: "NOT INTENDED TO BE RUN ON A PRODUCTION SERVER" written in the comments...?
:fire: :fire: :fire: 

Does anyone think any of these should be kept? @mkllnk @sauloperez @enricostano

**Comment by sauloperez** [comment]
I posted my comment about development.yml in the PR itself, I didn't see this.

**Comment by sauloperez** [comment]
@danypr92 what were your thoughts about ruby_update.yml? I think you mentioned it was pointless?

**Comment by mkllnk** [comment]
> debug.yml

:fire:

> development.yml

Discussed on the PR, maybe useful to keep. Should be documented though.

> import.yml
> From 2016. Used for importing database dumps. Has anyone used this in the last 3 years?

No. Never heard of it. :fire: 

> ruby_update.yml

I commented on #341. :fire:

> verify.yml (and verify role)

Never head of it. :fire:
