### ISSUE TITLE
Missing ssh keys on fresh install

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/ofn-install#349]
When installing on a fresh server, the ssh keys need to be added to the ofn-admin user as `root` on the first run, in `setup.yml`. 

Otherwise when we run `provision.yml` there is a fatal error due to the ssh keys not being present when the playbook tries to execute tasks as ofn-admin.

**Comment by enricostano** [comment]
Yep, this is what we to in other Ansible projects at Coopdevs, first run with `--user=root`.
