### ISSUE TITLE
Re-add Stripe API details to French staging

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/ofn-install#354]
The stripe keys got lost from the secrets file when the server was reset recently, so we need to re-add them.

- [x] Add Stripe details
- [x] Provision fr-staging
- [x] Encrypt and update in repo

**Comment by Matt-Yorkley** [comment]
And S3 settings for image storage...

**Comment by sauloperez** [comment]
OMG I'm so glad we're fixing all this madness...

**Comment by Matt-Yorkley** [comment]
Done.
