### ISSUE TITLE
Postgresql tuning

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/ofn-install#361]
This was mentioned somewhere else, but we don't have an issue for it.

Postgresql sets incredibly conservative configuration values by default that are not well-suited to production servers.

There are quite a few "recommended" tuning settings but most of them are based on the resources of the system being tuned (available RAM, etc). I've anecdotally seen references to ~30% performance increases just by applying recommended settings.

Given that we seem to be hitting some performance issues, maybe we should prioritise a spike on this at some point for some quick wins.

**Comment by lin-d-hop** [comment]
I would say this should be a high priority due to recent French server crashes due to postgres. @luisramos0?

Ping @RachL @myriamboure

**Comment by luisramos0** [comment]
I agree with prioritising this, also because it should be a relatively quick task.

**Comment by Matt-Yorkley** [comment]
It looks like these are the most important and easiest to calculate:

- **shared_buffers**: defaults to 128MB, recommended setting: 1/4 of total ram
- **effective_cache_size**: defaults to 4GB, recommended setting: 3/4 of total ram
- **maintenance_work_mem**: defaults to 64MB, recommended setting: 1/16 total ram

We can add these easily with Ansible...

**Comment by Matt-Yorkley** [comment]
I've also increased `work_mem` from 4MB to 6MB. This one is a bit more contentious. Consensus seems to be the 4MB default is not enough for a production server. 

Suggestions range from "set it somewhere between 10MB and 64MB based on your specs" to various complicated calculations based on cpus, ram, and other config settings. Setting it too low can cause problems, but setting it _too high_ can also cause problems if there are lots of requests at once.

There's an online app for calculating optimum postgres settings here: https://pgtune.leopard.in.ua/
Punching in a few different numbers based on the low to high ranges of our various production server specs puts the recommended `work_mem` somewhere between 6MB and 10MB, so I opted for 6MB as a conservative increase.

Background here: https://www.citusdata.com/blog/2018/06/12/configuring-work-mem-on-postgres/

**Comment by sauloperez** [comment]
When mentioned tunning Postgres I had checked https://github.com/gregs1104/pgtune. It's worth keeping it in our toolbelt as well. I believe the numbers are quite similar to what https://pgtune.leopard.in.ua/ gives.

**Comment by Matt-Yorkley** [comment]
Yep. The only problem is: `pgtune` hasn't been maintained or updated for at least 4 years, and it's config recommendations don't stretch above postgres `9.2` I think. The project at https://pgtune.leopard.in.ua/ is a fork based on updating `pgtune` for use with newer versions. I rummaged around in the source code of their app whilst looking for ways to calculate settings.
