### ISSUE TITLE
Change to a Datadog's paid plan

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/ofn-install#367]
As explained in-depth in https://community.openfoodnetwork.org/t/making-operations-a-first-class-citizen/1601 we need to start paying for Datadog to get data retention longer than a day plus valuable integrations such as Postgres and Delayed Job, essentials at this point for OFN.

**Comment by sauloperez** [comment]
We're currently monitoring UK, FR and Katuma but I'd also like to add other smaller instances finding the balance of ease of management (fewer conditionals to keep in mind) and pricing. As for AU, it was agreed in https://github.com/openfoodfoundation/ofn-install/issues/273 that it'll stick to Wormly instead of Datadog.

![Screenshot from 2019-04-03 14-57-41](https://user-images.githubusercontent.com/762088/55481316-654e0700-5622-11e9-8fd7-06a60aef19ab.png)

If we go up to 5 hosts that is 90$ per month, whereas if we stick to 3 hosts: UK, FR, Katuma that is 54$. Both amounts are totally affordable IMO.

If we paid anually we would save 3$ per host per month. Is it worth the cost of being locked with Datadog for a year? Chances are that we won't move from it in year though. I guess it's more an accounting/management question.

thoughts @myriamboure @Matt-Yorkley @mkllnk ?

**Comment by enricostano** [comment]
What about data retention with these prices?

**Comment by luisramos0** [comment]
You know I'd put this money right way into metal... you can almost double all those 5 servers' capacity with this money #performance

Anyway, it will be nice to have this data!!!

**Comment by sauloperez** [comment]
I know @luisramos0 what's the value of such metal if have no idea what is going on under the hood?

**Comment by sauloperez** [comment]
> What about data retention with these prices?

That comes with 15-month data retention.

What I see now is that we might need to pay for the Application Performance Monitoring product to get the Delayed Job integration. I just sent an email to customer support to have a clear answer. If that was the case, it'd be extra 31$ per host per month. IMO we could live without it as long as we do get the PostgreSQL integration.

**Comment by luisramos0** [comment]
we have a 30secs page load time currently on shops list, map and the backoffice for super admins on the main instances is a total joke.
it's a tricky discussion, I understand you see other priorities, that's why I only shared what I'd do: buy metal. imo we are not doing correct infrastructure capacity planning.

**Comment by sauloperez** [comment]
> I understand you see other priorities

Not at all. We do have the same ones it's just that we see other ways to reach the same goal. I think I've shared this screenshot several times but how will more metal other the one is underused will change the situation? See UK's production stats below.

![Screenshot from 2019-04-03 15-59-15](https://user-images.githubusercontent.com/762088/55484968-c4634a00-5629-11e9-968a-06b9ac2d4b9d.png)

With the current specs they experience regular downtime not to mention the 1h 40min OFF had with the same specs, for which I wrote a [postmortem](https://community.openfoodnetwork.org/t/postmortem-report-on-open-food-frances-incident-on-03-20-2019-02-47-pm-utc/1602).

**Comment by luisramos0** [comment]
uptime and performance are two different priorities.

I have seen metal help with uptime even when the data is looking normal as those images show (load average of 3 for 4 cpus is something, it's not like the server is sleeping).

but it can also be a bug.

in the past I have used monitoring data to detect problems, very rarely to fix problems.

**Comment by sauloperez** [comment]
> uptime and performance are two different priorities.

Absolutely. while I stopped working on the second to stick to the priorities until we have the gathering I don't think we can afford not caring about the former.

> in the past I have used monitoring data to detect problems, very rarely to fix problems.

And that is all I want

**Comment by sauloperez** [comment]
Let's not forget this is also needed to have  decent data retention that allows us to spot problems caused by the v2 roll out as explained in https://community.openfoodnetwork.org/t/making-operations-a-first-class-citizen/1601

**Comment by enricostano** [comment]
> That comes with 15-month data retention.

15 days?

**Comment by sauloperez** [comment]
![Screenshot_20190403-181427](https://user-images.githubusercontent.com/762088/55495075-68ee8780-563c-11e9-86ba-b10e288d4d61.png)

**Comment by Matt-Yorkley** [comment]
First impressions: 

- is $90 per month expensive for this sort of thing? I don't have anything to compare it to.
- do we need 15-month data retention?

**Comment by mkllnk** [comment]
We pay $36 for Wormly in Australia. It would increase if we added a lot more hosts for monitoring but probably not as much. They don't bill by host, they bill by how many metrics you are monitoring. Anyway, my conclusion is that those prices are comparable and there is not much in it.

If we talk about an additional $31 for APM, that's very expensive. That would be $155 extra for the five hosts.

Can we select for which hosts we go paid and for which ones we don't or do we then need two accounts?

It's probably enough to get data retention for two or three big instances and maybe APM for one instance. The application behaves pretty much the same on each host. That makes it affordable and should give us all the data we need.

**Comment by sauloperez** [comment]
That's another option we could explore in the future. I would keep things agile for now and stick to the paid plan to get longer retention plus the PostgreSQL integration. This would be a lot already as we already have a basic APM with Skylight.

To answer you @Matt-Yorkley 

> do we need 15-month data retention?

We don't but that's what they offer.

**Comment by RachL** [comment]
@sauloperez I think in France we are ok to go forward with this :) Let's do it!

**Comment by sauloperez** [comment]
Done! Say hello to a wealth of data and more to come!

![Captura de pantalla 2019-04-19 a les 10 17 50](https://user-images.githubusercontent.com/762088/56414973-91a58c80-628c-11e9-889e-3f94b250254a.png)

👆 France production. I did my best to get some sort of discount but no luck. We'll see as we pay for more hosts in the future 🤞
