### ISSUE TITLE
Configure deadlock logging and handling

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/ofn-install#377]
Stems from https://community.openfoodnetwork.org/t/making-operations-a-first-class-citizen/1601.

We are seeing a (increasing?) number of deadlocks in Bugsnag which don't seem to be logged by Postgres for further inspection. We can't know if they are the root cause of the regular downtime we experience either.

**Comment by Matt-Yorkley** [comment]
What level of logging do you need? `cat /var/log/postgresql/postgresql-9.5-main.log | grep -A 2 "blocked by process"` gives pretty good feedback.

**Comment by sauloperez** [comment]
This information seems to be enough. I wonder what does the `log_lock_waits` setting do then because we have it disabled and still we get the errors. Closing anyway.
