### ISSUE TITLE
You don’t have to write every role from scratch.

### ISSUE THREAD

**Issue by ypid** [openfoodfoundation/ofn-install#39]
First of all, nice that there is an Ansible Playbook and a Vagrantfile to setup openfoodfoundation.

The problem is that it is not easy that way to integrate the roles into my Ansible setup. I already use other roles to manage various aspects of my servers so the current approach of ofn_deployment kind of conflicts with this. One way to solve this would be to move the currently "playbook centric" approach to a more "role centric" approach. And then publish the openfoodfoundation related roles individually.

Any suggestions for such an advanced user?

Second related hint: You don’t have to write common roles like Database setup or Webserver setup yourself. Have a look at the [DebOps project](http://debops.org/) for a set of high-quality roles for all the basics like this.

**Comment by pmackay** [comment]
Hi @ypid, I'm aware that in this first version of ansible scripts for OFN, there is a lot that is coded here that could be managed by other roles. Its a refactoring task that would be great to do, but currently not so high on the priority list.

**Comment by ypid** [comment]
Understandable. Maybe someday :smile:

**Comment by pmackay** [comment]
@ypid just wondering, do you have any thoughts on best practice of developing a role at the same time as a playbook using the role?

**Comment by ypid** [comment]
I would go with one git repository per role, ideally all interdependently tested using CI and then create a repository for the playbooks which can include the individual roles using git submodules. I kind of do similar things for my personal role/playbook stack: https://github.com/ypid/ypid-ansible-common
Alternatively, you can also use Ansible Galaxy and use it to handle role dependencies of the playbooks. For reference, here is also the main playbooks repo of the DebOps project: https://github.com/debops/debops-playbooks

**Comment by pmackay** [comment]
Closing but this is something we are gradually evolving to. Not sure if it will be reached though :)
