### ISSUE TITLE
Upgrade Certbot role!

### ISSUE THREAD

**Issue by darshana-danrox** [openfoodfoundation/ofn-install#392]
on ubuntu 16.04 

PLAY RECAP
www.openfoodnetwork.org.pt : ok=49   changed=3    unreachable=0    failed=1   

 Error details : 

fatal: [www.openfoodnetwork.org.pt]: FAILED! => {
    "cache_update_time": 1555157377, 
    "cache_updated": false, 
    "changed": false, 
    "invocation": {
        "module_args": {
            "allow_unauthenticated": false, 
            "autoclean": false, 
            "autoremove": false, 
            "cache_valid_time": 0, 
            "deb": null, 
            "default_release": null, 
            "dpkg_options": "force-confdef,force-confold", 
            "force": false, 
            "force_apt_get": false, 
            "install_recommends": null, 
            "name": "certbot=0.28.0-1+ubuntu16.04.1+certbot+4", 
            "only_upgrade": false, 
            "package": [
                "certbot=0.28.0-1+ubuntu16.04.1+certbot+4"
            ], 
            "purge": false, 
            "state": "present", 
            "update_cache": null, 
            "upgrade": null
        }
    }, 
    "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"     install 'certbot=0.28.0-1+ubuntu16.04.1+certbot+4'' failed: E: Version '0.28.0-1+ubuntu16.04.1+certbot+4' for 'certbot' was not found\n", 
    "rc": 100, 
    "stderr": "E: Version '0.28.0-1+ubuntu16.04.1+certbot+4' for 'certbot' was not found\n", 
    "stderr_lines": [
        "E: Version '0.28.0-1+ubuntu16.04.1+certbot+4' for 'certbot' was not found"
    ], 
    "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\n", 
    "stdout_lines": [
        "Reading package lists...", 
        "Building dependency tree...", 
        "Reading state information..."
    ]
}

**Comment by luisramos0** [comment]
hello, can you please share:
- in what stage of the guide are you in? https://github.com/openfoodfoundation/ofn-install/wiki/Configuration
- what exact command did you execute
- the content of your config files: in hosts and group vars

Thanks!

**Comment by Matt-Yorkley** [comment]
Is your target server on Ubuntu 16.04 as well?

**Comment by darshana-danrox** [comment]
Hi luisramos0 

Here is the requested details .

stage of the guide :  Provisioning

Command that I Execute :  ansible-playbook -vvvvv  site.yml 

@Matt-Yorkley  :  Yes 

[hosts&group_vars.zip](https://github.com/openfoodfoundation/ofn-install/files/3076407/hosts.group_vars.zip)

**Comment by Matt-Yorkley** [comment]
I've never seen that before, so I can only make some guesses... it looks like apt hasn't found the package it's looking for. The failing task is run by a third-party module we use for certbot: https://github.com/coopdevs/certbot_nginx

A brief look suggests it might not ensure apt is updated after adding the certbot repo and before fetching the package...

So I would try updating apt on the server with `sudo apt update` and re-run the playbook?

**Comment by enricostano** [comment]
I would say that the issue could be related to `ofn-install` not using https://github.com/coopdevs/certbot_nginx/releases/tag/0.0.4

**Comment by darshana-danrox** [comment]
try with update and still not resolved 

if you try this command in directly in terminal you see there is no such package  

/usr/bin/apt-get -y -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold" install certbot=0.28.0-1+ubuntu16.04.1+certbot+4
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Version '0.28.0-1+ubuntu16.04.1+certbot+4' for 'certbot' was not found

**Comment by enricostano** [comment]
@darshana-danrox try the following

1. change `0.0.3` for `0.0.4` in https://github.com/openfoodfoundation/ofn-install/blob/master/bin/requirements.yml#L12
2. run `ansible-galaxy install -r bin/requirements.yml --force`

If it solve your issue please consider to open a PR to `ofn-install` with the suggested changes.

**Comment by luisramos0** [comment]
@darshana-danrox we are very happy to have you guys on board!

Before we continue with this support process someone from your organisation needs to sign the OFN pledge: https://community.openfoodnetwork.org/t/ofn-community-pledge-v1-0-1-june-2017/948

From previous conversations it looks like you will be associates and that means you should not use the url www.openfoodnetwork.org.pt (urls using the OFN brand are for affiliates).

From the pledge:
![Screenshot 2019-04-15 at 10 17 06](https://user-images.githubusercontent.com/1640378/56121258-a79f0e80-5f67-11e9-9f30-ada19af05508.png)

Let's first sort out the collaboration model before we get into the details.
We are available for a clarification call. Let us know :heart:

**Comment by montejunto** [comment]
Thanks @darshana-danrox @luisramos0 , I will confirm with JF (organisation) on how to proceed to get back at the deployment.

**Comment by darshana-danrox** [comment]
solution provided by @enricostano Worked

**Comment by Matt-Yorkley** [comment]
I think this still needs fixing.

**Comment by enricostano** [comment]
As I sayd before:

> If it solves your issue please consider to open a PR to ofn-install with the suggested changes.

You need to use the latest `certbot_nginx` version
