### ISSUE TITLE
 Increase number of unicorn workers for French prod

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/ofn-install#395]
As done here : https://github.com/openfoodfoundation/ofn-install/issues/355

With the following PR:

https://github.com/openfoodfoundation/ofn-install/pull/356
https://github.com/openfoodfoundation/ofn-install/pull/384

We need to do this on the French server as well.

**Comment by sauloperez** [comment]
It's perfect timing now that we have graphs to compare to.
