### ISSUE TITLE
Database encoding

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/ofn-install#399]
Whilst working on #393 I discovered the encoding names for `LC_COLLATE` and `LC_CTYPE` we have been setting is incorrect. It's set by the following script as `en_US.utf8` but the correct value appears to be `en_US.UTF-8`:

https://github.com/openfoodfoundation/ofn-install/blob/96badf275642293086baf5e04bd88e863b305b81/roles/dbserver/files/fix_pg_encoding.sh#L12

In order to change the encoding on each of our databases, we would have to:

- Dump the database
- Kill all connections
- Drop and recreate the database with the the correct encoding values
- Restore the dumped data

This needs some discussion obviously. We could write a role to handle it smoothly, but the process would take a small amount of downtime.

**Comment by Matt-Yorkley** [comment]
I'm getting this with the new plugin which uses recommended values:
```
Database query failed: new collation (en_US.UTF-8) is incompatible with the collation of the template database (en_US.utf8)
```

**Comment by Matt-Yorkley** [comment]
It looks like maybe we can stick with the alternate spelling, and just force the new role to use it instead.

https://superuser.com/a/999151

**Comment by sauloperez** [comment]
:see_no_evil: thank God

**Comment by Matt-Yorkley** [comment]
Yeah, it looks like it'll be ok. We can specify it with the plugin. Here's some production values:

![Screenshot-2019-04-16-21-06:57](https://user-images.githubusercontent.com/9029026/56240516-ad8e1000-608b-11e9-820e-ec204b990dce.png)
