### ISSUE TITLE
Links and Form Actions lose PORT in Vagrant dev environment

### ISSUE THREAD

**Issue by MikeiLL** [openfoodfoundation/ofn-install#40]
I'm running the server (which loads with `default: SSH address: 127.0.0.1:2222`) from (`apps/=app_name=/current/` like `bundle exec rails server -b 0.0.0.0` and visit the site in the host machine at `127.0.0.1:3000`, but the form actions and many of the links are resolving without the port number: `http://127.0.0.1/admin/enterprises`

Is there something obvious (or subtle) that I'm missing in the vagrant configuration, OFN config or the way I'm running the app?

**Comment by pmackay** [comment]
Were you able to resolve this?

Is it possible the Vagrantfile just forwards port 80?

**Comment by MikeiLL** [comment]
What do you mean, @pmackay? That it is *only* forwarding port 80 and not, for example, port 3000?

**Comment by enricostano** [comment]
@MikeiLL I'm closing this issue since it has been too long and we still don't have a clear plan on Vagrant.

Please feel free to ping me if you want to work on it. Thanks!
