### ISSUE TITLE
Secrets check doesn't execute when using `--tags`

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/ofn-install#404]
When running part of the provisioning, for example with `-t unicorn_user` the secrets check isn't run. That can be good because most roles don't need the secret. But it makes it easy to forget the secrets when running roles which need them which would be destructive.

I'm not sure what the best approach is. Optional roles don't run when secrets are not set. But I'm not sure that all roles that require secrets fail early before changing something.

**Comment by sauloperez** [comment]
To be honest, running any playbook with tags should happen in very rare cases IMO. I think running just bits of playbooks misses the point of Ansible, which is to ensure things are in the declared state. So, in that case, I wouldn't put too much effort on it.
