### ISSUE TITLE
Create and use new locale en_AU

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/ofn-install#438]
I find it surprising that we didn't need to update any AU specific text in the en locale in years. But now it happened and it showed that our old process of changing the source locale `en` isn't great. It occupies space in the dev pipeline.

So we should create a new language file `en_AU` with Transifex and use it like everybody else. It will also make it more important for the Australian team to optimise the Transifex process if there are any issues.

**Comment by RachL** [comment]
> I find it surprising that we didn't need to update any AU specific text in the en locale in years. 

@mkllnk actually Sally opened some issues. I've grouped them under the missing translations epic which group missing keys and rephasing needed on the basic en file. Here is the list of issues:

https://github.com/openfoodfoundation/openfoodnetwork/issues/985
https://github.com/openfoodfoundation/openfoodnetwork/issues/1279
https://github.com/openfoodfoundation/openfoodnetwork/issues/1467
https://github.com/openfoodfoundation/openfoodnetwork/issues/1613
https://github.com/openfoodfoundation/openfoodnetwork/issues/1382

**Comment by mkllnk** [comment]
I just found that Transifex doesn't support Australian English. I asked the support to add it. :crossed_fingers:

**Comment by kirstenalarsen** [comment]
Does this mean that we now have a job of checking and updating translations
with new releases?

**Comment by sauloperez** [comment]
Indeed @kirstenalarsen . We announce so in the #translations Slack channel when we start preparing a new one.

**Comment by luisramos0** [comment]
a quick update on the 5 issues @RachL listed above:
- 985 was a code change and is already resolved #ukdevhack
- 1467 requires a code change (string is not translatable)
- I just closed the other 3 issues as they are now transifex work in en_AU, I added the exact transifex links to each issue:
https://github.com/openfoodfoundation/openfoodnetwork/issues/1613
https://github.com/openfoodfoundation/openfoodnetwork/issues/1279
https://github.com/openfoodfoundation/openfoodnetwork/issues/1382

**Comment by RachL** [comment]
fine by me @luisramos0 ! Thank you :) I just did the list so that Australian people know what changes where needed. ping @kirstenalarsen @mkllnk
