### ISSUE TITLE
add US prod secrets to ofn-secrets repo

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/ofn-install#440]
us-prod secrets are missing from ofn-secrets repo https://github.com/openfoodfoundation/ofn-secrets

**Comment by luisramos0** [comment]
issue moved to ofn-secrets: https://github.com/openfoodfoundation/ofn-secrets/issues/12

**Comment by Matt-Yorkley** [comment]
It's tracked here as well: https://github.com/openfoodfoundation/ofn-install/issues/309
