### ISSUE TITLE
Switch to Ansible 2.9

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/ofn-install#442]
Ansible 2.8 and 2.9 have been released, and they include a lot of new features and modules. It also changes and deprecates various bits of syntax, which apparently breaks some of our playbooks.

We should update the syntax and all switch to ~~2.8~~ 2.9 at some point.

- [x] Make a branch that runs the Travis build with Ansible 2.9
- [x] Make sure all playbooks are tested carefully (not just in the CI build)
- [x] Update/fix any syntax that needs it
- [x] Make sure everyone in the team updates their Ansible version to 2.9

Porting guide: https://docs.ansible.com/ansible/latest/porting_guides/porting_guide_2.9.html

**Comment by sauloperez** [comment]
In particular, https://docs.ansible.com/ansible/latest/modules/postgresql_query_module.html#postgresql-query-module would be a great addition.
