### ISSUE TITLE
The conditional check 'inventory_hostname not in groups['local']' failed

### ISSUE THREAD

**Issue by bakuppus** [openfoodfoundation/ofn-install#446]
Hello,

while doing ansible deployment, facing below issue. How to fix ?

fatal: [smartfarmer.pt]: FAILED! => {
    "msg": "The conditional check 'inventory_hostname not in groups['local']' failed. The error was: error while evaluating conditional (inventory_hostname not in groups['local']): Unable to look up a name or access an attribute in template string ({% if inventory_hostname not in groups['local'] %} True {% else %} False {% endif %}).\nMake sure your variable name does not contain invalid characters like '-': argument of type 'AnsibleUndefined' is not iterable\n\nThe error appears to be in '/root/ofn-install/community/coopdevs.certbot_nginx/tasks/main.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: Add certbot repository\n  ^ here\n"
}

PLAY RECAP **************************************************************************************************************
smartfarmer.pt             : ok=71   changed=1    unreachable=0    failed=1    skipped=62   rescued=0    ignored=0   

Thanks
Bala

**Comment by Matt-Yorkley** [comment]
I've never seen this one before...

My best guess is that you've switched to using a different `hosts` file and the `local` group is not present?

Either that or you've upgraded to Ansible 2.8 which has just been released and isn't yet compatible with ofn-install. Try `ansible --version` and see what it says. If it's version 2.8 you'll have to downgrade it until we finish #442 .

**Comment by bakuppus** [comment]
Hi Matt,

Is postfix MTA support  ? am getting below error, any idea ?

[image: image.png]

Thanks
Bala

**Comment by sauloperez** [comment]
@bakuppus the image didn't get attached, unfortunately.

**Comment by bakuppus** [comment]
[image: image.png]

**Comment by bakuppus** [comment]
Hi Matt,

getting a Error

tarted POST "/user/spree_user" for 122.166.162.71 at 2019-05-30 11:30:32 +0000
Processing by UserRegistrationsController#create as JSON
  Parameters: {"spree_user"=>{"remember_me"=>0,
"email"=>"bakuppus@gmail.com", "password_confirmation"=>"[FILTERED]",
"password"=>"[FILTERED]"},
"return_url"=>"https://redes.smartfarmer.pt/#/login",
"user_registration"=>{"spree_user"=>{"remember_me"=>0,
"email"=>"bakuppus@gmail.com", "password_confirmation"=>"[FILTERED]",
"password"=>"[FILTERED]"},
"return_url"=>"https://redes.smartfarmer.pt/#/login"}}
  Rendered shared/mailers/_signoff.html.haml (3.3ms)
  Rendered shared/mailers/_social_and_contact.html.haml (9.6ms)
  Rendered spree/user_mailer/confirmation_instructions.html.haml
within layouts/mailer (27.6ms)
  Rendered layouts/mailer.html.haml (55.5ms)
  Rendered spree/user_mailer/confirmation_instructions.text.erb (3.1ms)
Connecting to database specified by database.yml
[SKYLIGHT] [1.7.2] Skylight agent enabled
No valid API key has been set, notifications will not be sent
Creating scope :deleted. Overwriting existing method Spree::Variant.deleted.
Creating scope :available. Overwriting existing method
Spree::PaymentMethod.available.
Creating scope :accessible_by. Overwriting existing method
OrderCycle.accessible_by.



Any idea ?

**Comment by sauloperez** [comment]
I think that's a wrong stack. I can't see any error there.

**Comment by bakuppus** [comment]
Hi ,

While sign up new mail user, not able to sign up. No error message in web
console

but getting this error in log

Started POST "/user/spree_user" for 49.207.48.30 at 2019-06-04 17:00:01 +0000
Processing by UserRegistrationsController#create as JSON
  Parameters: {"spree_user"=>{"remember_me"=>0,
"email"=>"bakuppus@gmail.com", "password_confirmation"=>"[FILTERED]",
"password"=>"[FILTERED]"},
"return_url"=>"https://redes.smartfarmer.pt/#/login",
"user_registration"=>{"spree_user"=>{"remember_me"=>0,
"email"=>"bakuppus@gmail.com", "password_confirmation"=>"[FILTERED]",
"password"=>"[FILTERED]"},
"return_url"=>"https://redes.smartfarmer.pt/#/login"}}
  Rendered shared/mailers/_signoff.html.haml (3.9ms)
  Rendered shared/mailers/_social_and_contact.html.haml (12.7ms)
  Rendered spree/user_mailer/confirmation_instructions.html.haml
within layouts/mailer (28.2ms)
  Rendered layouts/mailer.html.haml (70.5ms)
  Rendered spree/user_mailer/confirmation_instructions.text.erb (3.1ms)
Connecting to database specified by database.yml
[SKYLIGHT] [1.7.2] Skylight agent enabled
No valid API key has been set, notifications will not be sent
Creating scope :deleted. Overwriting existing method Spree::Variant.deleted.
Creating scope :available. Overwriting existing method
Spree::PaymentMethod.available.
Creating scope :accessible_by. Overwriting existing method
OrderCycle.accessible_by.


How to fix ?

**Comment by sauloperez** [comment]
by the line `Connecting to database specified by database.yml` above I'd say you are seeing a 500 error page but there's no clue about it in the log. What are you exactly experiencing @bakuppus ?

**Comment by bakuppus** [comment]
Not able sign up  any email id

**Comment by sigmundpetersen** [comment]
I guess this is resolved or not relevant any more.
