### ISSUE TITLE
No valid API key has been set, notifications will not be sent

### ISSUE THREAD

**Issue by bakuppus** [openfoodfoundation/ofn-install#448]
Hi ,

While sign up, getting error

tarted POST "/user/spree_user" for 122.166.162.71 at 2019-05-30 11:30:32 +0000
Processing by UserRegistrationsController#create as JSON
  Parameters: {"spree_user"=>{"remember_me"=>0, "email"=>"bakuppus@gmail.com", "password_confirmation"=>"[FILTERED]", "password"=>"[FILTERED]"}, "return_url"=>"https://redes.smartfarmer.pt/#/login", "user_registration"=>{"spree_user"=>{"remember_me"=>0, "email"=>"bakuppus@gmail.com", "password_confirmation"=>"[FILTERED]", "password"=>"[FILTERED]"}, "return_url"=>"https://redes.smartfarmer.pt/#/login"}}
  Rendered shared/mailers/_signoff.html.haml (3.3ms)
  Rendered shared/mailers/_social_and_contact.html.haml (9.6ms)
  Rendered spree/user_mailer/confirmation_instructions.html.haml within layouts/mailer (27.6ms)
  Rendered layouts/mailer.html.haml (55.5ms)
  Rendered spree/user_mailer/confirmation_instructions.text.erb (3.1ms)
Connecting to database specified by database.yml
[SKYLIGHT] [1.7.2] Skylight agent enabled
No valid API key has been set, notifications will not be sent
Creating scope :deleted. Overwriting existing method Spree::Variant.deleted.
Creating scope :available. Overwriting existing method Spree::PaymentMethod.available.
Creating scope :accessible_by. Overwriting existing method OrderCycle.accessible_by.

Any idea ?

**Comment by sigmundpetersen** [comment]
Seems this is regarding Skylight and Skylight was removed long ago. Closing
