### ISSUE TITLE
Can't log in to site with admin password

### ISSUE THREAD

**Issue by CliffordNetwork** [openfoodfoundation/ofn-install#460]
Hi,

After runnning playbook setup I can't log in. I get this in the log ../current/log/production.log 

Completed 200 OK in 266.8ms (Views: 228.5ms | ActiveRecord: 23.8ms)
Started POST "/user/spree_user/sign_in" for 37.189.106.82 at 2019-06-20 07:53:27 +0000
Processing by Spree::UserSessionsController#create as JSON
  Parameters: {"spree_user"=>{"remember_me"=>0, "email"=>"redes@smartfarmer.pt", "password_confirmation"=>"[FILTERED]", "password"=>"[FILTERED]"}, "user_session"=>{"spree_user"=>{"remember_me"=>0, "email"=>"redes@smartfarmer.pt", "password_confirmation"=>"[FILTERED]", "password"=>"[FILTERED]"}}}
Completed 401 Unauthorized in 21.1ms (Views: 0.6ms | ActiveRecord: 4.6ms)
Started POST "/user/spree_user/sign_in" for 37.189.106.82 at 2019-06-20 07:53:33 +0000
Processing by Spree::UserSessionsController#create as JSON
  Parameters: {"spree_user"=>{"remember_me"=>0, "email"=>"redes@smartfarmer.pt", "password_confirmation"=>"[FILTERED]", "password"=>"[FILTERED]"}, "user_session"=>{"spree_user"=>{"remember_me"=>0, "email"=>"redes@smartfarmer.pt", "password_confirmation"=>"[FILTERED]", "password"=>"[FILTERED]"}}}
Completed 401 Unauthorized in 20.9ms (Views: 0.4ms | ActiveRecord: 6.1ms)

I've reviewed the output of the running book in full debug mode and I can see what the password is. Also I tried changing the password in secrets.yml but once again after reviewing output the password is the first one still and not the new one.

Thanks in advance.

**Comment by AngelHeadedHipsters** [comment]
Followup - I can now see the new password being set during setup but still can't log in.

**Comment by luisramos0** [comment]
Hi @AngelHeadedHipsters thanks for reporting the issue.

As mentioned [here](https://github.com/openfoodfoundation/ofn-install/issues/392#issuecomment-483175143) before we continue with this support process someone from your organisation needs to sign the OFN pledge: https://community.openfoodnetwork.org/t/ofn-community-pledge-v1-0-1-june-2017/948

ping @montejunto
Let us know if you need anything else from our side to do that ❤️

**Comment by sigmundpetersen** [comment]
@montejunto @CliffordNetwork is this working now?

**Comment by montejunto** [comment]
@sigmundpetersen we are through this problem and the more recent one is the one in slack. we can close this one here.

**Comment by sigmundpetersen** [comment]
That's great, thank you @montejunto !
