### ISSUE TITLE
RFC: Rewrite unicorn.rb on deploy

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/ofn-install#475]
## The current issue

We have been talking about switching directories during deploy. This can happen by deleting the old directory and moving the new build into place like in #471. Or we can rewrite the `current` symlink from the old release to the new release.  In any of those cases there is a gap between switching directories and reloading unicorn. Requests can fail during this time.

## Why there is downtime during deploy

Unicorn loads some application code into memory during startup. But most requests still read some files from the application directory, for example views. Now imagine that we renamed a view in a new release. It will lead to this scenario:

- During deploy, we switch the `current` directory to the new version of the code.
- Unicorn has not been reloaded yet.
- The in-memory Ruby code tries to find the view under the old name and fails: server error.
- We reload unicorn, the new Ruby code is loaded into the memory.
- The next request tries to find the view under the new name and succeeds.

## A possible solution

Our `unicorn.rb` file contains the path to the application. If we changed that path during each deploy, the scenario above would look a bit different:

- During deploy, we switch the `current` symlink to the new version of the code.
- We change the path in unicorn.rb to the new directory.
- Unicorn has not been reloaded yet. It still looks at the old directory.
- The in-memory Ruby code tries to find the view under the old name in the old directory: success.
- We reload unicorn, the new Ruby code is loaded into the memory.
- The next request tries to find the view under the new name in the new directory and succeeds.

## Request for comments

This is a new approach and I would like to know what your thoughts are.

If we just switched symlinks during deploy and then reloaded unicorn with Ansible, there can still be several seconds before unicorn is reloaded. Especially if the Ansible requests cross continents, for example when I deploy to France, each Ansible request takes several seconds.

I think we should try to make deploys as smooth as possible to move towards continuous delivery.

**Comment by luisramos0** [comment]
My opinion in terms of priority for this is that, with our current situation with a very slow delivery train with features waiting 2 years to be delivered, I'd say that a 10secs downtime in deployments is not so important as focusing on fixing tech debt and delivering features.

Do you have an idea how long this will take to implement?

**Comment by sauloperez** [comment]
I agree with @luisramos0 that short downtime in it's a problem now. I think most of the instances (if not all) still have a time window where no one is using them.

From a technical standpoint, IMO the complexity this will add outweighs any possible benefit. Besides, I've had zero-downtime deployments with Unicorn before without having the rewrite unicorn.rb.

**Comment by mkllnk** [comment]
Hm, I thought this is really easy and simple because we have to change only one line in a file. The implementation should be after we switched to Ansistrano which is a much bigger change. After that, it should take only an hour to properly implement this.

Anyway, I agree that it's not top priority. But I do think that zero downtime will be important when we come to continuous deployment.

@sauloperez 
> I've had zero-downtime deployments with Unicorn before without having the rewrite unicorn.rb.

Great, how did you do that?

We had that as well but we were re-using the same directory and just copied the new files in.

**Comment by sauloperez** [comment]
> Great, how did you do that?

Capistrano + Unicorn's reload

**Comment by mkllnk** [comment]
> Capistrano + Unicorn's reload

So I guess there was very little time between switching symlinks and Unicorn reload? I think that's definitely acceptable but also something to be aware of. Random errors can occur if the site is busy.

**Comment by sauloperez** [comment]
> So I guess there was very little time between switching symlinks and Unicorn reload?

Can't tell. I'd need to investigate how it's all performed but seems good enough as you say.

**Comment by mkllnk** [comment]
We don't use unicorn any more and newer versions of Rails keep view files in memory. This issue is obsolete.
