### ISSUE TITLE
Adapt spree_auth_devise inital db:seed task

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/ofn-install#476]
Bug reported in: #413 and #472.

This line in `spree_auth_devise` is causing an error on first deploy when creating the initial admin user: https://github.com/spree/spree_auth_devise/blob/23ae0704f4f9c688c7d3c5598204b2e37872b14c/db/default/users.rb#L59

It tries to send a confirmation email, but it can't because the assets aren't compiled yet. It's also unnecessary, as the user is programmatically confirmed shortly after here: https://github.com/openfoodfoundation/openfoodnetwork/blob/6f0d155508cd967939d1e8d13a66388c547156b8/db/seeds.rb#L52

We need to adapt it, with something like: `admin.skip_confirmation_notification!.save`

We're in the process of removing the dependency to `spree_auth_devise`, so maybe we should wait for those changes.

What do you think @luisramos0 ?

**Comment by luisramos0** [comment]
ah, nice one!

yes, PR #3700 will remove spree_auth_devise completely. We keep only devise.
I didnt bring that script to OFN in the PR, I have added it to the PR now :trollface:  #bug



wrt this issue, yes, we should fix this on top of 3700 (it's in test ready now).

wrt to the fix, yes, maybe skip_confirmation_notification! will do the trick
or maybe we can just disable deliveries?
```ruby
    if admin.save
      role = Spree::Role.find_or_create_by_name 'admin'
      admin.spree_roles << role
      # Disable email delivery as at this stage the app may not be setup yet and delivery may fail
      ActionMailer::Base.perform_deliveries = false
      admin.save
      ActionMailer::Base.perform_deliveries = true
      say "Done!"
    else
```

**Comment by sauloperez** [comment]
Temporally disabling sounds good to me. It's very explicit so next dev will understand why.

**Comment by lin-d-hop** [comment]
PR http://github.com/openfoodfoundation/openfoodnetwork/issues/3700 has been merged so next release should fix this.

**Comment by Matt-Yorkley** [comment]
I think we'd still need to change that line from `admin.save` to `admin.skip_confirmation_notification!.save` to avoid the error.

**Comment by sauloperez** [comment]
both work IMO

**Comment by Matt-Yorkley** [comment]
Closing as this was resolved a while ago.
