### ISSUE TITLE
UK Certs Expiring

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/ofn-install#478]
UK is getting emails informing us that our SSL certs are expiring on July 31st.

## What's the Problem
1) We cannot have our certs expiring. Making this an S2 to make sure it doesn't happen.
2) Why are these not updating automatically?

## Environment
UK Production

## Severity 
S2 until you assure me that certs wont expire in just over a week.

**Comment by lin-d-hop** [comment]
Hello,

Your certificate (or certificates) for the names listed below will expire in 10 days (on 31 Jul 19 16:28 +0000). Please make sure to renew your certificate before then, or visitors to your website will encounter errors.

We recommend renewing certificates automatically when they have a third of their
total lifetime left. For Let's Encrypt's current 90-day certificates, that means
renewing 30 days before expiration. See
https://letsencrypt.org/docs/integration-guide/ for details.

openfoodnetwork.org.uk
www.openfoodnetwork.org.uk

For any questions or support, please visit https://community.letsencrypt.org/. Unfortunately, we can't provide support by email.

For details about when we send these emails, please visit https://letsencrypt.org/docs/expiration-emails/. In particular, note that this reminder email is still sent if you've obtained a slightly different certificate by adding or removing names. If you've replaced this certificate with a newer one that covers more or fewer names than the list above, you may be able to ignore this message.

If you are receiving this email in error, unsubscribe at http://mandrillapp.com/track/unsub.php?u=30850198&id=88f9931a1b884042b3d8ef6f55f0bef6.Vl31u70Orfg0isJgKXzWnekih%2FQ%3D&r=https%3A%2F%2Fmandrillapp.com%2Funsub%3Fmd_email%3Ddev.ofnuk%2540gmail.com

You may need to update your client to the latest version in case it is still using the deprecated TLS-SNI-01 validation method. https://community.letsencrypt.org/t/february-13-2019-end-of-life-for-all-tls-sni-01-validation-support/74209

Step-by-step instructions for updating Certbot are here: https://community.letsencrypt.org/t/how-to-stop-using-tls-sni-01-with-certbot/83210

Regards,
The Let's Encrypt Team

**Comment by mkllnk** [comment]
I just checked and the server has a certificate which expires on 15 September. Those emails sent out by Lets Encrypt are not always reliable. We changed the certificate in June and added the www URL (https://github.com/openfoodfoundation/ofn-install/pull/432). For Lets Encrypt it's not the same cert and it warns about the old one.

> When You Get an Expiration Email
>
> If your certificate is already renewed, we won’t send an expiry notice. We consider a certificate to be renewed if there is a newer certificate with the exact same set of names, regardless of which account created it. If you’ve issued a new certificate that adds or removes a name relative to your old certificate, you will get expiration email about your old certificate. If you check the certificate currently running on your website, and it shows the correct date, no further action is needed.

https://letsencrypt.org/docs/expiration-emails/
