### ISSUE TITLE
Unify database access

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/ofn-install#48]
The deploy scripts have different ways of accessing the database.

``` sh
## local connection
# roles/dbserver/tasks/main.yml
psql -U postgres

## network connections
# roles/deploy/tasks/main.yml, roles/webserver/handlers/main.yml
psql -h {{ db_host }} -U {{ db_user }} -d {{ db }}

# roles/rollback/tasks/main.yml
psql -h {{ db_host }} -U {{ db_user }} {{ db }}
```

In the openfoodnetwork project:

``` sh
## local connection
# script/ci/includes.sh
psql postgres

## network connections
# script/backup.sh
pg_dump -h localhost -U openfoodweb openfoodweb_production

# script/ci/load_staging_baseline.sh, script/ci/save_staging_baseline.sh
pg_dump -h "$DB_HOST" -U "$DB_USER" "$DB"
psql -h "$DB_HOST" -U "$DB_USER" "$DB"

# script/mirror_db.sh, script/restore.sh
pg_dump -h localhost -U $DB_USER $DB_DATABASE
psql -h localhost -U ofn open_food_network_test
psql -h localhost -U ofn open_food_network_dev
```

**Which way to go?**

Postgres has several ways of authenticating users, by password, by username or by system user. If we setup a local database, we can give the user running the app password-less access to the database. We don't need a host variable and we don't need a secret password. Additionally, the login via network should not be possible, increasing security.

The downside is that we have to change all these scripts if we want to have a separate database server. If we always configure the host and a password, you just have to change the credentials to switch the db server, not the scripts making the connection.

Ideally, we would have scripts that are flexible. If no host is set, don't append the `-h` option. If no user is set, don't use the `-U` option. I would assume that there is an Ansible role doing that already. It would probably be better anyway to use a more sophisticated role for calling psql commands.

**Comment by enricostano** [comment]
This is something we're look into with @danypr92 , would be nice to even have the same authentication method in development and production. That would reduce friction and confusion even more.

**Comment by mkllnk** [comment]
I think this is outdated now. No need to fix it.
