### ISSUE TITLE
[Spike] UK downtime 07/25/2019 01:38 AM UTC - 07/25/2019 01:59 AM UTC

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/ofn-install#482]
More downtime reported by HappyApps UK, and again 20ish minutes. I'm starting to think the 20min is a pattern.

An Incident of severity 'CRITICAL' was opened for App: UK DelayedJob on 07/25/2019 01:34 AM UTC
An Incident of severity 'CRITICAL' was opened for App: UK Uptime on 07/25/2019 01:38 AM UTC

An Incident of severity 'CRITICAL' was closed for UK DelayedJob on 07/25/2019 01:55 AM UTC
An Incident of severity 'CRITICAL' was closed for UK Uptime on 07/25/2019 01:59 AM UTC

**Comment by sauloperez** [comment]
This time HappyApps reports a very long response time which it then reports as downtime

![screencapture-app-happyapps-io-checks-12624-2019-07-25-10_38_19](https://user-images.githubusercontent.com/762088/61859939-648afa80-aec9-11e9-83bd-e4d404dfb07d.png)

That check however only performs a request to `/` and matches the text `SHOPS` in it. Nginx logs confirm that long response time.

![Screenshot from 2019-07-25 10-45-08](https://user-images.githubusercontent.com/762088/61860140-c2b7dd80-aec9-11e9-8468-2b53892f6572.png)

Notice how even the client (HappyApps) closed the connection, according to the docs

> 499 Client Closed Request
> Used when the client has closed the request before the server could send a response.

**Comment by Matt-Yorkley** [comment]
Closing, as this has been thoroughly spiked.
