### ISSUE TITLE
Nicer secrets usage

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/ofn-install#487]
### Goals

- Servers can be provisioned easily without manually including secrets files per host
- Reduced or eliminated potential for user error
- Multiple servers can be provisioned at once, eg `--limit europe` without problems
- Save sysadmin time and hassle, automate the small stuff

### Possible solutions

- Option 1: Symlink files locally from `../ofn-secrets` into their respective `inventory/host_vars` folders
- Option 2: Fetch the latest secrets before each provision via an Ansible task and add them (encrypted) to their their respective `inventory/host_vars` folders

#### Vault pass

This assumes use of the script-based vault password storage trick. You get a prompt for your sudo password each time, then Ansible queries a script that pulls the password from a file owned by `root`, with 600 permissions. I'm not sure everyone else is doing that? 

I can share the details of my setup in the ofn-install Wiki.

**Comment by sauloperez** [comment]
> This assumes use of the script-based vault password storage trick. You get a prompt for your sudo password each time, then Ansible queries a script that pulls the password from a file owned by root, with 600 permissions. I'm not sure everyone else is doing that?

> I can share the details of my setup in the ofn-install Wiki.

Please, do

**Comment by Matt-Yorkley** [comment]
Done.

**Comment by Matt-Yorkley** [comment]
I wrote a wiki page for this, and now I can't find it. Was it deleted?

**Comment by sauloperez** [comment]
lol, I think that's unlikely. You can clone the wiki's repo and take a look at the git log, assuming you can't delete without a commit, even from the UI>

**Comment by Matt-Yorkley** [comment]
Closed by #522
