### ISSUE TITLE
Enable HappyApps alarms for all instances except AU

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/ofn-install#494]
## Description

We need to set up the same Unicorn and Delayed Job alarms we have for the bigger instances to all of them, including setting up the Slack notification to the #devops-alerts channel. It is the one we want to use for these critical notifications from now on.

### Why?

As a result, we could fix downtimes very quickly compared to the current situation where there has to be someone that spots the problem and tells the team and then we act. Needless to say, we could get notified much later than the issue started happening.

## Context

Stems from the retro notes around UK's downtime: https://community.openfoodnetwork.org/t/uks-downtime-retro/1700

**Comment by Matt-Yorkley** [comment]
I'm moving this to the top of the sysadmin backlog...

**Comment by pacodelaluna** [comment]
HappyApps is terminated so I guess this ticket is obsolete. FYI, in France we are now using an instance of Uptime Kuma (https://github.com/louislam/uptime-kuma) to deal with these alarms.
