### ISSUE TITLE
UK's downtime actions

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/ofn-install#497]
## Description

This epic represents the ops work required to improve the limitations we hit while dealing with the last UK's big downtime

## Context

Stems from the retro notes: https://community.openfoodnetwork.org/t/uks-downtime-retro/1700

**Comment by daniellemoorhead** [comment]
Why doesn't AU get HappyApps alarms? I thought we were standardising all instances to be the same?

**Comment by sauloperez** [comment]
Taken from https://community.openfoodnetwork.org/t/uks-downtime-retro/1700

> If I understand you correctly, @sauloperez, you are suggesting that we set up HappyApps and Datadog for Aus. I have no problem with that. I didn’t see the need because Wormly works quite well for us and has indefinite data retention.

As far as I know, AU uses Wormly for the same we use HappyApps plus it provides some metrics about the server like memory and CPU usage, etc. Am I right @mkllnk ?

**Comment by mkllnk** [comment]
Yes. Wormly seemed to provide more to us then HappyApps. But I'm happy to review that again. I think we should set up HappyApps for AU as well.

**Comment by Matt-Yorkley** [comment]
Closing this epic as it's not super useful. There's one remaining issue open, it can stay in the sysadmin pipe.
