### ISSUE TITLE
Integrate use of Lets Encrypt for simpler SSL cert management

### ISSUE THREAD

**Issue by pmackay** [openfoodfoundation/ofn-install#50]
See http://community.openfoodnetwork.org/t/open-source-free-ssl/466/3 for more info on how it can be done.

**Comment by pmackay** [comment]
Now supported on master.

**Comment by lin-d-hop** [comment]
Reopened as adding to epic around Paul's recent work... as he is requesting testing.

**Comment by enricostano** [comment]
Is there any work left on this? The only thing I still miss is the post hook to reload nginx after the renewal. But probably we should create a specific issue for that.

I added a comment about this on a open issue in Ansbile role https://github.com/geerlingguy/ansible-role-certbot/issues/26#issuecomment-306031264

**Comment by elf-pavlik** [comment]
This issue seems ready to close, if not right away then latest after merging #124

**Comment by myriamboure** [comment]
@pacodelaluna is there any link here to the issue we had with the last Let'sEncrypt renewal?

**Comment by pacodelaluna** [comment]
The issue was related to permission on the script I had set up, nothing related to the code actually.

**Comment by elf-pavlik** [comment]
I think with #124 merged we can close this issue.
