### ISSUE TITLE
Central Logrotate management

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/ofn-install#503]
At some point we should probably create a role for `logrotate` and manage all log rotation in a clear and centralised way.

Logrotate can be configured to use the `conf.d` pattern :heart:, so we can just define a number of rotation rules in a role and write them to `/etc/logrotate.d`.

And there's a role in `ansible-galaxy` that handles it nicely: https://galaxy.ansible.com/arillso/logrotate

**Comment by mkllnk** [comment]
This is a duplicate of https://github.com/openfoodfoundation/ofn-install/issues/96.
