### ISSUE TITLE
Configure memcached to use 128 MB max memory and 6 threads

### ISSUE THREAD

**Issue by kristinalim** [openfoodfoundation/ofn-install#509]
## Description

For UK, we made the following changes to memcached config in `/etc/memcached.conf` manually:

- Increased the max memory from the default of 64 MB to 128 MB (existing line in config file)
- Increase the number of threads from the default of 4 to 6 (new line in config file)

Currently, memcached config is not managed through `ofn-install`. This should be done, and the other instances should use this configuration too.

## Why?

See Slack thread [here](https://app.slack.com/client/T02G54U79/CLSDUBV8A/thread/CLSDUBV8A-1567695797.125700):

1. We were using 64 MB max memory - This seems low, and we are probably exceeding this in some instances. (I did not check actual usage, actually.)
2. We were using default of 4 threads - At time of check in UK, we had 6 incoming memcached connections (`netstat -n | grep 11211`).

Also another cause for concern, but not related to this PR: There are some interesting results for "memcached cpu": https://www.google.com.ph/search?q=memcached+cpu

## Context

#497

**Comment by Matt-Yorkley** [comment]
Do we think 128 MB is good? Shall we go straight to 256?

**Comment by kristinalim** [comment]
If the servers can afford it, I think 256 MB sounds good @Matt-Yorkley. :+1:

**Comment by lin-d-hop** [comment]
I would vote for more! Maybe check Aus first as their mem load is high, but UK, France, Katuma are barely touching the sides of the available mem.

**Comment by sauloperez** [comment]
cannot claim that for Katuma :trollface: we really need that server upgrade. I don't want to start adding conditionals because of our limited server specs :see_no_evil:
