### ISSUE TITLE
Zapier integration for USA Server

### ISSUE THREAD

**Issue by lauriewayne** [openfoodfoundation/ofn-install#513]
Set up USA server (and maybe ofn-install too?) so that users can connect to the database for reporting using Zapier. This issue is a cousin to #403  and maybe #400?

**Comment by Matt-Yorkley** [comment]
I'll get this done today :+1:

**Comment by sauloperez** [comment]
This is done but just needs to be provisioned against the production server to take effect. Could you handle it @Matt-Yorkley ? I would just provision all servers before waiting for the next release.
