### ISSUE TITLE
Allow provisiong more than a server at the same time

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/ofn-install#519]
## What? Why?

This is a known old thing but it came up again in https://github.com/openfoodfoundation/ofn-install/pull/518.

While we are able to deploy a bunch of servers together, we can't do the same when provisioning resulting in a waste of time in manual work, that can always lead to errors.

This is because currently, due the structure of the `ofn-secrets` repo the secrets file needs to be provided as follows for each individual server.

```
ansible-playbook playbooks/provision.yml --limit=es-staging -e "@../ofn-secrets/es-staging/secrets.yml"
```

Otherwise, there is no way to tell Ansible which one of the matching variables in the various `secrets.yml` needs to end up in each server. Aka. `fr-prod` might end up with the UK's Stripe API key.

## Potential solution

@danypr92 suggests we follow Coopdevs' convention of having the secrets file next to the config.yml of each host_var. See https://gitlab.com/coopdevs/odoo-test-provisioning/tree/master/inventory/host_vars/odoo-test.coopdevs.org

This is almost the same we already have but simpler. Given the folder structure maps one to one, instead of a separate repo we merge them into a single one, which is always simpler to manage. for instance: do you always pull changes in `ofn-secrets` when running the provisioning against a server?

**Comment by Matt-Yorkley** [comment]
Do you mean to keep secrets in the public repo?

**Comment by sauloperez** [comment]
yes, but encrypted, of course.

**Comment by Matt-Yorkley** [comment]
We discussed this option previously and I think @mkllnk was against it.

It would definitely make secrets files easier to manage.

**Comment by sauloperez** [comment]
why is that @mkllnk ? I don't remember. At Coopdevs we successfully use it with our client projects. I like it because it's quick and easy solution.

**Comment by sigmundpetersen** [comment]
Maybe something here https://community.openfoodnetwork.org/t/sharing-secrets-yml-for-ofn-install/1404/4

**Comment by mkllnk** [comment]
I have no objection to multi-server provisioning. That would be ace. I'm just against a public secrets repo. Encryption technology is changing all the time. What's public now can possibly be cracked in five years which means that we need to change all secrets. That would be a pain.

Unless you have some automation to update all secrets regularly without manually creating new API keys for Google, Bugsnag etc and without losing encrypted cookie data... then we can keep up to date with encryption technology and old versions of ofn-secrets are useless. But that sounds very difficult to me, compared to a private repo.

**Comment by sauloperez** [comment]
Do you have a solution that allows for both: multi-server provisioning + plus stronger security levels? If not, I'd go with this.

Another reason, https://github.com/openfoodfoundation/ofn-install/issues/492 is broken because the `datadog_key` is not provided. If we don't implement this, it'll mean that we lose the ability to deploy multiple servers as well.
