### ISSUE TITLE
port 22 not enabled

### ISSUE THREAD

**Issue by MikeiLL** [openfoodfoundation/ofn-install#52]
port 22 isn't enabled on the VPS we're using, so in the `staging` file I had to add the `ansible_port` variable, as specified [here](http://docs.ansible.com/ansible/intro_inventory.html). Possibly we will want to note that in the docs.

**Comment by pmackay** [comment]
What VPS are you using, out of curiosity?

**Comment by MikeiLL** [comment]
It's a small company. I like the guys a lot so far. SVWH.HOST. Ben and Eric. (Not to be confused with swvh.net who were their old partenrs and apparently still friends...)

**Comment by enricostano** [comment]
@MikeiLL I'm closing this issue since it has been too long.

Please feel free to ping me if you want to work on it. Thanks!
