### ISSUE TITLE
[Spike] Automerge Transifex's PR when passing CI

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/ofn-install#520]
## What?

It's useless to have a dev merging this PR when it passed CI. I suggest we investigate https://github.com/marketplace/auto-merge and let a bot do it for us.

There have to be other options out there that fit our needs such as other GH bots or https://github.com/jonathanong/gh-automerge.

## Why?

This is yet another one of the tiny things we have to be on top of. Computers should do it for us so we can focus on providing value to our users.

**Comment by sauloperez** [comment]
Looks like we could have https://github.com/marketplace/issue-labeler-bot to add a `transifex` label and then https://github.com/marketplace/auto-merge merge it based on that label.

Also, https://doc.mergify.io/getting-started.html looks very interesting and might be enough to the job.

**Comment by sigmundpetersen** [comment]
We don't have Transifex PR's anymore. Closing
