### ISSUE TITLE
Installs Trusty/64 But no provisioning

### ISSUE THREAD

**Issue by MikeiLL** [openfoodfoundation/ofn-install#53]
I destroyed the previous dev server, checked out _infrastructure_ and ran `vagrant up` which only does:

`Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'ubuntu/trusty64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: Setting the name of the VM: ofn_deployment_default_1464238100539_37004
==> default: Clearing any previously set forwarded ports...
==> default: Fixed port collision for 22 => 2222. Now on port 2200.
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
    default: Adapter 3: hostonly
    default: Adapter 4: hostonly
    default: Adapter 5: hostonly
==> default: Forwarding ports...
    default: 80 (guest) => 8080 (host) (adapter 1)
    default: 22 (guest) => 2200 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2200
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: 
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default: 
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default: 
    default: Guest Additions Version: 4.3.36
    default: VirtualBox Version: 5.0
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /vagrant => /Users/mikekilmer/Documents/Clients/UsFoodCoop/OpenFoodNetwork/ofn_deployment`

Running vagrant up --debug produced a [mind-numbing amount of output](https://gist.github.com/MikeiLL/2c844c1784062586cbb8e70326ad8b78).

Vagrant provision doesn't seem to be doing anything. I looked through the docs again. I think I'm missing a configuration. Vars.yml is the same as my old one. Am I missing a configuration somewhere? Because it seems like none of the playbooks are being run.

**Comment by pmackay** [comment]
You've jumped ahead very fast! Here's a bit more context:

I've been updating the ofn_deployment wiki on a separate branch, because the infrastructure branch is not merged yet (my main argument for keeping docs and scripts together). So you could check that out **but** its a work in progress.

One main change is that having created a vagrant box, the ansible commands can be run just as ansible, rather than driven via the provisioning process of Vagrant, e.g.:

`ansible-playbook -i inventory/dev playbooks/install.yml`

I need to do some testing on this though to verify against recent changes.

**Comment by MikeiLL** [comment]
OK. I'll go back to previous Vagrant and (hopefully easily) re-provision a dev server until further notice. At the moment `playbooks/install.yml` doesn't exist as far as I can see.

**Comment by pmackay** [comment]
Damn, sorry, its `playbooks/provision.yml` for initial setup.

**Comment by MikeiLL** [comment]
Once I had (re) run `ansible-galaxy install zzet.rbenv` and `ansible-galaxy install mortik.nginx-rails` and getting this error:

`ESTABLISH SSH CONNECTION FOR USER: None
<192.168.50.4> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/Users/mikekilmer/.ansible/cp/ansible-ssh-%h-%p-%r 192.168.50.4 '/bin/sh -c '"'"'( umask 22 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1466880819.77-170801877427289 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1466880819.77-170801877427289 `" )'"'"''
fatal: [local_vagrant]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh.", "unreachable": true}`

**Comment by pmackay** [comment]
>The ofn-install readme now seems to be recommending installing without the install script.

Can you clarify what you mean?

**Comment by MikeiLL** [comment]
Maybe I had just misunderstood, but I thought the previous version : ofn-deployment was intended to also deploy to a local VM. Now https://github.com/openfoodfoundation/ofn-install/wiki states differently. I personally like the idea of being able to quickly provision a dev server - partly because there are a lot of different projects I work on at different times and have already installed OFN on a VM two or three times. The other folks on our dev team here are also new to Rails and in similar positions.

**Comment by enricostano** [comment]
@MikeiLL I'm closing this issue since it has been too long and we still don't have a clear plan on Vagrant.

Please feel free to ping me if you want to work on it. Thanks!
