### ISSUE TITLE
Change Datadog's APM from UK production to FR production

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/ofn-install#544]
## Description

As per the discussion in https://community.openfoodnetwork.org/t/data-insights-in-ofn/1693/15?u=sauloperez, we need to move Datadog's APM from UK production to FR production.

Unfortunately, we're only paying for a server and we need to know how data streaming impacts the server.

**Comment by Matt-Yorkley** [comment]
@sauloperez maybe we can do this switch today?
