### ISSUE TITLE
Add Google Maps API Key for Belgium

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/ofn-install#547]
## Description
As described here : https://github.com/openfoodfoundation/ofn-install/wiki/Google-Maps

A dev need to add OFN Belgium Google Map API key to secrets file.

Théo & Rachel have the API key (not sure I can share the hey here in the issue?)

This would help Belgium to fix all issues with current map.

**Comment by luisramos0** [comment]
I am out of context her but the api key is already in the secrets file for BE:
starts with google_maps_api_key: AIzaSyCfBKP3e...

(please dont share the full key in the issue)

**Comment by sigmundpetersen** [comment]
There was a change in Google at one point that you had to enable more of the API's and create a billing account behind the API's. If I remember correctly a new key was created when I had to do this so the secrets/config had to be updated with the new key.

I'm not 100% sure so I would first make sure that all the steps in the mentioned wiki article are performed.

**Comment by RachL** [comment]
@sigmundpetersen @luisramos0 yes I have made al the steps with Theo following the wiki :+1: He just need to add a credit card (actually to find a creadit card at Oxfam :D ). But that was step 6, and this issue is step 5 :-)

**Comment by RachL** [comment]
The new API key that I have is different than the one you shared Luis, so I guess we are good to go :+1:

**Comment by luisramos0** [comment]
ok :+1:
I'll be doing the next release so you can send me the new key in a slack PM

**Comment by Kim152** [comment]
@Theo

**Comment by TheoGallez** [comment]
Hey, it become quite complicated to support OFN BE with the API problem. I stayed with kimi more than one hour to try to understand where to put the key... How can I support you to finalise the Google API? Thanks. ;-)

**Comment by TheoGallez** [comment]
So it will be ready on Thuesday ? Thanks

**Comment by luisramos0** [comment]
Hi @TheoGallez 
actually I can provision BE on Monday. I'll let you know when the key is there.

**Comment by luisramos0** [comment]
the key has been updated in the server.
it will reach github when this PR is merged:
https://github.com/openfoodfoundation/ofn-secrets/pull/22

**Comment by TheoGallez** [comment]
Luis,

Thank you so much for your work ! ☺

De : Luis Ramos <notifications@github.com>
Envoyé : mardi 19 novembre 2019 13:28
À : openfoodfoundation/ofn-install <ofn-install@noreply.github.com>
Cc : openfoodnetwork <openfoodnetwork@mdmoxfam.be>; Mention <mention@noreply.github.com>
Objet : Re: [openfoodfoundation/ofn-install] Add Google Maps API Key for Belgium (#547)


the key has been updated in the server.
it will reach github when this PR is merged:
openfoodfoundation/ofn-secrets#22<https://github.com/openfoodfoundation/ofn-secrets/pull/22>
