### ISSUE TITLE
Support custom backup config

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/ofn-install#555]
## Description

The Australian production server has an AWS S3 bucket for assets and one for backups. The backups bucket is in a different region which is currently not supported by ofn-install. The configuration assumes that the backups bucket is similar to the assets bucket and uses the same keys as well.

I installed a hack on Aus production to deal with this now.

```crontab
40 2 * * * cp /home/openfoodnetwork/db2fog.rb /home/openfoodnetwork/apps/openfoodnetwork/current/config/initializers/
55 3,7,11,15,19,23 * * * cp /home/openfoodnetwork/db2fog.rb /home/openfoodnetwork/apps/openfoodnetwork/current/config/initializers/
```

```rb
# /home/openfoodnetwork/db2fog.rb
DB2Fog.config = {
  :aws_access_key_id     => '...',
  :aws_secret_access_key => '...',
  :directory             => "ofn-aus-production-backup",
  :provider              => 'AWS',
  :region                => 'ap-southeast-2'
}
```

## Expected Behavior

Backups can be configured independently from assets.

## Actual Behaviour

The backup options are very limited.

## Severity

I'd say s3 because there is a workaround.

## Possible Fix

The db2fog gem has many configuration options and supports many storage providers out of the box. The easiest would be to define the config of the db2fog initializer within ofn-secrets.

The config is represented as hash. My best idea so far (not great), would be to define the hash in native Ansible YAML. We then convert it into JSON to store it in a variable in the application config. And the initializer reads that variable and tries to use that parsed config.

**Comment by mkllnk** [comment]
@luisramos0 After the holiday break I thought that I lost my previous work on this during my computer re-install and described my alternative approach here. I didn't see my own PR: https://github.com/openfoodfoundation/openfoodnetwork/pull/4618

I'm not sure what's easier, actually. If we go ahead with https://github.com/openfoodfoundation/openfoodnetwork/pull/4618, we need to create an additional symlink to the config file every time we deploy. And we need a way to deploy that config file. The alternative here would store the config in a string instead. What do you think is easier and more robust?

@Matt-Yorkley Do you have an opinion about this?

**Comment by Matt-Yorkley** [comment]
I think we can just define some new Ansible variables in ofn-install, and each instance can add configs for backups and assets in their `inventory/host_vars` files as normal. Does that sound good? I'll take a look at making a quick PR today.

**Comment by Matt-Yorkley** [comment]
@mkllnk I've added a PR here: https://github.com/openfoodfoundation/openfoodnetwork/pull/4653
And a corresponding one in ofn-install here: https://github.com/openfoodfoundation/ofn-install/pull/556

Now we can just define `s3_backups_region` in `secrets.yml`. 

What do you think?

**Comment by mkllnk** [comment]
It solves only the immediate region problem. But ideally I would like to use different access keys for assets and backups as well. And what if somebody would like to use something different to Amazon for backups? I think that we are replicating a configuration interface here. It would be much simpler to pass on any custom configuration and suddenly we can do everything with db2fog without changing the code.

**Comment by Matt-Yorkley** [comment]
That sounds like two "nice-to-have" features that we don't currently need, and an improvement that would take a lot more time (rewriting more ofn-install code and updating all secrets files)? I agree it would be a nice improvement, but maybe it's not priority? 

We would also need to make it work with existing configs, as most instances use the same keys. So we still have to manage those overlapping defaults..?
