### ISSUE TITLE
Replace Australian production server

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/ofn-install#565]
## Description

A still unknown bug caused corrupted files on the Australian production server `prod2.openfoodnetwork.org.au`. Even commands like `apt` won't run without repair. Fortunately, the OFN application seems to be running. Deploying newer version could be risky though.

Since the extent of corrupt files is unknown, the safest option is to provision a new machine and transfer our application data there.

## Work that has been done already

The server was hosting the Australian Wordpress site but I moved it to a shared web host now.

I created a new virtual server. Unfortunately, our hosting provider only offers Ubuntu 18 now. Given that we would like to migrate to Ubuntu 18 anyway, this is a good opportunity to finish https://github.com/openfoodfoundation/ofn-install/issues/342.

I started the provisioning which means that the global admin team as access to the new server: `prod3.openfoodnetwork.org.au`.

I ran into several problems. Some of them I resolved on a new branch: https://github.com/openfoodfoundation/ofn-install/compare/master...mkllnk:au-prod3

## Work still to be done

- #342.
- I found that the brotli module doesn't recover when `configure` fails. That step is only executed when `Makefile` doesn't exist but a failing `configure` still creates a Makefile. (Create tech-debt issue?)
- Finish the provisioning.
- Deploy.
- [ ] Migrate data from prod2 to prod3.
- [ ] Point `openfoodnetwork.org.au` to prod3.

**Comment by Matt-Yorkley** [comment]
I think the new Italian instance is running successfully on 18...

**Comment by Matt-Yorkley** [comment]
@mkllnk in Travis the `setup` and `provision` playbooks run without any issues on Ubuntu 18, and I just ran them against a Vagrant box with a fresh Ubuntu 18 image, and had no problems.

Did the `prod3` server come with some pre-installed packages, added configs, or custom package sources? Or was it a "clean" Ubuntu 18 image?

**Comment by Matt-Yorkley** [comment]
Okay, it's provisioned and deployed. You can check it at https://prod3.openfoodnetwork.org.au

The certificate on the server is valid for **all** of these three domains:
- `openfoodnetwork.org.au`
- `www.openfoodnetwork.org.au`
- `prod3.openfoodnetwork.org.au`

The assets still need to be migrated (I'll do that tomorrow, and redeploy) and some downtime needs to be announced for the final migration/switch (it should be fairly short though). We have playbooks to automate both of those tasks :tada:

**Comment by mkllnk** [comment]
> Did the prod3 server come with some pre-installed packages, added configs, or custom package sources? Or was it a "clean" Ubuntu 18 image?

Rimu hosting installs images with some pre-installed packages like apache. I had to uninstall that one to get nginx running. There might be more, like a standard email setup.

> it's provisioned and deployed.

You are awesome! :tada: I'll discuss that with the Australian team.

**Comment by Matt-Yorkley** [comment]
> Rimu hosting installs images with some pre-installed packages like apache. I had to uninstall that one to get nginx running. There might be more, like a standard email setup.

OK. It looks like we don't need to fix anything in the playbooks if they run against a clean Ubuntu 18 image.

**Comment by Matt-Yorkley** [comment]
@mkllnk  Assets have been migrated :heavy_check_mark: 

I'll deploy `prod3` again now so the symlinking and precompiling is re-done. 

We could also do an initial (provisional) database migration now, and check to see if everything looks OK on `prod3`. We'll obviously have to re-migrate it later during the switchover so it's up to date, but it's nice to check it first with the data in place. What do you think?

I'm not sure what other bits you've applied in terms of custom code on `prod2` (like the backups bucket hack?), so I'll leave that part to you...

**Comment by mkllnk** [comment]
> We could also do an initial (provisional) database migration now

What were you thinking of?

We can't just copy the database because it would start to run on real data and trigger actions on that. For example subscriptions processed twice (prod2 and prod3).

**Comment by Matt-Yorkley** [comment]
Ah, I forgot about subs. That's a good point.

**Comment by mkllnk** [comment]
A little summary of the migration:

- The service was effectively down for three hours from 4:43 till 7:43 Australian time.
- After the move was complete, product images were not showing until 9am.
- Links in any email send out before 9.30am were broken.

### Downtime

Three hours is a long time. If I remember correctly, the tools download the data to the dev's computer and than upload them to the new server. I think we should transfer the data between servers to speed this up.

### Images

I found the following configuration:
![Screenshot from 2020-02-25 09-01-55](https://user-images.githubusercontent.com/3524483/75198642-41089500-57b5-11ea-8ce6-c58e6b3ac1db.png)

@Matt-Yorkley Did you enter those details? The image settings should have copied with the database and the correct image path for the Australian bucket is `/public/images/spree/products/:id/:style/:basename.:extension`. Unicorn needed restarting after changing this.

### Email links

The general settings were set to Spree defaults:
![Screenshot from 2020-02-25 09-01-02](https://user-images.githubusercontent.com/3524483/75198770-80cf7c80-57b5-11ea-9d6a-cf22f30bfa94.png)

@Matt-Yorkley Do you know how that happened?

I entered the correct data `Open Food Network Australia` and `openfoodnetwork.org.au`. Then I restarted unicorn and delayed-job for these settings to take effect.

**Comment by Matt-Yorkley** [comment]
I think it probably just needed the `unicorn` restart. I've added some notes in the issue: #575
