### ISSUE TITLE
SSL issue for https://openfoodfrance.org

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/ofn-install#570]
## Description

There is an SSL issue when I access https://openfoodfrance.org. The www domain name is fine.

Can we redirect to www.  ?

Or find a way to keep it up to date. Luis & Kristina worked on i t recently: https://github.com/openfoodfoundation/ofn-install/pull/560
but the problem is back.

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/6525576/74919777-65d2c600-53cb-11ea-93a4-cc8cbafe88dd.png)

## Severity
bug-s2: a non-critical feature is broken, no workaround

**Comment by Matt-Yorkley** [comment]
Fixed :+1:
