### ISSUE TITLE
localize pg encoding script

### ISSUE THREAD

**Issue by orangeman** [openfoodfoundation/ofn-install#58]
The task  "_copy fix_pg_encoding PG script_" failed with a german ubuntu

This change made it work https://github.com/openfoodfoundation/ofn-install/commit/6874820ef29aea661b79b3de1bf2a1ac28bd0f89

The file roles/dbserver/files/fix_pg_encoding.sql is a static file
Maybe it could become a template dynamically adding locale?

**Comment by Matt-Yorkley** [comment]
Closing, as I think this is handled now.
