### ISSUE TITLE
Upgrades to Provisioning and Deployment Scripts

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/ofn-install#59]
Capturing the updates that are ongoing to the deployment scripts.

Now a chunk of work has been completed and changes are live at https://www.openfoodnetwork.co.uk/ (note this is not the main uk site, .co.uk instead of .org.uk).

This work is ready for a round of testing. In particular we need to test functionality around images (uploading, retrieving, replacing). maps (checking new enterprises appear as they should), payments to external payment gateways (paypal). This will require ensuring that Paypal sandbox is properly set up on this 'staging' server.

**Comment by lin-d-hop** [comment]
@OliverUK Can you take a look at testing this for us? Bit of a biggy so happy to talk it through after you've had a wee look

**Comment by OliverUK** [comment]
I started by registering a Producer (Oliver's test shop 1). The signup process asks for a "state" with a drop-down showing meaningless letter.

![screen shot 2016-11-30 at 13 17 52](https://cloud.githubusercontent.com/assets/17590921/20754218/d862a290-b701-11e6-8ed0-f68de45a0640.png)

On trying to upload a logo I chose a 2.6MB image, which resulted in the following screen. I coud go past it but there was no way of knowing if it had done the upload even after waiting for 5 minutes.
![screen shot 2016-11-30 at 13 21 29](https://cloud.githubusercontent.com/assets/17590921/20754272/16328b3a-b702-11e6-986a-d40a1be38ad8.png)
The image did appear in the enterprise management screens though.
![screen shot 2016-11-30 at 13 28 51](https://cloud.githubusercontent.com/assets/17590921/20754312/43650f56-b702-11e6-83ae-7e9bf2177e55.png)

I then set a shipping and payment method and a few other bids. Upon checking the map, a map briefly flashes up but is then replaced by
![screen shot 2016-11-30 at 13 33 09](https://cloud.githubusercontent.com/assets/17590921/20754353/73584a20-b702-11e6-8860-fa58397a8d11.png)
This happened in Firefox and Safari.

The enterprise does not appear in the list of producers. 

I set up two products and then went to create a new order cycle. I got the following:
![screen shot 2016-11-30 at 13 52 15](https://cloud.githubusercontent.com/assets/17590921/20754774/696d4a40-b704-11e6-8f8b-9b882013da38.png)
"None of your enterprises have permission to coordinate an order cycle."

**Comment by OliverUK** [comment]
Logged out and logged back in as Stroudco manager using my gmx email account. Gave producer "Oliver Muller" two new products and added him to a new Stroudco order cycle. I like how the fields now expand so I can actually read the fees properly. 
![screen shot 2016-11-30 at 14 08 57](https://cloud.githubusercontent.com/assets/17590921/20755371/a7b67dc4-b706-11e6-9aaf-b60fd831e1b4.png)

I saved the OC and looked at the shop front. No image appears with a product if different images are given to different variants (known bug); no image appears if only one image is used but it's allocated to a variant; changing the image settings to just one image and allocating it to "all" does not now make the image appear in the shop front either.
![screen shot 2016-11-30 at 14 14 48](https://cloud.githubusercontent.com/assets/17590921/20755670/bbf7436c-b707-11e6-8026-b4b98a289f30.png)
Added another product to the OC with one image and one variant; 99 in stock; will not appear in shop front. 
![screen shot 2016-11-30 at 14 24 52](https://cloud.githubusercontent.com/assets/17590921/20755959/e102209a-b708-11e6-9fed-3e369dcd7ef8.png)
![screen shot 2016-11-30 at 14 25 24](https://cloud.githubusercontent.com/assets/17590921/20755966/e79f7e3e-b708-11e6-9209-771e8415ea38.png)

**Comment by OliverUK** [comment]
Stroudco now has permission to add Oliver's Test Shop to its order cycle but can't be cause he is "unconfirmed"; no confirmation emails come through, however. 
![screen shot 2016-11-30 at 14 35 35](https://cloud.githubusercontent.com/assets/17590921/20756362/516b5cd8-b70a-11e6-881d-ce45a4d4a33e.png)

Added Biovergel to the OC and made 3 products "to order" for stock. 
![screen shot 2016-11-30 at 14 41 23](https://cloud.githubusercontent.com/assets/17590921/20756575/19a20468-b70b-11e6-8e29-76a1361e572c.png)
![screen shot 2016-11-30 at 14 42 04](https://cloud.githubusercontent.com/assets/17590921/20756598/30b85576-b70b-11e6-9336-eb4cb69e3470.png)

Still nothing appears in the shopfront. The only product showing is the clementines as above.

**Comment by lin-d-hop** [comment]
@pmackay can you update @OliverUK email status on the updated server? @OliverUK emails run on a separate job and won't come through until Paul has updated this... so it won't be work testing  more until you hear from Paul that emails are working.

**Comment by pmackay** [comment]
@lin-d-hop I've had to pause a bit on further testing, cos there are a bunch of issues and it will take time to investigate. Will aim to action as soon as possible and will update then.

**Comment by lin-d-hop** [comment]
@pmackay see #1214... existing issue that @OliverUK picked up.

**Comment by pmackay** [comment]
See #1186 on 3 letter issue.
