### ISSUE TITLE
Zapier integration for OFN-CAN server

### ISSUE THREAD

**Issue by tschumilas** [openfoodfoundation/ofn-install#605]
## Description
Set up Canada server so that users can connect to the database for reporting using Zapier.  This issue is replicating #513 that was done for the USA server

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by Matt-Yorkley** [comment]
I'll do this now and PM the Zapier connection details :+1:

**Comment by Matt-Yorkley** [comment]
Provisioned and set up :heavy_check_mark: 
Login details sent :heavy_check_mark: 
Should be ready to go :heavy_check_mark:
