### ISSUE TITLE
Add, Italian, German and Dutch to the list of languages for FR prod

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/ofn-install#606]
Our customer base start to look more European! I have had requests for being able to display the platform in German and Dutch.

Now that OFN Italy has launched I also need an it_fr file and not display the italian content.

**Comment by RachL** [comment]
I didn't get specific request, but I'm wondering about adding Spanish (and maybe Catalan). We have a lot of Spanish producers and a large group is starting to use the platform in Pays Basque. I wonder if this wouldn't help some collaboration between instances as well. @sauloperez would it be useful to you to have OFF translated in Spanish?
The only dark side is the maintenance of the language and copy/pasting what translator are doing in other countries...

**Comment by sauloperez** [comment]
> We have a lot of Spanish producers and a large group is starting to use the platform in Pays Basque. I wonder if this wouldn't help some collaboration between instances as well

Agree. It feels like both instances need to sit together. Is there a need that both instances need to fulfill?

> @sauloperez would it be useful to you to have OFF translated in Spanish?

I would have to check with Eugeni but I haven't hear anyone asking for that.

> The only dark side is the maintenance of the language and copy/pasting what translators are doing in other countries...

I wouldn't maintain a per-country translation of the same language (I don't know if that is what you meant). If you guys need Spanish, just use the one we maintain. The same should apply for German, for instance.

**Comment by RachL** [comment]
@sauloperez I think we need to maintain a per-country translation, otherwise it breaks our main menu.

**Comment by sauloperez** [comment]
Oh gosh :see_no_evil: then, IMO we need to reconsider how to deal with the menu. Having to maintain multiple translations just because of it seems like a big waste of resources to me.

**Comment by sigmundpetersen** [comment]
There used to be other "instance specific strings" that one could customize through translation as well. I don't know if this is still the case, but if it is there's some more work to be done before we can use the same language file across instances.

**Comment by luisramos0** [comment]
I think we have been through this discussion already, it's not good and we should fix it but it works.
I dont think this is a priority. I mean, look at all the things we have to get done...

**Comment by Matt-Yorkley** [comment]
Agreed it needs to be fixed, and we will end up creating lots of mess until then.

**Comment by luisramos0** [comment]
I am not sure everyone is aware of the process in transifex, it's very easy to extract one language and upload it to another one thus creating the duplicate that can be customized (adapt the menu).
What you can do afterwards, lets say 2 months later when translations will need an update, is to repeat the process: extract original language from transifex, upload to copied language and adapt the menu. This takes 2 minutes if you know how to do it in transifex.

**Comment by sauloperez** [comment]
fair enough. I didn't know this possibility existed.

**Comment by sauloperez** [comment]
yep :point_down: 

https://github.com/openfoodfoundation/ofn-install/blob/27dc3055e2acd98ed3cc7c0f3313b9e150804fdd/inventory/group_vars/fr.yml#L8

**Comment by RachL** [comment]
ok so I updated the issue title and description: we need to change that as well.

**Comment by luisramos0** [comment]
:+1: 
it will become
 available_locales: fr,it_FR,en_FR,de_FR,nl_FR

we need to clone the 3 files in transifex:
it_FR,de_FR,nl_FR  from it, de_DE and nl_BE
and put the FR menu in them.

**Comment by mkllnk** [comment]
That is a lot of additional work to maintain these locales. We need a better way to manage instance-specific text so that we can use locales in multiple instances.

**Comment by luisramos0** [comment]
Did you see my comment above Maikel? This can be done in 5 minutes in transifex:
https://github.com/openfoodfoundation/ofn-install/issues/606#issuecomment-621367341

**Comment by mkllnk** [comment]
Is it really just the menu items? What about pricing info?

And what happens with all the untranslated strings in the meantime? They will fall back to the default language which is French. Not great for German users.

**Comment by RachL** [comment]
Yeah there are a lot of other strings. But the main menu is the biggest one for non-enterprise users.

The alternative is that I follow on the flow how other translators are doing it. It's doable, the problem is that some languages are translated more slowly. German has currently 40 strings untranslated.

I'm pinging @tschumilas  in this conversation because I'm not sure she is downloading my french translations or updating them on the go...

**Comment by tschumilas** [comment]
Thanks @RachL  -  yes,  I"m really behind in updating our French-Canadian file.   I have been just copying and pasting strings from France,  waiting on a francophone here to see if there are any Can-French specific strings to change.   (We are getting desperate to be able to offer support in French too - and its still so unfortunate that none of our current team speaks French -  and really embarassing.)

**Comment by RachL** [comment]
I created https://github.com/openfoodfoundation/ofn-install/issues/796 I don't think it's maintainable to have several languages on OFN prod currently. So keeping it at minimum is the best. Closing
