### ISSUE TITLE
Improve custom asset handling

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/ofn-install#640]
Related to asset and precompilation issues outlined here: https://github.com/openfoodfoundation/openfoodnetwork/issues/5622#issuecomment-645891351

We've got a bit of a mess with assets. This is mostly due to the way move custom (instance-specific) assets into the build during deploy. These can be things like: Terms and Conditions PDFs, custom logos, etc, and they get symlinked into the build in a certain way. The result is that we end up with a mess of old precompiled assets that are release-specific sitting around in shared directories that should **not** contain any release-specific files.

The relevant task is here:

https://github.com/openfoodfoundation/ofn-install/blob/31833e59f76170b4fa2fb6e6acf65b77034c7521/roles/deploy/tasks/deploy.yml#L14-L29

I think we should probably remove the first item in that list, and not symlink from `{{ assets_path }}` to `{{ build_path }}/public/assets`.

The tricky bit is this: it looks like some instances have added files in the `assets_path` directory and some haven't. So we would need to have a look on each instance, figure out what needs to be there and what doesn't, move those assets into somewhere more sensible (I think `system_path` is a good choice in this case as it already seems to contain custom assets like logos uploaded via `ContentConfiguration`) and then update the instance's links to those assets, for example the config value for the path to the Terms and Conditions PDF. 

I don't think there's an easy way to automate this bit, but it probably won't take too long. I suspect newer instances might have their custom assets in sensible locations already, but we'll have to look.

**Comment by Matt-Yorkley** [comment]
> @sauloperez ...is there something we need to do to undo the mess in ofn-install?

This :point_up:

**Comment by Matt-Yorkley** [comment]
Actually there might be some more cleanup we can do here: it looks like the only images in `images_path` (which is `/shared/images` on the server) are the taxons icons, which I think we're removing from the main repo...

:fire::fire:

**Comment by sauloperez** [comment]
That would be very good news!
