### ISSUE TITLE
Test Ubuntu 16.04.1 x64

### ISSUE THREAD

**Issue by pmackay** [openfoodfoundation/ofn-install#65]
This is now the default image on Digital Ocean. Obviously we can change to 14.04, but would it be worth testing an OFN install with 16.04 and using that, if it works ok?

cc @mkllnk @lin-d-hop

**Comment by mkllnk** [comment]
Yes, definitely worth testing. I think we need to re-build our production server soon. Support for Ubuntu 12.04 is ending in April.

**Comment by enricostano** [comment]
I think we can close this since https://github.com/openfoodfoundation/ofn-install/pull/70 got merged.

BTW we're using 16.04 for OFN since March without any issue.
