### ISSUE TITLE
Filepath change in master

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/ofn-install#662]
## Description

The path to a file that ofn-install references explicitly (`db/default/spree/states.yml`) has changed in master in https://github.com/openfoodfoundation/openfoodnetwork/pull/6089 which will break deployments.

Discovered here: https://github.com/openfoodfoundation/ofn-install/issues/660#issuecomment-710141481

## Expected Behavior

Deployment works

## Actual Behaviour

Deployment fails with fatal error

## Steps to Reproduce

Deploy current master 

## Severity

bug-s1: a critical feature is broken

We won't be able to deploy until this is resolved, so S1.

**Comment by Matt-Yorkley** [comment]
@luisramos0 how would you feel about changing that path back to the original `db/default/spree/states.yml`?

It's trivial to change that path in ofn-install, but the issue is that ofn-install can either be compatible with the old version or the new version, but not both at the same time. So if I make the needed change, ofn-install will only be able to deploy branches or releases after that change in the main repo, and will not be able to deploy any branches or releases prior to that change... I can't see a nice way to resolve this and keep the ability to deploy any branch, but maybe I haven't had enough coffee yet.

**Comment by Matt-Yorkley** [comment]
Hmmm.... there's more problems as well... ofn0install runs `db:seed` during deployment and it looks like there are some problems.

**Comment by luisramos0** [comment]
I think the path move is not worth the trouble! Let's move it back to where it was :+1:

**Comment by luisramos0** [comment]
The s1 tag can be a false inducer of panic, maybe we can keep it but add something to the title of the issue to clarify. There is no problem in prod yet correct? The most serious problem right now is that master is not deployable right?
