### ISSUE TITLE
Decouple ofn-install from Python 2.7

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/ofn-install#663]
## Description

ofn-install currently uses and requires Python 2.7 and Python-2 versions of packages with Ansible (psycopg for example is a dependency for interacting with postgres via python). Some of these related dependencies are heaily deprecated, and removed in newer versions of Ubuntu, which means we can't currently use ofn-install with Ubuntu 20 for example.

Discovered here: https://github.com/openfoodfoundation/ofn-install/pull/659#issuecomment-704125456

## Expected Behavior

We don't need to explicitly install or use Python 2.7

## Actual Behaviour

We currently are tied to Python 2.7 for ofn-install

**Comment by dacook** [comment]
Looks like we've been using Python 3.8.2 for some time (e170e9d365b9639bbe29494f1f7e6b6c4d86c733), so I think this can be closed.
I think it's a good idea to continue having a specific version number to avoid unexpected incompatibilities (just like we do for everything else).
