### ISSUE TITLE
FR certs are not automatically renewed

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/ofn-install#694]
## Description

During Christmas FR prod went down because our SSL cert did not renewed itself. If I understand correctly, there is an Ansible recipe that takes care of renewal during provisioning. And this isn't working for FR anymore?

Could be linked to the changes we have made for FR's new domain?

## Steps to Reproduce

See discussion when prod went down in December here : https://openfoodnetwork.slack.com/archives/CEF14NU3V/p1608671323260300

## Severity
bug-s3: a feature is broken but there is a workaround

It's technically an s3 because now that we know we can renew it manually?

## Your Environment

* Version used: v3.4.5
* Browser name and version: All
* Operating System and version (desktop or mobile): Both

**Comment by pacodelaluna** [comment]
I thought the issue was related to wrong provisonning so I rerun the recipe.

Then I saw:
```
TASK [coopdevs.certbot_nginx : Force generation of a new certificate] *************************************************************************************************************************************
skipping: [www.coopcircuits.fr]
```
The renewal was skipped, and with more trace I saw:
```
Attempting to renew cert (openfoodfrance.org) from /etc/letsencrypt/renewal/openfoodfrance.org.conf produced an unexpected error: Failed authorization procedure. openfoodfrance.org (http-01): urn:ietf:params:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response from https://www.openfoodfrance.org/.well-known/acme-challenge/0IjJAJAk-dbe44aX42U3zhrHsjNpwkhhaOiak1Uocr8 [51.255.196.10]: "<!DOCTYPE html>\n<html lang=\"fr-FR\">\n<head>\n\t<meta charset=\"UTF-8\" />\n<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n\t<lin", www.openfoodfrance.org (http-01): urn:ietf:params:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response from http://www.openfoodfrance.org/.well-known/acme-challenge/QTshlF1mRGLZK6OY9js9mrxQoIFclessDVgNNu6UsaU [51.255.196.10]: "<html>\r\n<head><title>404 Not Found</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>404 Not Found</h1></center>\r\n<hr><center>". Skipping.
```
I succeeded in renewing the certificate manually on the FR prod server:
```
ofn-admin@vps570864:~$ sudo service nginx stop
ofn-admin@vps570864:~$ sudo certbot renew
ofn-admin@vps570864:~$ sudo service nginx start
```

**Comment by pacodelaluna** [comment]
Ok, I misinterpreted the Ansible task, it is not supposed to renew the certificate, this should be manage on the server directly with `cerbot-renew`. So it is normal for the task to have been skipped.

**Comment by pacodelaluna** [comment]
I guess the issue was some configuration issue with `certbot` and manual execution helped fixing it... I wish I could be sure...

Anyway I cleaned the old certificates (we needed them for redirections), anyway it was expiring in 4 days and would have given an error as the old domain is not pointing on this server anymore.
```
ofn-admin@vps570864:~$ sudo certbot certificates
Saving debug log to /var/log/letsencrypt/letsencrypt.log

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Found the following certs:
  Certificate Name: www.coopcircuits.fr
    Domains: www.coopcircuits.fr coopcircuits.fr
    Expiry Date: 2021-03-22 20:35:43+00:00 (VALID: 69 days)
    Certificate Path: /etc/letsencrypt/live/www.coopcircuits.fr/fullchain.pem
    Private Key Path: /etc/letsencrypt/live/www.coopcircuits.fr/privkey.pem
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
```

**Comment by Matt-Yorkley** [comment]
This has been fixed :ok_hand:
