### ISSUE TITLE
Recreate Katuma staging from scratch

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/ofn-install#699]
## Description

We've been trying to fix the issue Katuma staging is having with Memcached for quite some time. Essentially, the app fails to find the Memcached server at localhost:11211 but it does when connecting to 127.0.0.1:11211. See https://openfoodnetwork.slack.com/archives/CEBMTRCNS/p1610366558071000.

It'll be faster and more reliable to just provision and deploy a new VPS from scratch. We'll take the chance to do it with Coopdevs' de-facto provider, Hetzner, which will ease the accounting and thus, will make @enricostano happier.

**Comment by enricostano** [comment]
![](https://media2.giphy.com/media/fDzM81OYrNjJC/giphy.gif?cid=ecf05e479n7arb03p5l37sasyjcirc62pmhafvxbz4pijr49&rid=giphy.gif)
