### ISSUE TITLE
Certbot installation fails

### ISSUE THREAD

**Issue by andrewpbrett** [openfoodfoundation/ofn-install#702]
## Description
On a fresh Ubuntu 16.04 (x64) server on Digital Ocean, I get the following when Ansible tries to install Certbot:

```
'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"      install 'certbot=0.31.0-1+ubuntu16.04.1+certbot+1'' failed: E: Version '0.31.0-1+ubuntu16.04.1+certbot+1' for 'certbot' was not found
```

For fun, I also tried a fresh Ubuntu 20.04 (x64) server:
```
fatal: [migrate.openfoodnetwork.net]: FAILED! => {"changed": false, "msg": "No package matching 'python-psycopg2' is available"}
```

And 18:
```
'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"      install 'certbot=0.31.0-1+ubuntu18.04.1+certbot+1'' failed: E: Version '0.31.0-1+ubuntu18.04.1+certbot+1' for 'certbot' was not found
```
(same as 16)

I tried doing `sudo apt-get update` and `sudo apt upgrade` but it had no effect.

I found https://github.com/openfoodfoundation/ofn-install/issues/392 and also did `ansible-galaxy install -r bin/requirements.yml --force` locally, but also no effect. 

I also tried a totally different provider (Linode) just in case there was something weird with Digital Ocean or their distro; but got the same message. 

## Expected Behavior
Certbot should be installed

## Actual Behaviour
Installation fails

## Steps to Reproduce

1. Create new server
2. Run `ansible-playbook site.yml` with the host config etc set up
3. 
4.

## Severity
It seems like this would be an S1 equivalent since it prevents installation, but I'm not sure if it's just something with Digital Ocean or my own setup that's causing it. 

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by Matt-Yorkley** [comment]
Just added a comment here: https://github.com/coopdevs/certbot_nginx/pull/30/files#r575692438

We need two different values for Ubuntu 16 and Ubuntu 18... :see_no_evil:

**Comment by Matt-Yorkley** [comment]
I'm not sure we can bump to the latest version of that Ansible role, as it uses Python 3 explicitly and we're not ready for that switch yet (there's an open issue for it though).

**Comment by andrewpbrett** [comment]
Doesn't it only use Python3 if you're installing on Ubuntu >= 20?

**Comment by Matt-Yorkley** [comment]
Ah yeah, you're right :+1:
