### ISSUE TITLE
Letsencrypt not installed in local vagrant

### ISSUE THREAD

**Issue by jeronimo** [openfoodfoundation/ofn-install#71]
- Git repo from - https://github.com/openfoodfoundation/ofn-install/tree/ebc73d03be2c64b4b0a4197415e3e7b517bb767e
- Vagrant 1.9.3
- Ubuntu 14.04.5 LTS
- Ansible output - https://gist.github.com/jeronimo/199d2d305ce07f3f490297ad41e0cdcd
- `/etc/letsencrypt` is missing and `/etc/opt` is empty

**Comment by jeronimo** [comment]
After fixing a lot of python libs' issues I was able to install `jaywink.letsencrypt` instead of `geerlingguy.certbot`.
Source code https://github.com/jeronimo/ofn-install/commit/913a7ec327f2198b05bd8713af90b829b1a62bb0
Unfortunately there is another problem - Letsencrypt do not provide certificates for domains like `localhost` so vagrant setup should be without https 443 or with different certificate.

**Comment by enricostano** [comment]
If the aim of this is to setup a development environment using `ofn-install` I can point you at a beta `development.yml` playbook that we're working on: https://github.com/coopdevs/ofn-install/blob/183d3c84af502675a551d9af0b25c40bfdfc7176/playbooks/development.yml

Basically it rips off all the stuff that's not needed (for now) in development. We're using this to build LXC containers but the idea is that it should work on any "thing" accessible via SSH without password and `python2.7`. Basically just ansible requirements.

Please ping me if you need more details. We're planning to open a PR to `ofn-install` ASAP.

Sorry if it's not the case and you're not trying to use this to setup a development environment 😹

**Comment by jeronimo** [comment]
This is great! I am sure we will be able to figure out and share something.

My goal is to build production environment in my local machine to test and check potential issues with gem upgrades before even pushing to staging.
Or to solve issues like https://github.com/openfoodfoundation/openfoodnetwork/pull/1513. As rspec tests fail all the time for me without `wkhtmltopdf-binary` upgrade in my local mac os.

And I just wanted to have a quick break from working on javascript and ui-grid so there are my results :)

**Comment by enricostano** [comment]
@jeronimo are you still working on this? If not, can we close it and reopen again if we work on making ansible scripts working on Vagrant in the future?

**Comment by Matt-Yorkley** [comment]
Closing for now, as we are tidying up the backlog.
