### ISSUE TITLE
Site URL reset to default after server migration

### ISSUE THREAD

**Issue by andrewpbrett** [openfoodfoundation/ofn-install#712]
## Description

After following the migration steps in https://github.com/openfoodfoundation/ofn-install/issues/646, the Site URL fell back to the default of `demo.openfoodnetwork.org`

## Expected Behavior

The Site URL preference should be preserved

## Steps to Reproduce

See #646 

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by Matt-Yorkley** [comment]
This should be fixed now :ok_hand:
