### ISSUE TITLE
Add Spanish to US Instance

### ISSUE THREAD

**Issue by lauriewayne** [openfoodfoundation/ofn-install#716]
## Description
OFN-US is currently only offered in English, though there are many immigrant and refugee communities who are more comfortable using Spanish, and they should be able to choose that. This will also demonstrate to users that alternate languages are available and encourage them to use OFN to connect users of other languages to local food systems.

## Expected Behavior

Users will be able to choose either a Spanish or English presentation of OFN

## Actual Behaviour

Users are stuck with English, which is also a perfectly good language if you happen to speak it.

## Severity

bug-s5: we can live with it, only a few users impacted

## Possible Fix

add Spanish (es) to ofn-install for OFNUS (?)

**Comment by sauloperez** [comment]
> which is also a perfectly good language if you happen to speak it.

:100: :heart:

**Comment by RachL** [comment]
@lauriewayne hello! Do you confirm this issue can be closed now?

**Comment by lauriewayne** [comment]
Sí, el caso se puede cerrar. ¡gracias! :-)
