### ISSUE TITLE
Postgres authentication question

### ISSUE THREAD

**Issue by enricostano** [openfoodfoundation/ofn-install#72]
Hi,
does anybody has any idea about why we need to create a `.pgpass` file in the home of the unicorn user?

I'm talking about this specific task: https://github.com/openfoodfoundation/ofn-install/blob/master/roles/dbserver/tasks/main.yml#L21

I don't think we use it in VPS instances, maybe Heroku or something else?

**Comment by RohanM** [comment]
This would make it easier as a user on the VPS to sign in to postgres for debug/maintenance purposes. That's my guess at the intent. What do you think?

**Comment by enricostano** [comment]
I don't know, on a VPS you can just `sudo su postgres` from `ofn-admin` user. Maybe @pmackay can shade some light on this? If we don't use it I would remove it since it adds noise on how we authenticate to postgres and for what purposes.

**Comment by pmackay** [comment]
I think this might have been added by Raf. I’m not sure I can offer
anything additional on best practice here, whether this is worth keeping.

**Comment by enricostano** [comment]
Can we simplify this step removing the things that we don't know / understand? If not we'll keep stuff that only add confusion.

What do you think @RohanM @pmackay @oeoeaio ?

**Comment by saimonmoore** [comment]
Agreed with @enricostano .

**Comment by elf-pavlik** [comment]
I see it added by @rafaqz in https://github.com/openfoodfoundation/ofn-install/commit/c936b67fd8a886188e6e528fa50ed7ee2745bfe2#diff-df92b892760893a0a7c5736ef1451e02

:+1: to removing clutter, if we ever need it again we can find it in git history

**Comment by sauloperez** [comment]
feel free to open a PR @elf-pavlik

**Comment by mkllnk** [comment]
But even when we get rid of that deployment script I still find that .pgpass file very convenient. It also enables other convenience scripts, for example the mirror-db script that copies that database of a server into your local dev environment. It doesn't need to know the password and it doesn't need to connect as ofn-admin.

Is there any downside of having this file?

**Comment by enricostano** [comment]
> Is there any downside of having this file?

Not really. I don't personally like it, but I'm not against either. The point of this issue was just about understanding who uses it and in which instance. I don't think anybody is using it, but I may be wrong.
