### ISSUE TITLE
Untoggle Unit prices for FR

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/ofn-install#730]
## Description
**- As a:** ALL loggedin and loggedin visitor of coopcircuits.fr
**- On page:** on each shops, on a customer's cart, + new product page
**- I want to be able to do:** see unit prices

## Acceptance Criteria & Tests
1. When visiting the pages listed above on CoopCircuits, any loggedin or non loggedin user should see unit prices.

**Comment by jibees** [comment]
Not sure to understand how to handle this one, but here's the doc on how to do this with Flipper: 
https://github.com/openfoodfoundation/openfoodnetwork/wiki/Feature-toggle-with-Flipper#fully-enable-a-feature

**Comment by RachL** [comment]
@jibees me neither that's why I've asked if this needed a PR. Apparently it does? 

Re flipper UI I should see the admin user group when I log in in prod, right?

**Comment by jibees** [comment]
@RachL 
Sorry, I missed that.

> Re flipper UI I should see the admin user group when I log in in prod, right?

Yes, you should. This isn't the case?

**Comment by RachL** [comment]
@jibees nope only Taylor Swift. Do you want my credentials?

**Comment by jibees** [comment]
@RachL Yes! I'll take a look.

**Comment by RachL** [comment]
USELESS FEATURE OF THE YEAR AWARD

You can easily press a button to enable a toggle for a whole instance as a super admin.

![ ](https://media.giphy.com/media/15BuyagtKucHm/giphy.gif)

Do I know how to read a doc? Clearly not 🤦
