### ISSUE TITLE
Release unit prices everywhere

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/ofn-install#731]
## Description

When #730 is done and working for a week, we can introduce the feature to the whole pool of instances we are managing.

## Acceptance Criteria & Tests

1. Unit prices are released for all instances managed by the core team

**Comment by jibees** [comment]
After this one is done and released, we should removed all the conditional testing in the code. 
Here's the issue: #7499

**Comment by jibees** [comment]
If FR instance manager (@RachL) is fully convinced and there is no bug, and no user complains:
 - Should we use this one as reminder to communicate thought instances manager on how to release the feature? (by _reading the documentation_ and using the FlipperUI)
 - Or maybe we should simply remove all the toggle code, and release it everywhere by fixing #7499

Thoughts?

**Comment by sauloperez** [comment]
IMO we should remove the toggle altogether.

**Comment by RachL** [comment]
So this issues is not needed anymore. Closing
