### ISSUE TITLE
Use same Bundler version as in OFN `Gemfile.lock`

### ISSUE THREAD

**Issue by enricostano** [openfoodfoundation/ofn-install#74]
This is a follow up to the discussion started in https://github.com/openfoodfoundation/openfoodnetwork/pull/1641

Here is where we install Bundler: https://github.com/openfoodfoundation/ofn-install/blob/master/roles/bundler/tasks/main.yml#L6

**Comment by mkllnk** [comment]
This just became really important as the newest bundler doesn't support our Ruby version any more. Ofn-install is broken for new hosts.
