### ISSUE TITLE
Add NZ to global deployment pool

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/ofn-install#775]
## Description

NZ would like to be part of the global feature pool.
They are contributing for this work, so we can prioritise it under the Funded Features Pipe.

They are on an old version of OFN so they might be a little faff.

Would be good to know what information we need from them, so that we can gather that in advance of this work being prioritised.
@Matt-Yorkley or @andrewpbrett Can you help with a list of what we need from them?

## Acceptance Criteria & Tests

1. NZ are on the latest OFN version
2. NZ are managed within the global deployment pool

**Comment by Matt-Yorkley** [comment]
If they've kept up with releases and they're on a recent version, it's really easy. If they're really far behind it's a bit more tricky...

**Comment by Matt-Yorkley** [comment]
Oooof. They're way behind...

Also I can't even SSH to the server to have a look, so someone on their end will need to provision my key and/or adjust any firewall stuff they might have (if they're on AWS they'll probably have annoyingly restrictive firewall rules by default).

**Comment by Matt-Yorkley** [comment]
Also worth noting: I strongly recommend they **don't** try to catch up quickly by just deploying the latest version. It'll need to be handled carefully and there's various pitfalls that won't be obvious.

**Comment by lin-d-hop** [comment]
Cool, will navigate to make these links. Will keep you posted. Thanks!

**Comment by mkllnk** [comment]
The current server is based on release v3.4.5 from 18 Dec 2020. It has some [custom patches](https://github.com/openfoodfoundation/openfoodnetwork/compare/master...mkllnk:nz) which are not needed any more if we configure ofn-install correctly.

### WIP list of release steps

- [ ] v3.5.0 Bump to ruby 2.4.4
- [ ] v3.5.1
- [ ] v3.5.2 Check https://github.com/openfoodfoundation/openfoodnetwork/pull/6369 for manual database repair.
- [ ] v3.5.3
- [ ] v3.5.4
- [ ] v3.5.5 Simplified email configuration code.
- [ ] v3.5.6
- [ ] v3.5.7
- [ ] v3.5.8 Remove variant migration - run migration before this release
- [ ] v3.5.9
- [ ] v3.5.10
- [ ] v3.5.11
- [ ] v3.5.12
- [ ] v3.5.13
- [ ] v3.5.14
- [ ] v3.6-beta
- [ ] v3.6.0-rc1
- [ ] v3.6.1
- [ ] v3.6.2
- [ ] v3.6.3 Ruby 2.5.8
- [ ] v3.6.4
- [ ] v3.6.5
- [ ] v3.6.6
- [ ] v3.6.7
- [ ] v3.6.8
- [ ] v3.6.9
- [ ] v3.6.10
- [ ] v3.7.0
- [ ] v3.7.1
- [ ] v3.7.2 ? provision required ?
- [ ] v3.7.3 Ruby to 2.5.9
- [ ] v3.8.0
- [ ] v3.8.1
- [ ] v3.8.2
- [ ] v3.8.3 Ruby 2.7.3
- [ ] v3.8.4
- [ ] v3.8.5
- [ ] v3.8.6
- [ ] v3.8.7
- [ ] v3.8.8
- [ ] v4.0.0 Switched app server from Unicorn to Puma - ofn-install has a branch for previous releases
- [ ] v4.0.1
- [ ] v4.1.0
- [ ] v4.1.1
- [ ] v4.1.2
- [ ] v4.1.3
- [ ] v4.1.4
- [ ] v4.1.5
- [ ] v4.1.6
- [ ] v4.1.7
- [ ] v4.1.8
- [ ] v4.1.9
- [ ] v4.1.10
- [ ] v4.1.11
- [ ] v4.1.12
- [ ] v4.1.13
- [ ] v4.1.14 Update Ruby to 3.0.2 
- [ ] v4.1.15 Ruby 3.0.3
- [ ] v4.1.16
- [ ] v4.1.17
- [ ] v4.1.18
- [ ] v4.1.19
- [ ] v4.1.20
- [ ] v4.1.21
- [ ] v4.1.22
- [ ] v4.1.23
- [ ] v4.1.24
- [ ] v4.1.25
- [ ] v4.1.26
- [ ] v4.1.27
- [ ] v4.1.28
- [ ] v4.1.29
- [ ] v4.1.30
- [ ] v4.1.31
- [ ] v4.1.32
- [ ] v4.1.33

**Comment by mkllnk** [comment]
I wrote a little script to migrate the database:
```
#!/bin/sh
#
# Migrate database from older code base.
#
# Our current code can't run all old migrations because some of them depend
# on application code. So you need to run the migrations with the code at the
# time. Here is one example of listing releases from a certain version,
# excluding a breaking newer version and filtering a bad release:
#
#   for v in `git tag --list 'v*' --sort v:refname --contains v3.5.0 --no-contains v4.2.0 | grep -v - | grep -v v3.5.7`; do
#     ./script/migrate-old-code.sh "$v" || break
#   done

set -ex

version="$1"

# Some releases introduced a differing schema.rb file but we need the
# unmodified version to checkout the next release. Stashing is safer than just
# checking out the original schema.
git stash
git checkout "$version"

# script/rbenv-install.sh from master
# Older releases don't contain this script.
if rbenv install --skip-existing; then
  echo "Ruby is installed."
else
  echo "Upgrading rbenv's ruby-build:"
  git -C "$(rbenv root)"/plugins/ruby-build pull

  rbenv install
fi

./script/install-bundler
bundle >> tmp/bundle.log
GOOD_MIGRATIONS=skip bundle exec rake db:migrate
```

My plan is to provision a new server with the most up-to-date code version, import the old database and then apply all migrations by going through all old releases.

**Comment by mkllnk** [comment]
Steps for the switchover:

* Stop services on the old server: `systemctl stop sidekiq && systemctl stop puma`.
* Log into the new server with `ssh -A` so that I can log into the old server from there.
* Copy the database: `ssh prod.openfoodnetwork.org.nz "pg_dump -h localhost -U ofn_user openfoodnetwork | gzip" > tmp/original.sql.gz`
* Reset database as postgres user: `dropdb openfoodnetwork && createdb openfoodnetworkk`
* Import as ofn user: `zcat tmp/original.sql.gz | psql -h localhost -U ofn_user openfoodnetwork`
* Run the migration script above in the previous comment.
* Start the new puma service.
* Proxy pass requests from the old server to the new server or direct Cloudflare to the new server.

**Comment by mkllnk** [comment]
Yes, I knew I should have copied it instead of typing.

**Comment by mkllnk** [comment]
The main switch is done. Some more tasks:

- [x] Deactivated services on old server.
- [x] Migrate images to Active Storage.
- [ ] Deploy most recent version.
- [ ] Configure Bugsnag for error reporting.
- [ ] Fix Google Maps API key permissions (billing).
