### ISSUE TITLE
Add Welsh language to UK-prod

### ISSUE THREAD

**Issue by lin-d-hop** [openfoodfoundation/ofn-install#782]
The Welsh language has been added to transifex. We now need to make this live on OFN UK.

File: [cy.yml](https://github.com/openfoodfoundation/openfoodnetwork/blob/master/config/locales/cy.yml)

**Comment by RachL** [comment]
ouuuh you can do that 😍 any chance you can remove italian from FR or create a FR_IT file? Our italian file is still ITalia's production 😭

**Comment by sigmundpetersen** [comment]
>  or create a FR_IT file?

I think it should be `it_fr` no?
But I don't think `it_fr` is available through Transifex though

**Comment by RachL** [comment]
yes you are right @sigmundpetersen sorry it's `it_fr`. The file is not on transifex that's why a workaround is just to remove IT from Fr's prod. I don't know which one is easier.
