### ISSUE TITLE
Unable to install v3.4.4

### ISSUE THREAD

**Issue by rngkll** [openfoodfoundation/ofn-install#788]
## Description
Getting error while trying to install version 3.4.4

## Actual Behaviour
While running the command `ansible-playbook site.yml -u ofn-admin --limit=cr-staging -e "git_version=v3.4.4"`

we get the error

```
TASK [deploy : use ruby 2.3.7] ******************************************************************************************************************************************************************************************************************
fatal: [staging.laferia.cr]: FAILED! => {"changed": true, "cmd": "bash -lc \"/home/openfoodnetwork/.rbenv/bin/rbenv global 2.3.7 && rbenv rehash\"", "delta": "0:00:00.117074", "end": "2022-01-12 14:50:38.603081", "msg": "non-zero return code", "rc": 1, "start": "2022-01-12 14:50:38.486007", "stderr": "rbenv: version `2.3.7' not installed", "stderr_lines": ["rbenv: version `2.3.7' not installed"], "stdout": "", "stdout_lines": []}
Wednesday 12 January 2022  07:50:38 -0600 (0:00:00.972)       0:06:08.861 *****
```

## Steps to Reproduce
1. Checkout to ofn-v3
1. apply changes for Costa Rica (https://github.com/rngkll/ofn-install/tree/ofn-v3-laferia)
1. `ansible-playbook site.yml -u ofn-admin --limit=cr-staging -e "git_version=v3.4.4"`

## Animated Gif/Screenshot
![image](https://user-images.githubusercontent.com/5940156/149339097-d4d38782-ab7e-4a0c-9592-eeb2247f266a.png)

## Severity
bug-s2: a non-critical feature is broken, no workaround

## Your Environment
Ubuntu 16.04 machine

* Version used:
ansible 2.9.20
  config file = /Users/asegura/git/laferia/ofn-install/ansible.cfg
  configured module search path = ['/Users/asegura/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/asegura/git/laferia/ofn-install/venv/lib/python3.9/site-packages/ansible
  executable location = /Users/asegura/git/laferia/ofn-install/venv/bin/ansible
  python version = 3.9.7 (default, Oct 13 2021, 06:44:56) [Clang 12.0.0 (clang-1200.0.32.29)]

**Comment by sigmundpetersen** [comment]
The error points to ruby v2.3.7 not being installed.
ofn-v3 does not list v2.3.7 https://github.com/openfoodfoundation/ofn-install/blob/ofn-v3/inventory/group_vars/all.yml#L60

But I don't know why it's trying to deploy with v2.3.7, maybe @Matt-Yorkley can help further

**Comment by rngkll** [comment]
I'm following the var:

1. roles/deploy/tasks/deploy.yml: register: deploy_ruby_version
2. roles/deploy/tasks/deploy.yml: {{ build_path }}/.ruby-version
3. roles/deploy/defaults/main.yml: build_path: "{{ releases_path }}/{{ timestamp }}"
4. inventory/group_vars/all.yml: releases_path: "{{ app_path }}/releases-old"
5. inventory/group_vars/all.yml:app_path: "{{ unicorn_home_path }}/apps/{{ app }}"

``` bash
openfoodnetwork@laferia-temp:~/apps/openfoodnetwork/releases-old/2022-01-13-212517$ cat .ruby-version
2.3.7
openfoodnetwork@laferia-temp:~/apps/openfoodnetwork/releases-old/2022-01-13-212517$ pwd
/home/openfoodnetwork/apps/openfoodnetwork/releases-old/2022-01-13-212517
```

**Comment by rngkll** [comment]
Ruby version is not present.
``` bash
openfoodnetwork@laferia-temp:~$ rbenv version
2.7.3 (set by /home/openfoodnetwork/.rbenv/version)
openfoodnetwork@laferia-temp:~$ rbenv versions
  2.5.8
  2.5.9
* 2.7.3 (set by /home/openfoodnetwork/.rbenv/version)
```

**Comment by mkllnk** [comment]
Did you work this out? Can we close the issue as it's for a very old version?

**Comment by rngkll** [comment]
I was not able to solve, but we can close the issue, we haven't worked on
this for a long time.


Thanks & Regards
