### ISSUE TITLE
Sidekiq log is corrupted

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/ofn-install#793]
## Description

I noticed on several servers that the sidekiq.log file gets corrupted. It's missing data and I just see a lot of `@` on the screen. I read in https://github.com/mperham/sidekiq/issues/446 that our logrotate method (copytruncate) might be the issue. The author suggests to let systemd handle the log rotation. :shrug: 

## Expected Behavior

The sidekiq log is complete without corrupted data.

## Actual Behaviour

![Screenshot from 2022-01-25 15-29-14](https://user-images.githubusercontent.com/3524483/150911107-1e8d17b2-b6e6-44c8-a0f5-6b340a4e9aec.png)

## Steps to Reproduce

1. Look at any sidekiq log that's older than one week.

## Severity

Maybe S3? The logging feature is broken, no workaround if the data is lost. But it doesn't affect the usability of the site directly.

**Comment by mkllnk** [comment]
@Matt-Yorkley What do you think about using systemd for logging? We would just not pipe the output into a log file and then we can access the log with journalctl. Maybe not as convenient when we are used to the logfiles of being in that directory but it allows to search for logs on certain dates better. At the moment, you need to check the old releases for the right folder and then the right file. It's a bit annoying at the moment.

**Comment by Matt-Yorkley** [comment]
Sure :+1:
