### ISSUE TITLE
Role disappeared: conorsch.create-droplet

### ISSUE THREAD

**Issue by danypr92** [openfoodfoundation/ofn-install#80]
https://github.com/openfoodfoundation/ofn-install/blob/bd9fbf9057de4754ab69911dcf050cb0d8c49b5d/playbooks/create_server.yml#L27

Hi,
we noticed that this role disappeared from both Ansible Galaxy and GitHub. 

We opened an issue in other repo of the role owner that uses this disappeared role. 

https://github.com/conorsch/ansible-digitalocean-vpn/issues/4

**Comment by enricostano** [comment]
cc/ @Matt-Yorkley

**Comment by pmackay** [comment]
@danypr92 are you actively using that role? I think I added it to support quickly spinning up Digital Ocean droplets, maybe thats not that much used?

**Comment by enricostano** [comment]
@pmackay we don't use it in Spain/Catalunya instance, I guess only UK uses it but maybe not even anymore.

I vote for removing the specific DO role and its dependencies.

**Comment by enricostano** [comment]
Thanks @danypr92 !
