### ISSUE TITLE
Ubuntu 20.04 Support

### ISSUE THREAD

**Issue by rafamanzo** [openfoodfoundation/ofn-install#811]
## Description

**- As a:** user looking to perform a fresh install
**- On:** ofn-install playbooks and vagrant test environment
**- I want to be able to do:** be able to install OFN to Ubuntu 20.04

As we are planning a fresh install, it is desirable to do it in a version with longer LTS.

I have found some unfinished work in https://github.com/openfoodfoundation/ofn-install/pull/659

In [Slack](https://openfoodnetwork.slack.com/archives/C02G54U7H/p1655132810185189) I was instructed to make a note that **I'm working on this** in an issue. Since I've found no issue about this, I'm creating one. Please feel free to update the acceptance criteria below.

## Acceptance Criteria & Tests

1. The installation should continue working in 16.04 and 18.04
2. All OFN features should work in a Vagrant box running 20.04

**Comment by sigmundpetersen** [comment]
Thanks @rafamanzo !
I'll assign you and move the issue to the proper Zenhub column
