### ISSUE TITLE
Add Bethan's public SSH key to the UK production and staging servers

### ISSUE THREAD

**Issue by BethanOFN** [openfoodfoundation/ofn-install#817]
My public key is:
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDGD7k/J33iZ1HuErPDFIZa5t1ovw8ZWvFSDq8h4MaVleCBC3lSvUBOiAqMaCksr8r8/u+i6h8OFb8IYgg8UAYL+5maVciS4/KqT2oeN2csfaw5bc0+96ELZ8ESE0ob43vlHEYyl+RQLH5w0CTj/SRIziUdgdaogznE7wvscWCpTAdauEM9dUtOGn8MGY15p+rZE9nSVESHhJh60OLiNvPofXPkceuls79Ow4zpOApgUPHK/GkFcm8IpMppIr2Gl6GxRLx++ResT7/HkUcCB5hIdyfCS4kz//6cKIA/bvmDwSJt1MoSPWVAI9ZO+3tUrvuC0gCkvcE6aK/+mfUUG91+zcDAn6y5XCERUsHh4QvJSZZD5lWnFcFfWFvajMOjrudpZddLrXGgrvST9gEP8dQhkDhAANbOMi9osp9MO38xeKDuqRAlNMgLoxVGXqphfxyyAcaW6DTeGVbTQFDQlIqWez19jIHkoygdcAjfM19BDtTFurkNG/MqWugXaTxRV/E= bethanphillips@Bethans-MacBook-Pro.local

**Comment by mkllnk** [comment]
@lin-d-hop Can you approve this?

**Comment by lin-d-hop** [comment]
Yes please :pray:

**Comment by jibees** [comment]
I've open a PR, but it's only add the public key to the list of the public key for now. 
https://github.com/openfoodfoundation/ofn-install/pull/821

Which servers should Bethan have access to?

**Comment by jibees** [comment]
> to the UK production and staging servers


Ok ... 😮‍💨
