### ISSUE TITLE
Deploy fails to restart unicorn

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/ofn-install#82]
```shell
RUNNING HANDLER [deploy : restart unicorn step 2] ******************************************************************************************
Thursday 05 October 2017  12:38:14 +0200 (0:00:02.295)       0:04:52.566 ******
fatal: [staging.katuma.org]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to restart service unicorn_openfoodnetwork: Failed to restart unicorn_openfoodnetwork.service: The name org.freedesktop.PolicyKit1 was not provided by any .service files\nSee system logs and 'systemctl status unicorn_openfoodnetwork.service' for details.\n"}
```

**Comment by enricostano** [comment]
This is still broken 😭

**Comment by elf-pavlik** [comment]
Same here, anyone already has strategy for how to deal with it?

**Comment by enricostano** [comment]
@elf-pavlik yep, just log in as `ofn-admin` and run:
`sudo systemctl restart unicorn_openfoodnetwork.service`

**Comment by agorapy** [comment]
It is not enought to have the following (in `roles/deploy/handlers/main.yml`):

```
- name: restart unicorn step 2
  shell: sudo /etc/init.d/unicorn_openfoodnetwork restart
  become: yes
  become_user: "{{ user }}"
  when: table_exists.stderr.find('does not exist') == -1
  # If unicorn isn't actually started yet we probably need this:
  notify: start unicorn

- name: start unicorn
  shell: sudo /etc/init.d/unicorn_openfoodnetwork start
  become: yes
  become_user: "{{ user }}"
```

This calls the `roles/webserver/templates/unicorn_init.j2` script which seems to work nice.

**Comment by enricostano** [comment]
@agorapy I don't think so, `restart` also `start` a service if not started already. The problem is with permissions. But thanks for the help!

**Comment by elf-pavlik** [comment]
I do some research on this issue, sharing some notes here:

@MikeiLL posted this question here but haven't received helpful answers: https://serverfault.com/questions/733084/running-service-with-systemd-as-default-user-via-ansible-in-ec2-requests-passwo

Based on this gist, sudoers file for `openfoodnetwork` will not play well with ansible service module https://gist.github.com/nanobeep/3b3d614a709086ff832a

We could consider running unicorn as systemd user service: https://www.brendanlong.com/systemd-user-services-are-amazing.html

Above possibly would work with ansible systemd module: https://docs.ansible.com/ansible/latest/systemd_module.html

I also stumbled across suggestions to use PolicyKit to allow certain user to control certain system service: https://serverfault.com/a/841150

Thoughts?

PS I also wonder where does it get `ofn-admin` from when I run this as `openfoodnetwork`

```shell
openfoodnetwork@granja:~$ systemctl start unicorn_openfoodnetwork.service 
==== AUTHENTICATING FOR org.freedesktop.systemd1.manage-units ===
Authentication is required to start 'unicorn_openfoodnetwork.service'.
Authenticating as: ofn-admin
Password: 
```

**Comment by elf-pavlik** [comment]
> We could consider running unicorn as systemd user service: https://www.brendanlong.com/systemd-user-services-are-amazing.html

PR #143 shows working (mostly) prove of concept for that approach

**Comment by elf-pavlik** [comment]
PR #144 proposes a simpler approach and fully works (including restarting nginx)
