### ISSUE TITLE
db_user is not allowed to run db:seed

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/ofn-install#83]
The `db:seed` rake task fails with:

```
PG::Error: ERROR: permission denied: "RI_ConstraintTrigger_30381" is a system trigger
```

According to https://github.com/matthuhiggins/foreigner/issues/61 the Postresql's database adapter tries to disable all triggers (referential constraints are triggers internally). The only way I managed to overcome it is turning the `db_user` superuser.

I can't understand how this works in other environments.

**Comment by elf-pavlik** [comment]
Does this still happen in latest version? `db:seed` never failed for me while i run this playbook many times in last weeks.

**Comment by sauloperez** [comment]
I believe I meant running `db:seed` from the command line on your dev environment. I guess we grant `db_user` super user privileges.
