### ISSUE TITLE
Upgrade nodejs to latest LTS, ie. 18.x

### ISSUE THREAD

**Issue by jibees** [openfoodfoundation/ofn-install#838]
## Description
We have recently upgraded github actions (and nodejs itself) to use the latest LTS version via https://github.com/openfoodfoundation/openfoodnetwork/pull/9820 

I think it could be a good idea to also use the latest LTS version in ofn-install. 

(locally, it seems that I use the nodejs v18, so I'll assume that moving from 14 to 16 will be ok)

**Comment by jibees** [comment]
Seems like upgrading node is blocked by upgrading ansible version.

**Comment by dacook** [comment]
Looks like this was automatically moved to Dev Test Ready. I will move to Tech debt prioritised, as I think it's safe to say this is a priority.

**Comment by dacook** [comment]
One way to do this would be to install Nodenv, then upgrade the version in the app `.node-version` file (we now [recommend doing this in dev](https://github.com/openfoodfoundation/openfoodnetwork/pull/10366)). 
But it might not be worth setting that up in Ansible, especially given that this would be replaced if we move to Docker.

I think we should also update the CI config to use this version file. ([so I did](https://github.com/dacook/openfoodnetwork/pull/new/use-same-node-version-in-ci))

**Comment by dacook** [comment]
I think ideally we'd update the playbook to install nodenv (like we do with rbenv), but that will probably take more effort.

But maybe we can just update the system node version for now, it's a simple config change:
https://github.com/openfoodfoundation/ofn-install/blob/master/inventory/group_vars/all.yml#L150

I tried this, but was unable to install on au-staging :(
```
"item": "deb-src https://deb.nodesource.com/node_17.9.1 xenial main", "msg": "apt cache update failed"}
```
I don't know, but it's possible this will be a problem for nodenv also. I'll reach out on `#devops`.

**Comment by dacook** [comment]
As [discussed](https://openfoodnetwork.slack.com/archives/CEBMTRCNS/p1675994843020009),  I'll try installing nodenv on the servers.
If it works, we'll add a script to install it automatically (maybe a script in the openfoodnetwork codebase like install-bundler, which we'll trigger from the playbook)

**Comment by dacook** [comment]
Sorry @jibees I just realised you're assigned to this. Would you like to continue with it, or happy to assign to me?

**Comment by jibees** [comment]
i'm happy to assign to you ;)

**Comment by dacook** [comment]
Hooray, nodenv knows where to download it from!

```openfoodnetwork@staging:~/apps/openfoodnetwork/current$ nodenv install 17.9.1
Downloading node-v17.9.1-linux-x64.tar.gz...
-> https://nodejs.org/dist/v17.9.1/node-v17.9.1-linux-x64.tar.gz

WARNING: node-v17.9.1-linux-x64 is past its end of life and is now unsupported.
It no longer receives bug fixes or security updates.

Installing node-v17.9.1-linux-x64...
Installed node-v17.9.1-linux-x64 to /home/openfoodnetwork/.nodenv/versions/17.9.1
openfoodnetwork@staging:~/apps/openfoodnetwork/current$ node --version
v17.9.1
```

So the next step is to set up installation of nodenv.

**Comment by dacook** [comment]
Ok I think this is done!
Nodenv is installed on the servers, and the `.node-version` file has been updated. It will be deployed to production servers with the release next Tuesday.

**Comment by jibees** [comment]
Great! 🚀
