### ISSUE TITLE
Invalid group names in hosts file

### ISSUE THREAD

**Issue by dacook** [openfoodfoundation/ofn-install#844]
## Description

When running the playbooks, a warning is shown that the group names in the `hosts` file are invalid. It doesn't seem to be a problem, but maybe it will be in the future.
```
[WARNING]: Invalid characters were found in group names but not replaced, use -vvvv to see details
Not replacing invalid character(s) "{'-'}" in group name (au-prod)
...
```

According to the [hosts documentation](https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html), 

> Group names should follow the same guidelines as [Creating valid variable names](https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#valid-variable-names).

## Possible Fix

We could replace the hyphens with underscores.
It might also be a good time to consider changing to YAML format, which could make the hierarchy clearer.

**Comment by sigmundpetersen** [comment]
I _think_ this was all closed in #904 
We can always reopen if we see it again
