### ISSUE TITLE
Export RAILS_ENV environment variable

### ISSUE THREAD

**Issue by enricostano** [openfoodfoundation/ofn-install#85]
Every time we run a rails related command we need to specify it and it's really annoying.

We should have `RAILS_ENV` exported with the given Rails environment.

**Comment by enricostano** [comment]
This should be added in `app` role IMHO.
https://github.com/openfoodfoundation/ofn-install/tree/master/roles/app

**Comment by elf-pavlik** [comment]
Did #89 sove this one?

**Comment by sauloperez** [comment]
Yep, thanks for the heads-up @elf-pavlik
