### ISSUE TITLE
Reduce Puma worker timeouts

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/ofn-install#859]
## Description

Timeouts have been increased on several instances to allow for long-running reports. This is now been moved into a separate process and we can reduce the timeout again. I would suggest the default timeout of 30 seconds. So we can remove host-specific timeouts from the inventory.

Follow up from:

- https://github.com/openfoodfoundation/openfoodnetwork/issues/10282

**Comment by mkllnk** [comment]
New Relic APM is activated for au-prod and records response times.

Usually all pages respond in well under 2 seconds. The default timeout of 30 seconds would be enough for over 99% of all requests. But we would like to respond to all legit requests.

* The longest response time was 3 minutes due slow response times from Bugsnag trying to respond to an invalid request. We can ignore that.
* Some shops take up to 2 minutes to load. I can't reproduce it. They seem to be outliers but I think that we should keep a timeout of 2 minutes until we improved that page. My hunch is that new product images were uploaded and needed resizing before the page can be displayed.
* `shops#index` seems to be the slowest page in total with an average of 4 seconds to load. The maximum is 9.3 seconds on au-prod.

**Comment by RachL** [comment]
@mkllnk would it be worth checking UK or FR as well? I recall UK needed a 6min timeout or something, maybe they experience other pages that are quite slow?

**Comment by mkllnk** [comment]
> would it be worth checking UK or FR as well?

We don't have APM for other servers. We would need to add it, wait a while and later remove it because it does affect performance negatively. I think that 2 minutes is a conservative value anyway. Most people wouldn't wait that long and try again. I would be surprised if there's a page that needs that long on a regular basis.
