### ISSUE TITLE
Change crontab user for Letsencrypt renewal

### ISSUE THREAD

**Issue by enricostano** [openfoodfoundation/ofn-install#86]
## WAT!? Why!?
Right now we [pass](https://github.com/openfoodfoundation/ofn-install/blob/master/playbooks/provision.yml#L52) `openfoodnetwork` to the [cerbot](https://github.com/geerlingguy/ansible-role-certbot) role as the crontab user for Letsencrypt renewal cron job.
```
openfoodnetwork@staging:~$ crontab -l
#Ansible: Certbot automatic renewal.
30 3 * * * /opt/certbot/certbot-auto renew --quiet --no-self-upgrade
```
The problem is that `openfoodnetwork` user doesn't have permissions to run the certbot binary. Give a look at the CRON log:
```
oct 24 03:30:01 scw-ecce22 CRON[10274]: (openfoodnetwork) CMD (/opt/certbot/certbot-auto renew --quiet --no-self-upgrade)
oct 24 03:30:01 scw-ecce22 sudo[10278]: pam_unix(sudo:auth): auth could not identify password for [openfoodnetwork]
oct 24 03:30:01 scw-ecce22 sudo[10278]: openfoodnetwork : user NOT in sudoers ; TTY=unknown ; PWD=/home/openfoodnetwork ; USER=
oct 24 03:30:03 scw-ecce22 sudo[10299]: pam_unix(sudo:auth): auth could not identify password for [openfoodnetwork]
oct 24 03:30:03 scw-ecce22 sudo[10299]: openfoodnetwork : user NOT in sudoers ; TTY=unknown ; PWD=/home/openfoodnetwork ; USER=
oct 24 03:30:03 scw-ecce22 CRON[10270]: (CRON) info (No MTA installed, discarding output)
oct 24 03:30:03 scw-ecce22 CRON[10270]: pam_unix(cron:session): session closed for user openfoodnetwork
```

## Proposal
Let's use `ofn-admin` user instead since it has permissions to run it. There is still a pending problem about the `standalone` web server but it will be covered in another issue. Will link to this one once created.

**Comment by enricostano** [comment]
> On the server I just provisioned, the root user already had the crontab entry.
Who created it? Are you using latest `ofn-install`?

**Comment by mkllnk** [comment]
https://certbot.eff.org/all-instructions/#ubuntu-16-10-yakkety-nginx
> The Certbot packages on your system come with a cron job that will renew your certificates automatically before they expire.

**Comment by mkllnk** [comment]
Oh sorry, I quoted the wrong source. https://certbot.eff.org/#ubuntuxenial-nginx
> The Certbot packages on your system come with a cron job that will renew your certificates automatically before they expire. 

Same thing. The new server I set up runs 16.04:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```
And that's what I observed there. I don't want to setup a new server just to test this and my machine is too slow to do it.

**Comment by enricostano** [comment]
Nice, thanks! I'll test it and report back.

**Comment by enricostano** [comment]
I just created a Ubuntu Xenial 16.04 LXC container and installed `certbot` following the steps from doc and I get the following:
```
ubuntu@hola:~$ cat /etc/cron.d/certbot 
# /etc/cron.d/certbot: crontab entries for the certbot package
#
# Upstream recommends attempting renewal twice a day
#
# Eventually, this will be an opportunity to validate certificates
# haven't been revoked, etc.  Renewal will only occur if expiration
# is within 30 days.
SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

0 */12 * * * root test -x /usr/bin/certbot -a \! -d /run/systemd/system && perl -e 'sleep int(rand(3600))' && certbot -q renew
```

**Comment by enricostano** [comment]
I'm not sure which one actually run the renewal between `cron` and `systemd.timer`, but the latter surely run:
```
enrico@scw-064c30:~$ systemctl list-timers
NEXT                         LEFT          LAST                         PASSED       UNIT                         ACTIVATES
Thu 2018-03-01 00:29:23 UTC  4h 53min left Wed 2018-02-28 15:56:10 UTC  3h 39min ago apt-daily.timer              apt-daily.ser
Thu 2018-03-01 00:40:41 UTC  5h 5min left  Wed 2018-02-28 12:09:29 UTC  7h ago       certbot.timer                certbot.servi
Thu 2018-03-01 17:35:49 UTC  22h left      Wed 2018-02-28 17:35:49 UTC  1h 59min ago systemd-tmpfiles-clean.timer systemd-tmpfi

3 timers listed.
```

**Comment by elf-pavlik** [comment]
I think #124 fixed it
