### ISSUE TITLE
Remove datadog agent

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/ofn-install#885]
We cancelled our Datadog subscription and need to stop using it this month. Otherwise we will get charged on-demand rates.

### WIP

* https://github.com/openfoodfoundation/ofn-install/compare/master...mkllnk:ofn-install:datadog

**Comment by drummer83** [comment]
https://github.com/openfoodfoundation/openfoodnetwork/pull/11092 has been merged. Can we close here?

**Comment by mkllnk** [comment]
> https://github.com/openfoodfoundation/openfoodnetwork/pull/11092 has been merged. Can we close here?

No. The datadog agent is a separate process running on the server to monitor resources and log files. We still need to do this. We are still getting charged by Datadog.

**Comment by mkllnk** [comment]
All done.
