### ISSUE TITLE
Remove AU/FR/UK's puma restart

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/ofn-install#915]
## Description

As discussed here: 

https://openfoodnetwork.slack.com/archives/C01T75H6G0Z/p1702978038586629

We are now in a good place to remove the cron task that restarts puma every day on these 3 instances.

I guess this is a prod test with new relic, so I haven't written up a testing section, but if anyone has a proposal feel free to update the issue :-)

**Comment by mkllnk** [comment]
Puma restarts removed from crontab on:

* au_prod
* uk_prod
* fr_prod
