### ISSUE TITLE
Migrate Uptime Kuma alert to New Relic

### ISSUE THREAD

**Issue by rioug** [openfoodfoundation/ofn-install#926]
## Description
Now that we moved N8N to n8n.openfoodnetwork.org, we would like to retire the server, but it's currently running Uptime Kuma to monitor a bunch of servers. New Relic has what they call [Synthetic monitoring](https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/getting-started/get-started-synthetic-monitoring/) which should be able to replace the current Kuma monitors/

Monitor to be migrated :
- [ ] ~~Coopcircuits FR DNS~~
- [ ] ~~Coopcircuits FR Ping~~
- [x] Coopcircuits FR Prod
- [x] Coopcircuits FR Prod Job Queue Status
- [x] Coopcircuits Outils Prod
- [x] Coopcircuits Wordpress
-  ~~N8N~~ Not needed any more
- [x] OFN UK Wordpress
- [x] OpenFoodFrance Discourse
- [x] OpenFoodFrance Wordpress

Additional task:
- Remove existing Cloudron synthetic monitor

**Comment by mkllnk** [comment]
We had some of these monitors in Wormly already. I added the missing ones. I skipped the DNS and ping tests because a ping doesn't prove much at all and DNS is implicitly tested during web requests.

**Comment by dacook** [comment]
Just confirming these were migrated to Wormly, not New Relic? I can't see them in NR under Alerts or Synthetic monitoring, so I guess so.

This list doesn't include all core managed instances, so we still don't have monitoring for all yet.

**Comment by mkllnk** [comment]
> Just confirming these were migrated to Wormly, not New Relic? 

That's correct.
