### ISSUE TITLE
Avoid the need for s3_backups_bucket: none

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/ofn-install#93]
## What

we shouldn't need to define vars that we don't use and check for their existence wherever they are used. Otherwise, the more vars are used the more annoying it'll be for instances that don't use them.

We should do the same as in https://github.com/openfoodfoundation/ofn-install/pull/92 for `s3_backups_bucket`.

**Comment by elf-pavlik** [comment]
I think this relates to #109 

would setting up those `none` values in `group_vars/all.yml` make sense here?

**Comment by enricostano** [comment]
We just should get rid of them by default and add them to the specific host variable list if needed.

**Comment by elf-pavlik** [comment]
I just started using ansible so I can't tell yet how to get rid of them. Wouldn't moving all those `null` values to `group_vars/all.ytml` provide at least some intermediate step to problem

>  the more vars are used the more annoying it'll be for instances that don't use them

and issue could stay open to implement better solution which make all the optional values truly optional.
