### ISSUE TITLE
[Upgrade Ubuntu] ca_prod

### ISSUE THREAD

**Issue by dacook** [openfoodfoundation/ofn-install#940]
Checklist based on https://github.com/openfoodfoundation/ofn-install/wiki/Migrating-a-Production-Server

## Setup
- [x] check old server config for any additional services, eg `/etc/nginx/sites-available`
- [x] hosting: provision new server with Ubuntu 20
  - [x] and add DNS for new domain (`prod2.openfoodnetwork.ca`)
- [x] Review host_vars config.yml
   -  remove old users_sysadmin if needed
   - allow default postgres12
- [x] Review ofn-secrets secrets.yml, remove unused config 
   - Move to shared bugsnag 
- [x]  add to `inventory/hosts`, copy temporary host_vars
- [x] `letsencrypt_proxy.yml`
- [x] `setup.yml`
- [x] `provision.yml`
- [x] `deploy.yml`
- [x] `transfer_assets.yml`
- [x] manually copy terms of service file (this probably wasn't necessary after 
- [x] `db_integrations`
-  Check:
   - [x] test `reboot`
   - [x] send test mail (https://prod2.openfoodnetwork.ca/admin/mail_methods/edit). 
   - [x] sidekiq is NOT running yet (https://prod2.openfoodnetwork.ca/admin/sidekiq/metrics or sidekiq.log)
   - [x] terms of service file: https://prod2.openfoodnetwork.ca/admin/terms_of_service_files
   - [x] shop catalogue display correctly, with images, add to cart, begin checkout
 - Check integrations 
   - [x] payment (check Stripe connect status https://prod2.openfoodnetwork.ca/admin/stripe_connect_settings/edit)
   - [x] New Relic working, stats appearing
   - [x] bugsnag 
   - [ ] any others?

## Migration
- [x] deploy.yml matching version
- [x] transfer_assets.yml
- [x] old server: make a tiny data change to verify later 
- [x] old server: 🚧 maintenance_mode.yml
- [x] old server: stop sidekiq 
- [x] db_transfer.yml
- [x] transfer_assets.yml again, because ca_prod stores images locally (s3_access_key: not set).
- [x] old server: stop puma, postgres (ensure other integrations no longer touch it)
- [x] old server: shutdown redis-jobs. copy `/var/lib/redis-jobs/dump.rdb` to new server
- [x] new server: systemctl restart puma; start sidekiq; start redis-jobs
- [x] Rails.cache.clear (or migrate redis-cache/dump.rdb also)
- [x] ⏭️ `temporary_proxy.yml` redirect traffic to new prod
- check everything is working
  - [ ] get confirmation from local team (eg David T or Theresa)
  - [x] tiny data change is present. undo it.
  - [x] shopfront and checkout looks good
  - [x] sidekiq is running
  - [ ] n8n https://n8n.openfoodnetwork.org/workflow/QHqgDXTZEg2Wfiw0
  - [x] https://waterlooregionfood.ca/directory/
- [x] Update DNS to point to new server
- [ ] Update DNS for waterlooregionfood.ca also

## Cleanup (after 48hrs)
- [x] check server access logs to verify no traffic (or NR network graph)
- [ ] shut down the old server, cancel old DO droplet
- [ ] remove DNS for temporary subdomain
- [x]  make sure the entries in ofn-install are up to date: remove the temporary entry made for the migration, and set the new IP address. 
- [ ] validate that `provision.yml` still works. This will rename ca-prod2 to ca-prod
- [ ] ~~check metabase sync: https://data.openfoodnetwork.org.uk/admin/databases/~~ Not required
- [ ] n8n: [CA - Garden Party Flower Plugs Orders Aggregation](https://n8n.openfoodnetwork.org/workflow/QHqgDXTZEg2Wfiw0)
- [ ] clean up local `ofn-install/backups`
- Update documentation: 
   * [x] https://github.com/openfoodfoundation/ofn-install/wiki/Current-servers

## Rollback plan
* If an error occurs before the  temporary proxy is active, and can't be resolved quickly, then restore service back to current server
* If an error occurs after proxy is active, users may have interacted with the new server (eg made payments.
   * if serious, consider putting into maintenance mode (and stop sidekiq) to avoid further changes
   * otherwise seek to resolve issue in-place.

## Follow up
  * Backups: there are none automated!
    * database is backed up and kept for last 4 releases (approx 1 month). but not stored offsite.
    * all asset files (incl product images) are not backed up https://github.com/openfoodfoundation/ofn-install/blob/master/roles/migrate_assets/defaults/main.yml#L8-L11
    * old snapshot in DO: confirm and destroy to save wasted $1.48 month

**Comment by dacook** [comment]
It doesn't have to be this Sunday, and in fact I just realised that perhaps
that's a busier time, if people are planning and shopping for the week
ahead. Let me know if there's a better time.

**Comment by dacook** [comment]
All done!
Go-live occurred around 2024-10-31 14:45 (AEDT) 
https://openfoodnetwork.slack.com/archives/CG7NJ966B/p1730346315048729?thread_ts=1727068302.322209&cid=CG7NJ966B

Including the Waterloo api cache service.

**Comment by dacook** [comment]
Actually we need to update the DNS for waterloo. waiting on access

**Comment by dacook** [comment]
Delayed waterloo switchover until Decemeber to avoid unexpected issues during sensitive time.
It's now December so I have requested to switch:
https://openfoodnetwork.slack.com/archives/CG7NJ966B/p1733098961506759?thread_ts=1727068302.322209&cid=CG7NJ966B

**Comment by dacook** [comment]
🚀  api.waterlooregionfood.ca switched.

**Comment by dacook** [comment]
Server shutdown, I've requested David T to delete it because I can't access DO at the moment.

**Comment by dacook** [comment]
I did a very brief check of server traffic first: 

```
ofn-admin@ca-prod:/var/log/nginx$ tail -f access.log
78.153.140.223 - - [04/Dec/2024:19:21:01 +0000] "GET /web/.env HTTP/1.1" 400 650 0.000 "-" "Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; MASA; .NET4.0C; .NET4.0E; AskTbFWV5/5.15.29.67612)"
78.153.140.223 - - [04/Dec/2024:19:21:02 +0000] "GET /web/debug/default/view HTTP/1.1" 400 650 0.000 "-" "Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36"
45.148.10.205 - - [04/Dec/2024:19:28:23 +0000] "GET /.git/config HTTP/1.1" 301 162 0.000 "-" "Mozilla/5.0 (Linux; Android 7.1.2; Redmi 4A) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.111 Mobile Safari/537.36"
45.83.64.121 - - [04/Dec/2024:19:35:43 +0000] "GET / HTTP/1.1" 301 162 0.000 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:65.0) Gecko/20100101 Firefox/65.0"
147.45.112.147 - - [04/Dec/2024:20:44:59 +0000] "\x03\x00\x00/*\xE0\x00\x00\x00\x00\x00Cookie: mstshash=Administr" 400 150 0.096 "-" "-"
88.214.25.65 - - [04/Dec/2024:20:50:39 +0000] "\x03\x00\x00/*\xE0\x00\x00\x00\x00\x00Cookie: mstshash=Administr" 400 150 0.098 "-" "-"
162.142.125.34 - - [04/Dec/2024:21:11:29 +0000] "\x16\x03\x01\x00\xEE\x01\x00\x00\xEA\x03\x03\x09\x98;\x85\xF1\x0F\xF3\xA0\xB6w>\xFC\xCF\x00\x98\xD2_\xBB\xA3\xBC\xB1" 400 150 0.033 "-" "-"
13.83.43.53 - - [04/Dec/2024:22:07:53 +0000] "GET /version HTTP/1.1" 301 162 0.000 "-" "Mozilla/5.0 zgrab/0.x"
129.159.98.17 - - [04/Dec/2024:22:35:41 +0000] "GET / HTTP/1.0" 301 162 0.000 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
3.255.131.132 - - [04/Dec/2024:22:58:59 +0000] "GET / HTTP/2.0" 403 146 0.000 "-" "Mozilla/5.0 (compatible; NetcraftSurveyAgent/1.0; +info@netcraft.com)"
^C
ofn-admin@ca-prod:/var/log/nginx$ date
Wed Dec  4 23:22:04 UTC 2024
```

**Comment by David-OFN-CA** [comment]
@dacook confirming deletion of ca_prod and purchase of DO weekly backup SaaS service

**Comment by dacook** [comment]
Fantastic 👍
