### ISSUE TITLE
[Upgrade Ubuntu] au_prod

### ISSUE THREAD

**Issue by dacook** [openfoodfoundation/ofn-install#966]
Clone existing image and upgrade it. Don't use temporary subdomain to save time. 
Switchover for minimal downtime.

## 1. Setting up the new server
- [x] clone current server in Rimu hosting
- [x] do-release-upgrade 18 -> 20

### config
- [ ] ~~Add temporary name to `inventory/hosts`~~
- [x] Review `host_vars/x/config.yml`, clean up if needed
- [x] Review `group_vars/x.yml`, clean up if needed
- [x] Review `ofn-secrets:x_prod/secrets.yml`, clean up if needed
- [x] enable Gmail IP authentication: Google Admin > Apps > Gmail > Routing > SMTP Relay Service
- [x] DNS: add temporary domain (eg `prod4.openfoodnetwork.org.au`)

### setup
Enable passthrough on _current_ server to allow new server to generate a certificate:
- [x] `ansible-playbook playbooks/letsencrypt_proxy.yml -l au_prod -e "proxy_target=prod4.openfoodnetwork.org.au"`

Then setup new server. Ensure you have the correct secrets (current secrets are usually fine).
`ansible-playbook -l x_prod2 -e "@../ofn-secrets/x_prod/secrets.yml" playbooks/`
- [x] `setup.yml`
- [x] `provision.yml`
- [x] `deploy.yml`
- [x] `db_integrations` (Permit DB access for n8n, Metabase)

### initial migration
- [x] Ensure sidekiq is disabled, to avoid creating subscription orders when data is loaded. Note that it will still get started by the deploy playbook each time it runs.
    `sudo systemctl stop sidekiq && sudo systemctl disable sidekiq`
- [x] Setup direct ssh access for `ofn-admin` and `openfoodnetwork` as per guide

`ansible-playbook -l x_prod -e rsync_to=x_prod2 playbooks/`
- [x] `db_transfer.yml` &&
- [x] `transfer_assets.yml`

Make sure to clear cache so that instance settings are applied:
`cd ~/apps/openfoodnetwork/current; bin/rails runner -e production "Rails.cache.clear"`

## 2. Testing
 - [ ] test `reboot`
 - [x] send test mail (`/admin/mail_methods/edit`). 
 - [x] terms of service file: `/admin/terms_of_service_files`
 - [x] shop catalogue display correctly, with images, add to cart, begin checkout, login
  - note: check cookies if login won't work
 - Check integrations 
   - [x] Payments (check Stripe connect status `/admin/stripe_connect_settings/edit`)
   - [x] New Relic
   - [ ] Bugsnag

### preparation
- [x] Reset database on new server? I think to avoid any migration issues due to being out of sync
  `bin/rake db:reset` (You will need to confirm. Make sure you're on the new server!)
- [x] Update ansible_host IP in `inventory/hosts` and ensure provision works (this should update host in `.env.production` and enable sidekiq again).
    `ansible-playbook playbooks/provision.yml -l x_prod`
- [x] `ansible-playbook playbooks/deploy.yml -l x_prod -e "git_version=vX.Y.Z"` matching version with current prod
- [x] old server: make a tiny data change to verify later (eg add `.` in meta description `/admin/general_settings/edit`)

### switchover: old server
- [x] 🚧 `ansible-playbook playbooks/maintenance_mode.yml -l x_prod`
- [x] `sudo systemctl stop sidekiq redis-jobs puma`
- [x] `ansible-playbook -l x_prod -e rsync_to=x_prod2 playbooks/db_transfer.yml &&`
- [x] `ansible-playbook -l x_prod -e rsync_to=x_prod2 playbooks/transfer_assets.yml`
- [x] Transfer `/var/lib/redis-jobs/dump.rdb` to new server (see guide)
- [x] `sudo systemctl stop postgresql` (ensure other integrations no longer touch it)

### switchover: new server
- [x] `sudo systemctl restart puma; sudo systemctl start sidekiq redis-jobs`
- [x] `cd ~/apps/openfoodnetwork/current; bin/rails runner -e production "Rails.cache.clear"` (or migrate redis-cache/dump.rdb also)
- [x] ⏭️ `ansible-playbook -l x_prod playbooks/temporary_proxy.yml -e 'proxy_target=<new_ip>'` redirect traffic to new prod
  * Note: this doesn't include webservices, and doesn't handle images. So it's a very short-term fix if at all.
  * Use a `hosts` file entry to test a direct connection
- Check there are no alarm bells, eg:
  - [ ] tiny data change is present. undo it.
  - [x] shopfront and checkout looks good
  - [ ] upload a product image
  - [x] `~/apps/openfoodnetwork/current/log/production.log` and `sidekiq.log`
- [ ] Update DNS to point to new server
- [ ] get confirmation from local team
- [ ] make sure the entries in ofn-install are up to date: set the new IP address and remove any temporary entry made for the migration
- Update documentation: 
  * [x] https://github.com/openfoodfoundation/ofn-install/wiki/Current-servers
  * [ ] This migration guide if necessary

### switchover: discover regenerative
- tbc

## 4. Cleanup (after 48hrs)
- [x] check server access logs to verify no traffic
- [x] shut down the old server, 
- [ ] cancel old VPS
- [ ] remove DNS for old subdomain
- [x] check metabase sync if required: https://data.openfoodnetwork.org.uk/admin/databases/
- [x] check n8n
- [x] check backups are functioning

## Rollback plan
* If an error occurs before the temporary proxy is active, and can't be resolved quickly, then restore service back to current server
* If an error occurs after proxy is active, users may have interacted with the new server (eg made payments.
   * if serious, consider putting into maintenance mode (and stop sidekiq) to avoid further changes
   * otherwise seek to resolve issue in-place.

**Comment by dacook** [comment]
Our existing hosting provider does not support creating a new VPS with Ubuntu 20 (minimum is 22), so I considered other options. My rough notes:

 * upgrade to new host? [which host](https://docs.google.com/spreadsheets/d/1_Hr3UbbQdWmraaloL-bQXeHbC1ziFy9LJ8ydMDmDuSk/edit?gid=1404766143#gid=1404766143)? eg
      * binarylane: super cheap
      * serversaurus: super enviro creds (but expensive)
  * ubuntu PRo fo security updates, upgrade later
  * ~~upgrdae staging now (get away from U16) , prod later?~~ nah it needs to be done
  * upgrdae inplace. for prod, can clone, upgrade then switch. ⏪ chose this one.

**Comment by dacook** [comment]
Notes after in-place upgrade:
I don't remember doing this for au_staging, but I had to delete the existing Ruby and Gem versions and re-install them (which is not that surprising, really).
Also Apache2 was running and blocking nginx from using port 80. `sudo systemctl stop apache2; sudo systemctl disable apache2`

**Comment by dacook** [comment]
Aborted due to issue with jemalloc.  Logging here for posterity.

Can't boot rails because ruby wasn't installed with jemalloc
```
home/openfoodnetwork/.gem/ruby/3.1.0/gems/msgpack-1.7.2/lib/msgpack.rb:7:in `require': /usr/lib/x86_64-linux-gnu/libjemalloc.so.2: cannot allocate memory in static TLS block - /home/openfoodnetwork/.gem/ruby/3.1.0/gems/msgpack-1.7.2/lib/msgpack/msgpack.so (LoadError)
	from /home/openfoodnetwork/.gem/ruby/3.1.0/gems/msgpack-1.7.2/lib/msgpack.rb:7:in `<top (required)>'
```

For some reason, when installed from provision.yml, it wasn't included (despite saying so):
```
TASK [zzet.rbenv : install ruby 3.1.4 for select users] *************************************************************************
changed: [openfoodnetwork.org.au] => (item=['openfoodnetwork', {'version': '3.1.4', 'env': {'RUBY_CONFIGURE_OPTS': '--with-jemalloc'}}])
Thursday 12 December 2024  11:17:42 +1100 (0:05:08.633)       0:06:47.905 *****
```

But when removed, and installed with `deploy.yml`, it worked:
```
TASK [deploy : Install required Ruby version if needed] *************************************************************************
changed: [openfoodnetwork.org.au]
Thursday 12 December 2024  11:42:36 +1100 (0:05:07.718)       0:05:54.308 *****
```

Dunno why, this wasn't an issue on other servers. But it's solved now, and as long as we use deploy.yml to upgrade ruby it should be ok in the future!

Also we are considering removing the install step from provision.yml, and relying only on the rbenv-install script. Jemalloc isn't needed in dev, so the script could check if jemalloc is present, or check an environment variable, and add the parameter as needed.

**Comment by mkllnk** [comment]
Just filling in a few steps I did today:

* Copy `/etc/nginx/sites-enabled/discover-api.conf` to the new server.
* Restart nginx on the new server.
* Test with host file or alternatively:
  `curl --connect-to api.regenerative.org.au:443:prod4.openfoodnetwork.org.au:443 'https://api.regenerative.org.au/webhook/regen/producers'
* Update api.regenerative.org.au DNS in Digital Pacific.
* Disable puma on the old server.
* Disable sidekiq on the old server.
* Disable postgresql on the old server.

**Comment by dacook** [comment]
Thank you Maikel, I'm sorry I didn't do this in advance.

I've documented this in the wiki: https://github.com/openfoodfoundation/ofn-install/wiki/Current-servers#australia

**Comment by dacook** [comment]
confirming old server no longer in use, just bots scanning for vulnerabilities:

```
139.59.82.241 - - [15/Dec/2024:21:04:43 +0000] "GET /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php HTTP/1.1" 400 650 0.000 "-" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36"
164.92.149.65 - - [15/Dec/2024:21:05:15 +0000] "GET / HTTP/1.1" 301 162 0.000 "-" "Mozilla/5.0 (compatible)"
204.188.228.39 - - [15/Dec/2024:22:37:53 +0000] "GET /.env HTTP/1.1" 301 162 0.000 "-" "Mozilla/5.0 Keydrop"
204.188.228.39 - - [15/Dec/2024:22:37:54 +0000] "GET /.env HTTP/1.1" 400 248 0.000 "-" "Mozilla/5.0 Keydrop"
181.49.205.58 - - [15/Dec/2024:22:38:51 +0000] "GET /admin/config.php HTTP/1.0" 301 162 0.000 "-" "nvdorz"
147.182.253.243 - - [15/Dec/2024:22:41:03 +0000] "\x16\x03\x01\x00\xB4\x01\x00\x00\xB0\x03\x03\x9E\xDA\xE1@g\x8B\xCA=tz\xD2=\xF5f\x10\xA2/)nB\x19\xCAt\xBA\xC6SxRZX># fv\x06\xD5\x1EG\xFBMJ\xDE\xF5\xBEA\x1A^\x94R(\xCD\xFA" 400 150 0.210 "-" "-"
159.223.84.70 - - [15/Dec/2024:22:41:10 +0000] "GET / HTTP/1.1" 301 162 0.000 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36"
159.223.84.70 - - [15/Dec/2024:22:41:10 +0000] "GET /favicon.ico HTTP/1.1" 301 162 0.000 "-" "Go-http-client/1.1"
13.91.165.91 - - [15/Dec/2024:23:26:37 +0000] "GET /actuator/health HTTP/1.1" 301 162 0.000 "-" "Mozilla/5.0 zgrab/0.x"
167.94.145.105 - - [15/Dec/2024:23:32:22 +0000] "GET / HTTP/1.1" 301 162 0.000 "-" "-"
167.94.145.105 - - [15/Dec/2024:23:32:41 +0000] "GET / HTTP/1.1" 301 162 0.000 "-" "Mozilla/5.0 (compatible; CensysInspect/1.1; +https://about.censys.io/)"
80.66.83.48 - - [15/Dec/2024:23:56:38 +0000] "\x04\x01\x00PPBS0\x00" 400 150 0.307 "-" "-"
80.66.83.48 - - [15/Dec/2024:23:56:39 +0000] "\x05\x01\x00" 400 150 0.312 "-" "-"
80.66.83.48 - - [15/Dec/2024:23:56:40 +0000] "CONNECT 80.66.83.48:80 HTTP/1.1" 400 150 0.311 "-" "-"
118.193.64.188 - - [16/Dec/2024:00:25:27 +0000] "GET / HTTP/1.1" 301 162 0.000 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0"
118.193.64.188 - - [16/Dec/2024:00:25:46 +0000] "GET /favicon.ico HTTP/1.1" 301 162 0.000 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_0) AppleWebKit/535.11 (KHTML, like Gecko) Chrome/17.0.963.56 Safari/535.11"
118.193.64.188 - - [16/Dec/2024:00:25:48 +0000] "GET /robots.txt HTTP/1.1" 301 162 0.000 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_0) AppleWebKit/535.11 (KHTML, like Gecko) Chrome/17.0.963.56 Safari/535.11"
118.193.64.188 - - [16/Dec/2024:00:25:50 +0000] "GET /sitemap.xml HTTP/1.1" 301 162 0.000 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_0) AppleWebKit/535.11 (KHTML, like Gecko) Chrome/17.0.963.56 Safari/535.11"
192.99.13.69 - - [16/Dec/2024:00:37:20 +0000] "GET /robots.txt HTTP/1.1" 301 162 0.000 "-" "Mozilla/5.0 (compatible; MJ12bot/v1.4.8; http://mj12bot.com/)"
192.99.13.69 - - [16/Dec/2024:00:37:23 +0000] "GET / HTTP/1.1" 301 162 0.000 "-" "Mozilla/5.0 (compatible; MJ12bot/v1.4.8; http://mj12bot.com/)"
18.222.226.15 - - [16/Dec/2024:00:53:27 +0000] "\x16\x03\x01\x00{\x01\x00\x00w\x03\x03-\xE5\x08v\xB3u\xEA\x10B\xC4\xC4YX\xEE\xE6\xD5\xA6\xC4\x08\xA5+g\x90\xFD\xEE\xAD\xE1\xD1@\x1A\xA1f\x00\x00\x1A\xC0/\xC0+\xC0\x11\xC0\x07\xC0\x13\xC0\x09\xC0\x14\xC0" 400 150 1.633 "-" "-"
40.88.21.235 - - [16/Dec/2024:01:07:16 +0000] "GET / HTTP/1.1" 301 162 0.000 "http://prod3.openfoodnetwork.org.au/" "DuckDuckBot/1.1; (+http://duckduckgo.com/duckduckbot.html)"
71.6.232.27 - - [16/Dec/2024:01:22:58 +0000] "GET / HTTP/1.1" 301 162 0.000 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36"
199.45.154.135 - - [16/Dec/2024:01:34:16 +0000] "GET / HTTP/1.1" 301 162 0.000 "-" "-"
199.45.154.135 - - [16/Dec/2024:01:34:27 +0000] "GET / HTTP/1.1" 301 162 0.000 "-" "Mozilla/5.0 (compatible; CensysInspect/1.1; +https://about.censys.io/)"
172.105.128.12 - - [16/Dec/2024:02:00:30 +0000] "\x16\x03\x01\x00\xEE\x01\x00\x00\xEA\x03\x03\xB5\x1A\xEB2@\xC2\x07\xB6i/\xF1>\xFE\x97\xC9\xBD\x8C\xF8\x0B*\xC8BB\xC9V\x88_P\xAD\xEFg\xC6 D\xDF\x1B\xCA" 400 150 0.230 "-" "-"
66.240.205.34 - - [16/Dec/2024:02:20:09 +0000] "145.ll|'|'|SGFjS2VkX0Q0OTkwNjI3|'|'|WIN-JNAPIER0859|'|'|JNapier|'|'|19-02-01|'|'||'|'|Win 7 Professional SP1 x64|'|'|No|'|'|0.7d|'|'|..|'|'|AA==|'|'|112.inf|'|'|SGFjS2VkDQoxOTIuMTY4LjkyLjIyMjo1NTUyDQpEZXNrdG9wDQpjbGllbnRhLmV4ZQ0KRmFsc2UNCkZhbHNlDQpUcnVlDQpGYWxzZQ==12.act|'|'|AA==" 400 150 0.165 "-" "-"
45.79.115.59 - - [16/Dec/2024:02:31:14 +0000] "\x16\x03\x01\x00u\x01\x00\x00q\x03\x03V\xF7\xA7L\x09Yog\x0EB\xABow\xF5A\xE0\xA0\xBF\x93g*\xA5\x87B" 400 150 3.701 "-" "-"
172.212.73.231 - - [16/Dec/2024:02:41:41 +0000] "GET /owa/auth/logon.aspx HTTP/1.1" 301 162 0.000 "-" "Mozilla/5.0 zgrab/0.x"
```

shutdown 🖥️ 💤

**Comment by dacook** [comment]
Backups looking good:
![Screenshot 2024-12-16 at 2 09 17 PM](https://github.com/user-attachments/assets/a2ac9b7c-5b93-4ae6-99db-cc7e216b0e2e)

**Comment by dacook** [comment]
> prod3.openfoodnetwork.org.au is being shut down.
>
> A 49.74 AUD credit has been added to your account.  Note this is a credit on your account.  You will not receive a refund.
> 
> If you need to un-cancel the server please contact our support team.
> 
> Thank you for having hosted prod3.openfoodnetwork.org.au with us.
