### ISSUE TITLE
Setup ENV vars

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/ofn-install#98]
We do need a way to provision env vars in our servers. This is needed for https://github.com/openfoodfoundation/ofn-install/issues/97 and also https://github.com/openfoodfoundation/ofn-install/issues/85. The latter  was the culprit of emails not being sent in the US instance. Very annoying.

**Comment by Matt-Yorkley** [comment]
Maybe a separate playbook/role for updating the ENV vars on an existing instance would be useful?

**Comment by sauloperez** [comment]
The way is https://github.com/openfoodfoundation/ofn-install/pull/137 and https://github.com/openfoodfoundation/ofn-install/pull/153 we could even DRY that but it's not a big deal for now.

Thanks for the heads-up. We can close this now.
